### ISSUE TITLE
Remove check for data index availability on legacy Quarkus Dev UI extensions

### ISSUE THREAD

**Issue by paulovmr** [apache/incubator-kie-issues#1009]
When using the previous Dev UI (Quarkus 2), our extensions check during the rendering of their cards if data index is available or not before showing the links to access it. 

When the data index is not available, it is hard to identify the issue in the browser. Always having the links available and letting the extension UI show the error would be more informative.

**Comment by yesamer** [comment]
@paulovmr I noticed this is marked as Done. In such a case, can you please close this ticket and link the PR (if any)?
