### ISSUE TITLE
React-Based DMN Editor: Data type not imported correctly

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#1018]
if the `itemDefinition` does not contain the id attribute, it is not correctly shown/managed in the editor

![Unknown](https://github.com/apache/incubator-kie-issues/assets/16005046/d32d6dfd-e9cc-48ae-b358-4e2453a17d35)

![Unknown-2](https://github.com/apache/incubator-kie-issues/assets/16005046/755e7a5f-adcc-497b-90ce-e05f6954ddf3)

From above, it seems optional, so editor should be able to work without it (being a namedElement, editor should rely on required “name” attribute)

[XSD](https://github.com/apache/incubator-kie-drools/blob/4004fe9bf745c5eae18223cd1d3a42d8efd4566e/kie-dmn/kie-dmn-validation/src/main/resources/org/kie/dmn/validation/org/omg/spec/DMN/20230324/DMN15.xsd) excerpt (`tItemDefinition → tNamedElement → tDMNElement`)

```xml
<xsd:complexType name="tItemDefinition">
	<xsd:complexContent>
		<xsd:extension base="tNamedElement">
...
<xsd:complexType name="tNamedElement">
		<xsd:complexContent>
			<xsd:extension base="tDMNElement">
              <xsd:attribute name="name" type="xsd:string" use="required"/>
...
<xsd:complexType name="tDMNElement">
	...
	<xsd:attribute name="id" type="xsd:ID" use="optional"/>
```

**Comment by tiagobento** [comment]
This is already fixed in https://github.com/apache/incubator-kie-tools/pull/2131. This PR, however, is blocked by https://github.com/apache/incubator-kie-tools/pull/2202, which should be merged in ~1 week. We'll get there.
