### ISSUE TITLE
BPMN Editor: Zooming in/out does not update the toolbox for correct size

### ISSUE THREAD

**Issue by inodeman** [apache/incubator-kie-issues#102]
When the user zooms in/out the position and size of the toolbox does not get updated. See image below

<img width="785" alt="image" src="https://user-images.githubusercontent.com/39567766/216159329-4ea40b08-441c-43af-90f8-f9da9d36bba7.png">

**Comment by yesamer** [comment]
@inodeman Is this probably related to https://github.com/kiegroup/kie-issues/issues/29 ?
