### ISSUE TITLE
React-Based DMN Editor: typeConstraint unsupported

### ISSUE THREAD

**Issue by gitgabrio** [apache/incubator-kie-issues#1020]
The current version does not allow creation of `typeConstraint`. Constraints are always mapped to `allowedValues`.
`typeConstraint` and `allowedValues` have a slightly different semantics.
 `allowedValues` is currently deprecated, but for the moment being both have to be managed

![Image](https://github.com/apache/incubator-kie-issues/assets/765578/0feb4835-99ac-4fc2-ba2a-b66f050c5419)

![Image](https://github.com/apache/incubator-kie-issues/assets/765578/ee4001f5-725d-495f-aa32-5d4d45ea5719)

```xml
<dmn:itemDefinition id="_20166AAE-06F8-4045-8F90-6EDF4990E91E" name="typeStringCollection" isCollection="true" typeLanguage="https://www.omg.org/spec/DMN/20230324/FEEL/">
     <dmn:typeRef>string</dmn:typeRef>
     <dmn:typeConstraint kie:constraintType="expression" id="_7A2D84BB-D6B9-4321-9BE0-7371D9F53D9A">
       <dmn:text>count (?) = 1</dmn:text>
     </dmn:typeConstraint>
```

**Comment by tiagobento** [comment]
Done on purpose, as we figured we should just keep the old behavior. But yeah, it's a gap, absolutely. We thought about converting all `allowedValues` usages to `typeConstraints`, as we have a migration mechanism, but we didn't do it yet, as it may be a little complicated.

What do you suggest for exposing this capability to users?

The suggestion I have would be giving users the possibility to chose between projecting (`allowedValues`) vs. not projecting (`typeConstraint`) for collection types, using a [ToggleGroup](https://www.patternfly.org/components/toggle-group#default-with-single-selectable). Of course, with a warning that projecting (`allowedValues`) is deprecated.

**Comment by gitgabrio** [comment]
@tiagobento 
I would personally create another row to insert those other constraints, and give specific names to both, so on one side the user may insert "allowedValues" and on the other side typeConstraints. They are not mutually exclusive.

```xml
<xsd:extension base="tNamedElement">
				<xsd:choice>
					<xsd:sequence>
						<xsd:element name="typeRef" type="xsd:string"/>
						<xsd:element name="allowedValues" type="tUnaryTests" minOccurs="0"/>
						<xsd:element name="typeConstraint" type="tUnaryTests" minOccurs="0"/>
					</xsd:sequence>
```

When/if the allowedValues will be definetely removed, then also the old input box will be.
I hope to have been clear - pls let me know if I'm not

**Comment by tiagobento** [comment]
As we discussed today between @ljmotta @gitgabrio @yesamer, we think the best course of action right now is:

1. For non-collection types, we read constraints from `allowedValues` and `typeConstraints`, defaulting to `typeConstraints` if both are present. When writing, we always choose `typeConstraint`.
3. For collection types, we show two Constraints sections. One for `allowedValues` and another for `typeConstraint`, with respective explanations on what's the difference between them. IMHO we shouldn't expose those names to the screen, but rather present their semantic.

In the future, if the `allowedValues` property is removed from the DMN spec, we can migrate models to extract a new type specific for the items of a collection type using `allowedValues`, and copying the `allowedValues` expression to its `typeConstraint` value. The `typeRef` of the collection type would refer to this new type.

**Comment by gitgabrio** [comment]
It seems  that the editor crashes as soon as an expression is inserted.
`typeConstraint` has a distinct meaning only when applied to collections, and the only way to define a costraint on a collection is to use expressions.

![immagine](https://github.com/apache/incubator-kie-issues/assets/765578/2d41cf4f-82b8-4eb4-acf7-5818fda35077)


```xml
<?xml version="1.0" encoding="UTF-8" ?>
<definitions xmlns="https://www.omg.org/spec/DMN/20230324/MODEL/" xmlns:dmndi="https://www.omg.org/spec/DMN/20230324/DMNDI/" xmlns:dc="http://www.omg.org/spec/DMN/20180521/DC/" xmlns:di="http://www.omg.org/spec/DMN/20180521/DI/" xmlns:kie="https://kie.org/dmn/extensions/1.0" expressionLanguage="https://www.omg.org/spec/DMN/20230324/FEEL/" namespace="https://kie.org/dmn/_992148AC-AC3F-4BC2-B8D0-1E4E3A1F3FB7" id="_F92B359C-9BC4-45AD-B3FE-BF86D69BA72A" name="DMN_61E36801-2864-4FFA-9471-287B9DEAFEA6">
  <itemDefinition id="_948BA971-898E-4F5F-9C17-3F367DAC289F" name="tInterests" isCollection="true" typeLanguage="https://www.omg.org/spec/DMN/20230324/FEEL/">
    <typeRef>string</typeRef>
    <typeConstraint kie:constraintType="expression" id="_A18EBD2D-1C96-4A28-98AB-A5F941246CFE">
      <text>count(?) = 2</text>
    </typeConstraint>
  </itemDefinition>
  <inputData name="New Input Data" id="_9CB691B7-0B6A-4633-B528-0E2BDD3EC4DC">
    <variable name="New Input Data" id="_42D2C638-7E11-400D-8C34-C458F827D7DD" typeRef="tInterests" />
  </inputData>
  <decision name="New Decision" id="_9228CD94-8DFA-4645-B163-243C7F01818B">
    <variable id="_B3D9B2B0-AA3F-4ABB-8E78-08A212F4DE0C" typeRef="Any" name="New Decision" />
    <informationRequirement id="_3302E414-47AA-49F4-B618-209AA1CA0BDA">
      <requiredInput href="#_9CB691B7-0B6A-4633-B528-0E2BDD3EC4DC" />
    </informationRequirement>
    <literalExpression id="_6CED4ABF-F3D9-4C56-BB16-89DFC5A3D172" typeRef="Any" label="New Decision">
      <text>New Input Data</text>
    </literalExpression>
  </decision>
  <dmndi:DMNDI>
    <dmndi:DMNDiagram id="_3B7A0C00-6FD1-4EF6-A7F2-AE92840A0F2F" name="Default DRD" useAlternativeInputDataShape="false">
      <di:extension>
        <kie:ComponentsWidthsExtension>
          <kie:ComponentWidths dmnElementRef="_6CED4ABF-F3D9-4C56-BB16-89DFC5A3D172">
            <kie:width>190</kie:width>
          </kie:ComponentWidths>
        </kie:ComponentsWidthsExtension>
      </di:extension>
      <dmndi:DMNShape id="_49A209C0-7F13-4A59-A506-78A1EE98C05F" dmnElementRef="_9CB691B7-0B6A-4633-B528-0E2BDD3EC4DC" isCollapsed="false" isListedInputData="false">
        <dc:Bounds x="100" y="60" width="160" height="80" />
      </dmndi:DMNShape>
      <dmndi:DMNShape id="_9DC82C21-D22E-4742-A96F-2F097422DE94" dmnElementRef="_9228CD94-8DFA-4645-B163-243C7F01818B" isCollapsed="false" isListedInputData="false">
        <dc:Bounds x="480" y="60" width="160" height="80" />
      </dmndi:DMNShape>
      <dmndi:DMNEdge id="_34CF9A9A-300E-4D27-8C39-DC5F98761137-AUTO-TARGET" dmnElementRef="_3302E414-47AA-49F4-B618-209AA1CA0BDA" sourceElement="_49A209C0-7F13-4A59-A506-78A1EE98C05F" targetElement="_9DC82C21-D22E-4742-A96F-2F097422DE94">
        <di:waypoint x="180" y="100" />
        <di:waypoint x="560" y="100" />
      </dmndi:DMNEdge>
    </dmndi:DMNDiagram>
  </dmndi:DMNDI>
</definitions>
```

@tiagobento @ljmotta @jomarko @yesamer

**Comment by tiagobento** [comment]
Do we have any updates on this task? cc @ljmotta @gitgabrio @yesamer

**Comment by gitgabrio** [comment]
@tiagobento @ljmotta @yesamer 
Recently we found and fixed [a bug](https://github.com/apache/incubator-kie-issues/issues/1100) in the json chema production that, IINW, was somehow related also to that.
We are also working to [further improve](https://github.com/apache/incubator-kie-issues/issues/1112) json schema generation.
Beside that, I'm not sure how things are going on the frontend side.

**Comment by ljmotta** [comment]
@gitgabrio I guess the improvement on (https://github.com/apache/incubator-kie-issues/issues/1112) is not part of the scope of this issue as the editor already enables to set the `typeConstraint` and `allowedValues` for collection item definitions. WDYT? Can we close this issue?

**Comment by gitgabrio** [comment]
@ljmotta if the frontend has been tested and verified to use typeCOnstraints and related expressions without issue, fine for me 👍
