### ISSUE TITLE
Upgrade Optaplanner Quarkus Extension DevUI

### ISSUE THREAD

**Issue by pefernan** [apache/incubator-kie-issues#1021]
OptaPlanner Quarkus Extension still uses the `DevUI v1` that will be deprecated in next Quarkus relaeses (`3.8 LTS`). We should upgrade the extension to make it available in the new DevUI and remove the `v1` components to avoid problems when upgrading to `3.8 LTS`.

**Comment by pefernan** [comment]
@lucamolteni I'm going to tackle this now, will ask for some input in the PR ..

**Comment by lucamolteni** [comment]
@pefernan I worked on this already, see my branch https://github.com/apache/incubator-kie-optaplanner/compare/main...lucamolteni:optaplanner:958-bis?expand=1

**Comment by pefernan** [comment]
Great @lucamolteni going to close this issue! Let me know if you need me to review the PR !

**Comment by lucamolteni** [comment]
Original issue https://github.com/apache/incubator-kie-issues/issues/958
