### ISSUE TITLE
Upgrade `pnpm` from `7.0.0` to latest (`7.26.3`) on `kie-tools`

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#103]
`pnpm` has a very rapid release cadance, and `kie-tools` has been using the fixed `7.0.0` version for a while now. We need to upgrade so we don't lack behind so much.

**Comment by tiagobento** [comment]
@pefernan FYI https://issues.redhat.com/plugins/servlet/mobile#issue/KOGITO-7854

**Comment by pefernan** [comment]
@tiagobento thanks! still have my RH account blocked but will got some details about the jira
