### ISSUE TITLE
Cannot model DMN model that imports other model with empty import name

### ISSUE THREAD

**Issue by baldimir** [apache/incubator-kie-issues#1066]
When I model a decision (from scratch using the new DMN editor), that uses an imported BKM (also modelled in the editor), imported using the empty name (1.5 feature), it doesn't work with the runner (I am getting Unknown variable 'sayHello' errors - sayHello is the name of the imported BKM). I see the potential problem could be, how the editor adds the knowledgeRequirement: 
```
<knowledgeRequirement id="_F4D15B4D-63AF-4956-9C39-96A1D2334146">
    <requiredKnowledge href="https://kie.org/dmn/_CDC1C967-6384-4BA9-989A-AC5385DDDFF7#_05703942-965D-4D2A-9579-E23A91DBB373" />
</knowledgeRequirement>
```
It is added with the namespace prefix (namespace before #). The namespace shouldn't be there, because the import with empty name imports into the default namespace of the model. This is from spec: 

> When the import name attribute is an empty string, the elements are imported in the default namespace of the
model. When a name collision occurs between an element in the default namespace and an imported element,
the imported element does not replace the one already in the default namespace while the elements without
name collision are imported.

So it should be used like this:
```
<knowledgeRequirement id="_F4D15B4D-63AF-4956-9C39-96A1D2334146">
    <requiredKnowledge href="#_05703942-965D-4D2A-9579-E23A91DBB373" />
</knowledgeRequirement>
```

**Comment by tiagobento** [comment]
As we discussed, there are two different interpretations here... one is related to FEEL namespaces, as referred to in here:

![image](https://github.com/apache/incubator-kie-issues/assets/1584568/348b2420-6453-4e78-a6de-a47dc86aa74d)


Namespace here means "the string before the `.`".

And the other is the namespace used in HREFs. 

The way I understood it is that only the FEEL namespace should be affected by the `name` property of `import`s. It's odd to think that the `name` of the `import` would change the way we write HREFs.

Anyway, pending confirmation from the DMN experts. Thanks @baldimir for raising this!

**Comment by tiagobento** [comment]
Found something that may help clarify it in "12.3.2 References within the DMN XSD"

<img width="872" alt="image" src="https://github.com/apache/incubator-kie-issues/assets/1584568/6baa6138-ee50-459c-a8b7-245e8e08f68a">

Source: https://www.omg.org/spec/DMN/1.5/Beta1/PDF
