### ISSUE TITLE
DMN Editor: width and height properties are not validated

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#1074]
DMN node width and height properties can be set using Properties panel component. The issue is the properties panel allows users to put any value.
- Good thing is that that real node is not resized below its minimal size
- Bad is user is not informed that invalid value was put into the form

See the attached screenshot. There is selected a **Decision** node. Its minimal size is 160x80. The node keeps this minimal size even lower value was put into the form (20x10). However we should propbably:
- reset properties panel form inputs to minimal value
- or mark form input values as invalid, red background or sth similar
- or not have a minimal size for nodes
- or ...

![Screenshot 2024-04-10 091929](https://github.com/apache/incubator-kie-issues/assets/8044780/84e57f25-90ad-429d-b0b5-a83a9ee1f881)

**Comment by jomarko** [comment]
The issue is related to our `ShapeOptions.tsx` component.

Here, we display `width` form field using Patternfly `TextInput`:
```js
  <TextInput
    aria-label={"Width"}
    data-testid={"kie-tools--dmn-editor--properties-panel-node-shape-width-input"}
    type={"number"}
    isDisabled={isDimensioningEnabled ? false : true}
    value={isDimensioningEnabled ? boundWidth : undefined}
    placeholder={isDimensioningEnabled ? "Enter a value..." : undefined}
    onChange={onChangeWidth}
    style={{ maxWidth: "80px", minWidth: "60px", border: "none", backgroundColor: "transparent" }}
  />
```

to indicate invalid width, it is enough to add a property `validated={ValidatedOptions.error}` to the `TextInput` component. So one part of the ticket should be doable easily.
![Screenshot 2024-04-19 132711](https://github.com/apache/incubator-kie-issues/assets/8044780/49c5339b-30f1-49ac-a334-922296c58100)

in pseudocode we would change to:
```js
{!isWidthValid&& 
      <TextInput
        validated={ValidatedOptions.error}
        aria-label={"Width"}
        data-testid={"kie-tools--dmn-editor--properties-panel-node-shape-width-input"}
        type={"number"}
        isDisabled={isDimensioningEnabled ? false : true}
        value={isDimensioningEnabled ? boundWidth : undefined}
        placeholder={isDimensioningEnabled ? "Enter a value..." : undefined}
        onChange={onChangeWidth}
        style={{ maxWidth: "80px", minWidth: "60px", border: "none", backgroundColor: "transparent" }}
      />
    }
```

the missing part is `isWidthValid` logic. We have minimal size logic already present in `DefaultSizes.ts`, to be more precise, `MIN_NODE_SIZES`. This is crucial to be able to implement `isWidthValid`, however it requires knowing node type.

However, node type is not present in the `ShapeOptions.tsx` component. We have only `nodeIds` and `dmn store`. I somehow feel node type could be computed thanks to `node id` and `dmn store`, but as newbie in this codebase, I am not sure.

Any advice would be more than welcome.

For the `height` all comments are the same as for `width`.

**Comment by ljmotta** [comment]
@jomarko The `store` is where the DMN Editor state is located. You can take a look into the `Store.ts` and there we'll have the values and the methods to retrieve the information. It's important to always use the `computed` methods, so the component will only re-render when the specific value was changed, minimizing the re-renders.

You can retrieve the node minimal size by doing something like this inside the `setBounds` method:
```ts
const node = nodeIds.map((nodeId) =>
  s.computed(s).getDiagramData(externalModelsByNamespace).nodesById.get(nodeId)
)[index];
if (node === undefined) {
  throw new Error(`DMN Element with index ${index} is not a Node.`);
}
const minNodeSize = MIN_NODE_SIZES[node.type as NodeType]({ snapGrid: s.diagram.snapGrid, isAlternativeInputDataShape: s.computed(s).isAlternativeInputDataShape() });

``` 

It also requires to get the ` externalModelsByNamespace`  which you can do on the component:
```
  const { externalModelsByNamespace } = useExternalModels();
```
