### ISSUE TITLE
Build and test development/showcase webapps on KIE Tools GitHub Actions workflows

### ISSUE THREAD

**Issue by Josephblt** [apache/incubator-kie-issues#109]
Throughout the many projects in KIE Tools, we have several web apps which we use for development, demonstrations, testing, etc. We must find ways to ensure these web apps work at all times. Some of them already have testing strategies implemented some don't. Among those existing test strategies, we can find examples using Cypress and Selenium.

The ideal scenario is to standardize everything using a single test framework, like [PlayWright](https://playwright.dev/), a more up-to-date framework. Using Selenium should be considered as a second option. As a last resort, we can use anything, but the minimum goal is to have at least one test for each web app. Ensuring all web apps are functional.

- The first step is to map all existing web apps and their test strategies.
- Next, check the possibility of using the [PlayWright](https://playwright.dev/) framework for existing tests.
- After deciding on the framework, update existing tests and create missing ones.
- Last, add test execution stages to our existing GitHub Actions workflows.

**Comment by Josephblt** [comment]
I'll share here a document containing the mappings of webapps and test strategies.
[KIE Tools webapss mappings](https://ibm.box.com/s/mqy211s9nv2iu5d4v73j3c2ritiu974a)
This is a work in progress.

**Comment by Josephblt** [comment]
Hello @tiagobento, please if you could take a look and share some feedback that would be great.

**Comment by tiagobento** [comment]
As a note for the future, we need to include tests for Showcase/Dev webapps building them with the `--env live` option as well. This option enables multi-package live reloading of components. Please search for this issue's URL on the code to see references to it.

**Comment by Josephblt** [comment]
This issue can be closed. The research work was used here:
https://github.com/apache/incubator-kie-issues/issues/457.
