### ISSUE TITLE
EPIC - Move SonataFlow CLI, builder, and devmode images back to SonataFlow Operator repository after 10.x

### ISSUE THREAD

**Issue by ricardozanini** [apache/incubator-kie-issues#1102]
As discussed in the ML, we need a plan to solve the cyclic dependencies between the CLI, images, and operator. 

Those components will reside in the same repository: https://github.com/apache/incubator-kie-kogito-serverless-operator. 

Preemptive tasks for this EPIC:

1. Move kn-workflow plugin to a new `cmd` module within the operator, and make the dependencies local via the `go.work` file
2. Move the builder and devmode images to the same repository to the already created `images` module where we already build the operator image with Cekit.
3. Review the PR GHA checks to run image tests once there's a change in the `images` module
4. Review the PR GHA checks to run CLI tests once there's a change in the `cmd` module
5. Create a new GHA for releasing the CLI directly on the GH Release page
6. Create a new GHA for releasing the images directly to image repository

**Comment by tiagobento** [comment]
`kogito-swf-builder` and `kogito-swf-devmode` images were never in the Serverless Operator repository. Neither was `kn-plugin-workflow`. We've seen requests for coordination for this move, but we don't have any yet. This EPIC mentions moving stuff to the Serverless Operator repository, but doesn't mention how this will play out in the higher-level, like dependencies with other repositories or changes to release automations that need to take place too. Please consider all these angles too.

**Comment by ricardozanini** [comment]
Closed as we won't move anything anymore.
