### ISSUE TITLE
Add tests for equality operators in positive unary tests to the TCK suite

### ISSUE THREAD

**Issue by kbowers-ibm** [apache/incubator-kie-issues#111]
Linked to https://github.com/kiegroup/kie-issues/issues/22

The engine supports equality operators (=, !=) in the positive unary tests, however there are no tests for this. Add tests for the equality operators.

Acceptance criteria:

- New code has 0 new security vulnerabilities.
- New tests defining compliance for this added to the TCK suite https://github.com/dmn-tck/tck.

**Comment by baldimir** [comment]
As the TCK tests are outside organization, they may take longer time to be merged. So closing this as done.
