### ISSUE TITLE
DMN Editor local variable autocompletion `for`, `some` and `every`

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#1138]
This issue is related to new DMN 1.5 expression types, autocompletion and the ticket #1124.

Especially to `for`, `some` and `every` expressions. These are used to iterate collections using a local variable. The issue is this local variable is not recognized by the autocompletion feature. In the screenshot below, the local variable is `x`. We can see the autocompletion marks it with 🔴 as not known variable. The variable `x` shouldn't be marked with 🔴 .
![for-loop-x](https://github.com/apache/incubator-kie-issues/assets/8044780/3d82322f-1170-4cb7-892b-30655d6be620)

**Comment by tiagobento** [comment]
Duplicated from:
- #1135 
- #1134
