### ISSUE TITLE
DMN Editor produces invalid typeRef attributes

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#1149]
This issue will describe the situation using `for` expression, however probably all DMN 1.5. expressions may have this issue.

In the attached screenshots we see two semantically same for expression. The good thing is that models can be executed, as we see in the DMN Runner panel on the right side, however the extended-services report validation issues to us.

![Screenshot 2024-05-03 132440](https://github.com/apache/incubator-kie-issues/assets/8044780/a033e2e7-c14f-4528-90dd-fc5db79cd454)
![Screenshot 2024-05-03 123506](https://github.com/apache/incubator-kie-issues/assets/8044780/4ce43679-23dd-4bae-92ba-9ec636a07ac6)

If we take a look into produced xml code, we will notice `typeRef="&lt;Undefined&gt;"` on few places, especially in the nested parts of the `<in>` and `<return>`. 

- [for-expression.dmn.txt](https://github.com/apache/incubator-kie-issues/files/15199976/for-expression.dmn.txt)
- [for-more-complex.dmn.txt](https://github.com/apache/incubator-kie-issues/files/15199975/for-more-complex.dmn.txt)

To solve the problem `typeRef` pointing to `<Undefined>` shouldn't be present in the xml **or** the `typeRef` should point to a correct data type. In the attached models:
- `<in>` nested expression should point to `tNumHolderList`
- `<return>` nested expression should point to `tNumHolder`

here are version of file, without validation issues:

- [for-expression-fixed.dmn.txt](https://github.com/apache/incubator-kie-issues/files/15199990/for-expression-fixed.dmn.txt)
- [for-more-complex-fixed.dmn.txt](https://github.com/apache/incubator-kie-issues/files/15200006/for-more-complex-fixed.dmn.txt) <- contains validation issues but not related to `typeRef` probably

**Comment by danielzhe** [comment]
Nice founding, @jomarko !
