### ISSUE TITLE
On the Boxed Expression Component, changing the ExpressionVariableCell text content will fail to commit if the focus is changed to another cell

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#1158]
For boxed expressions `some`, `every`, `invocation` and `decision table annotation` user can not commit the text of specific cell, see the attached screenshot by click into cell that is `Undefined`, clicking outside the boxed expression most parent works and changes are committed. 

![Screenshot 2024-05-06 175436](https://github.com/apache/incubator-kie-issues/assets/8044780/217e3de1-489c-4046-889b-2f1c424e86d5)

### Steps to reproduce
- Start to type a text into the red cell
- Click into the blue cell - **text is lost**
- vs click outside the boxed expression root - **text is saved**

**Comment by ljmotta** [comment]
This issue is related to the Boxed Expression Component, and it will happen to all expressions that uses the `ExpressionVariableCell` component. Clicking on any cell will cause to not commit the changes, only clicking outside the BEE component will work, or using the keyboard (enter/tab).
