### ISSUE TITLE
Upgrade 3rd party GitHub Actions that are deprecated because of Node 12 on `kie-tools`

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#116]
On the automated builds of `kie-tools`, there are some 3rd party GitHub Actions that need to be upgraded, as they're depending on Node 12.

The message below can be found on our workflows Summaries.

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: runforesight/workflow-telemetry-action@7af88337f61e495d20c0ffa970cf7691532af740, actions/setup-node@v2, stCarolas/setup-maven@417e1a9899611c0350621d1fb0c2770f35105c69, al-cheb/configure-pagefile-action@7e234852c937eea04d6ee627c599fb24a5bfffee. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12

**Comment by kbowers-ibm** [comment]
3 additional deprecated GitHub Actions that need to be upgraded:

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: ilammy/msvc-dev-cmd@376515093de803c897e7e6d576553c3104267e17, ayltai/setup-graalvm@3789c9412212eb6d435725e49d28e179a46b1aaa, actions/upload-artifact@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by kbowers-ibm** [comment]
ilammy/msvc-dev-cmd - tried switching to the latest commit and the commit that changed it to node 16, but it throws an error
ayltai/setup-graalvm - Switched to latest commit SHA successfully, however it was archived and was not updated to use node 16.
