### ISSUE TITLE
incubator-kie-tools missing header files

### ISSUE THREAD

**Issue by porcelli** [apache/incubator-kie-issues#1163]
Following files has been listed by the RAT tool. Still under the investigation if all of them require license, but some are clearly needed like Java files.

https://gist.github.com/porcelli/69467dc36462fa4a42339e697d50fd59

**Comment by porcelli** [comment]
@LightGuard fyi

**Comment by LightGuard** [comment]
The following kinds of files need to be updated to include the ASL license header:

* Makefiles
* mod (go.mod)
* sum (go.sum)
* Go
* YAML (yaml and yml)
* Dockerfiles
* BPMN
* Typescript
* CSS
* XSD
* DMN
* JavaScript
* Properties
* Java
* XML
* SVG (to be safe)
* txt files (if adding the header will not break the test)
* helm files
* scesim (if comments are supported)
* `.config` (if adding it doesn't break the tests)
* HTML files for testing
* less
* README (if more than simple few line readme file)
* FTL
* Markdown
* .template (if comments are available)
* sh files

I am not sure what a `.snap` file is.
I have no idea what a `.wid` file is.
Not sure about `.genmodel` and `.ecore` files
