### ISSUE TITLE
incubator-kie-kogito-runtimes files needing license headers

### ISSUE THREAD

**Issue by LightGuard** [apache/incubator-kie-issues#1168]
https://gist.github.com/LightGuard/188c26bc21ba59dd16e2279215872498

The following kinds of files need to be updated to include the ASL license header:

* Makefile
* BPMN
* DMN
* XML
* graphqls (if comments are supported)
* Properties
* SQL
* Markdown
* Dockerfiles
* Significant text files
* YAML (yaml and yml)
* PMML
* scesim
* conf files
* XSD
* SVG (to be safe)

**Comment by LightGuard** [comment]
[Uploading incubator-kie-kogito-runtimes-rat-report.txt…]()

**Comment by LightGuard** [comment]
@porcelli

**Comment by LightGuard** [comment]
Full Report: 
[incubator-kie-kogito-runtimes-rat-report.txt](https://github.com/apache/incubator-kie-issues/files/15229012/incubator-kie-kogito-runtimes-rat-report.txt)

**Comment by baldimir** [comment]
Partial fixes in this branch https://github.com/baldimir/kogito-runtimes/tree/update-copyright. The repository contains the rat plugin, so it can be used with this branch.
