### ISSUE TITLE
BPMN Editor: Enable auto population of DMN fields in Business Rule Task

### ISSUE THREAD

**Issue by inodeman** [apache/incubator-kie-issues#117]
When selecting DMN as rule language, the following fields should be fetched from a selected file name (New Field) and the following fields should be populated

Namespace, Decision Name (Dropdown) and DMN Model Name

The new field File Name should be marshalled and unmarshalled accordingly in BPMN Model

<img width="372" alt="image" src="https://user-images.githubusercontent.com/39567766/219126787-ab689401-138a-4da4-ba4c-9f126c8db02a.png">

**Comment by inodeman** [comment]
Hi @porcelli @tiagobento I have a couple of questions regarding this. 1) What should happen if there are no dmn files, should the user be able to just type a name? 2) What should happen if in a DMN file there are no decision nodes, should the user be able to type it? Thanks, let me know

**Comment by porcelli** [comment]
@inodeman please let us know what you think should be the behavior, so we can discuss based on your input.

**Comment by inodeman** [comment]
Hi @porcelli @tiagobento I think enabling the user an input in both cases even if there are files, decision nodes will give the most flexibility, for example if there are files, the user could still input a file if he/she chooses to, same thing on the Decision Name, let me know what you think.

**Comment by inodeman** [comment]
I mention this since the user can still modify namespace/dmn model name even if fetched the values from files input, let me know

**Comment by tiagobento** [comment]
@inodeman +1 for your suggestion. Flexibility is good.

**Comment by jomarko** [comment]
is this 'flexibility' compatible with DMN validation we have ? won't this cause an error in 'Problems' tab about referenced non existing DMN model, Decision node?

**Comment by porcelli** [comment]
@jomarko it's unrelated at this point; it’s a simple XML scan at this point. But we don’t want different XML scanners around, thus the ask from @tiagobento to align with existing DMN xml scanner that @ljmotta already implemented

**Comment by ljmotta** [comment]
Hi @inodeman I've found a bug for this feature. The KIE Sandbox FS hangs if you try to import a DMN in a BPMN that was renamed **_after_** the node was created. All the following edits will not be saved, but If you delete the Business Rule node, the FS will be recovered.

Steps to reproduce:
 - Create a new BPMN;
 - Create a new activitity node;
 - Convert the node to a Business Rule;
 - Rename the file;
 - Try to import a DMN;

## video
https://github.com/kiegroup/kie-issues/assets/24302289/d2cf8ad1-b6dd-4afc-91e1-8eff5ea5965e

**Comment by inodeman** [comment]
Hi @ljmotta thanks for looking and reporting it, I will take a look

**Comment by ljmotta** [comment]
@inodeman I've created a different issue for this bug (https://github.com/kiegroup/kie-issues/issues/530), and I'll close this one.
