### ISSUE TITLE
On the DMN Editor's Boxed Expression Editor, FEEL identifiers with spaces should be treated as non-breaking spaces.

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#1178]
Please see the attached file. There are multiple combinations showing that depending on the combination of new line characters and spaces, sometimes it breaks the syntax highlighting, sometimes it doesn't. Note, however, that the execution works fine for all cases.

[kie-issues-1178.dmn.txt](https://github.com/user-attachments/files/16149506/kie-issues-1178.dmn.txt)

<img width="2608" alt="image" src="https://github.com/apache/incubator-kie-issues/assets/1584568/3ee8b46d-d42f-4b6c-9897-22eb61b65e22">

**Comment by tiagobento** [comment]
@yesamer @gitgabrio @baldimir Do you guys have anything to add here? I mean, is there something that you know about that from the spec or something like that? Thanks!

**Comment by tiagobento** [comment]
Definitely a bug is this, though:

<img width="668" alt="image" src="https://github.com/apache/incubator-kie-issues/assets/1584568/571fa881-cefd-40ff-bf25-1d444d700ffa">

A variable name that doesn't contain spaces is still painted as if it were valid if we introduce a new line on the middle of its name.

**Comment by danielzhe** [comment]
I'm addressing scenarios like this one too:
(something) + variable with long name with break lines+ (something)
 
![image](https://github.com/user-attachments/assets/9dbb47e4-3d96-4b68-ad92-06a14d7eb4f2)

**Comment by danielzhe** [comment]
I'm following the runner as "The Truth" here: if the runner accepts it, it must be colorized as valid. If the runner considers it an error, then it's an error (paint with red), even if we think it's weird. 

I think the colorization should help users know what our engine accepts or not, even if it is something not usual like [SPACE][BREAK LINE][SPACE], in a variable that has only one space.
