### ISSUE TITLE
serverless-workflow-diagram-editor get ECONNREFUSED on bootstrap with a proxy

### ISSUE THREAD

**Issue by fantonangeli** [apache/incubator-kie-issues#1207]
Executing `pnpm bootstrap -F @kie-tools/sonataflow-quarkus-devui...` with a proxy we had the error:
       
[INFO] .../serverless-workflow-diagram-editor install: FetchError: request to https://repo1.maven.org/maven2/org/webjars/animate.css/3.5.2/animate.css-3.5.2.jar failed, reason: connect ECONNREFUSED

**Comment by tiagobento** [comment]
Did you manage to find a solution for this @fantonangeli ?

**Comment by fantonangeli** [comment]
@tiagobento I moved this issue as done in the board but forgot to close the issue
