### ISSUE TITLE
Adjust branch.yaml configurations and PR check scripts to dockerhub images and credentials

### ISSUE THREAD

**Issue by jstastny-cz** [apache/incubator-kie-issues#1213]
Adjust 
* .ci/jenkins/branch.yaml in:
  * kogito-pipelines:main
  * drools:main
  * optaplanner:main
* pr_check.groovy in kogito-pipelines

So that it points to dockerhub account, repositories and CI images.

**Comment by tiagobento** [comment]
After 
- #1211
