### ISSUE TITLE
[Release Automation] Replace explicit references to quay.io images across CI pipelines

### ISSUE THREAD

**Issue by jstastny-cz** [apache/incubator-kie-issues#1214]

**Comment by tiagobento** [comment]
Mostly `kogito-images`, but most likely there will be references in `kogito-runtimes`, `kogito-apps`, `optaplanner`.

**Comment by rodrigonull** [comment]
We want to run the weekly job on Monday to generate the timestamped snapshot images, so @jstastny-cz if you have time to work on this card on Monday morning, please feel free to do it.
