### ISSUE TITLE
Configure DockerHub credentials on KIE Tools CI pipelines

### ISSUE THREAD

**Issue by rodrigonull** [apache/incubator-kie-issues#1219]
- Add a new pipeline variable: `dockerHubUserCredentialsId = DOCKERHUB_USER` and `dockerHubTokenCredentialsId = DOCKERHUB_TOKEN` to the pipelineVars.groovy shared scripts file.
- Use the new credentials on KIE tools CI pipelines.

**Comment by tiagobento** [comment]
The kie-tools-build-ci image will continue being published to quay.io, all the others will eventually end up in DockerHub. We need to keep both credentials around for a while.
