### ISSUE TITLE
XLSX to DMN utility causes wrong informationRequirements

### ISSUE THREAD

**Issue by baldimir** [apache/incubator-kie-issues#122]
This is a clone of https://issues.redhat.com/browse/KOGITO-8712. For description and information, please check the linked JIRA.

**Comment by gitgabrio** [comment]
Reading the [Readme](https://github.com/apache/incubator-kie-drools/blob/main/kie-dmn/kie-dmn-xls2dmn-cli/README.md), 
1. that feature is marked as "experimental"
2. the tool seems working exactly as described  (`column to the left of the rightmost column in the Sheet, represent dependent InputData(s) or sub-Decision(s)`)
3. looking at the reproducer excel, I can't see a way to make it possibly working; I have the impression, the two "pelidatum" columns should be merged in one, with a proper FEEL expression (`the content of the cell MUST BE the exact FEEL value or FEEL unary test expected, as the value is placed in the generated DMN model as-is`)

**Comment by baldimir** [comment]
I am sorry, there is no time to implement this and this issue is open for a long time, so closing this. After investigation, the joining of columns with the same input when generating the information requirement may get too complex for this experimental tool.
