### ISSUE TITLE
[Release Automation] Adapt Drools/Optaplanner/Kogito setup-branch Jenkins jobs to use major.minor.999 snapshot versions

### ISSUE THREAD

**Issue by rodrigonull** [apache/incubator-kie-issues#1237]
Adjust snapshot handling in branches to start using `major.minor.999-SNAPSHOT` versions.

**Comment by jstastny-cz** [comment]
Keeping this open until we branch successfully.

**Comment by tiagobento** [comment]
This ensemble didn't include `kogito-images`, but we need to make sure that `kogito-images` also points to major.minor.999-SNAPSHOT, while publishing images under the `10.0.x` tag.

**Comment by jstastny-cz** [comment]
@tiagobento my ensemble dealt with updating project.version when preparing release branch, which is for kogito-images done via https://github.com/apache/incubator-kie-kogito-pipelines/pull/1201/files#diff-062224991ead10a9befd76b9e49500be602c0a818ee7d2fbc2e0b02d964656eeR175

**Comment by tiagobento** [comment]
@jstastny-cz Thank you! I didn't see a PR to the `kogito-images` repo and thought it wasn't done.. Sorry about that.

**Comment by tiagobento** [comment]
All work is done, just missing manual testing by @jstastny-cz
