### ISSUE TITLE
[Release Automation] Adapt KIE Tools release jobs to sign and upload release candidate artifacts to https://dist.apache.org/repos/dist/dev/incubator/kie

### ISSUE THREAD

**Issue by rodrigonull** [apache/incubator-kie-issues#1245]
As part of the release automation process for Apache KIE 10 release we need to adapt the existing release jobs to sign the artifacts and upload them to https://dist.apache.org/repos/dist/dev/incubator/kie/10.0.0.

**Comment by tiagobento** [comment]
Also do the signing here:
- https://github.com/apache/incubator-kie-tools/blob/main/.github/workflows/release_publish_extended_services.yml

**Comment by tiagobento** [comment]
- incubator-kie-10.0.0-sandbox-helm-chart.zip
- incubator-kie-10.0.0-cors-proxy-image.tar.gz
- incubator-kie-10.0.0-dashbuilder-viewer-image.tar.gz
- incubator-kie-10.0.0-sandbox-webapp-image.tar.gz
- incubator-kie-10.0.0-sandbox-extended-services-image.tar.gz
- incubator-kie-10.0.0-sandbox-dev-deployment-base-image.tar.gz
- incubator-kie-10.0.0-sandbox-dev-deployment-dmn-form-webapp-image.tar.gz
- incubator-kie-10.0.0-sandbox-dev-deployment-quarkus-blank-app-image.tar.gz
- incubator-kie-10.0.0-serverless-logic-web-tools-base-builder-image.tar.gz
- incubator-kie-10.0.0-serverless-logic-web-tools-swf-builder-image.tar.gz
- incubator-kie-10.0.0-serverless-logic-web-tools-swf-dev-mode-image.tar.gz
- incubator-kie-10.0.0-kogito-management-console-image.tar.gz
- incubator-kie-10.0.0-kogito-task-console-image.tar.gz
- incubator-kie-10.0.0-sonataflow-builder-image.tar.gz
- incubator-kie-10.0.0-sonataflow-devmode-image.tar.gz
- incubator-kie-10.0.0-sonataflow-operator-image.tar.gz
- incubator-kie-10.0.0-tools-npm-packages.zip
- incubator-kie-10.0.0-sandbox-extended-services-macOS-arm64.zip
- incubator-kie-10.0.0-sandbox-extended-services-macOS-x86.zip
- incubator-kie-10.0.0-sandbox-extended-services-windows-x86.zip
- incubator-kie-10.0.0-sandbox-extended-services-linux-x86.zip
- incubator-kie-10.0.0-sandbox-webapp.zip
- incubator-kie-10.0.0-business-automation-standalone-editors.zip
- incubator-kie-10.0.0-sonataflow-standalone-editors.zip
- incubator-kie-10.0.0-business-automation-chrome-extension-editors.zip
- incubator-kie-10.0.0-sonataflow-chrome-extension-editors.zip
- incubator-kie-10.0.0-bpmn-vscode-extension.vsix
- incubator-kie-10.0.0-dmn-vscode-extension.vsix
- incubator-kie-10.0.0-pmml-vscode-extension.vsix
- incubator-kie-10.0.0-dashbuilder-vscode-extension.vsix
- incubator-kie-10.0.0-sonataflow-vscode-extension.vsix
- incubator-kie-10.0.0-yard-vscode-extension.vsix
- incubator-kie-10.0.0-kogito-bundle-vscode-extension.vsix
- incubator-kie-10.0.0-business-automation-bundle-vscode-extension.vsix
- incubator-kie-10.0.0-business-automation-chrome-extension.zip
- incubator-kie-10.0.0-sonataflow-chrome-extension.zip
- incubator-kie-10.0.0-sonataflow-knative-plugin-macOS-arm64.zip
- incubator-kie-10.0.0-sonataflow-knative-plugin-macOS-x86.zip
- incubator-kie-10.0.0-sonataflow-knative-plugin-windows-x86.zip
- incubator-kie-10.0.0-sonataflow-knative-plugin-linux-x86.zip
- incubator-kie-10.0.0-sonataflow-operator.zip

**Comment by tiagobento** [comment]
As we discussed we need to fix the NPM packages job.

E.g., 

```
PNPM_FILTER_STRING_FOR_PUBLISHING=\$(pnpm -r exec 'bash' '-c' 'PKG_NAME=\$(jq -r ".name" package.json) PKG_IS_PVT=\$(jq -r ".private" package.json); if [[ "\$PKG_IS_PVT" != "true" ]]; then echo "-F \$PKG_NAME"; fi')
echo \$PNPM_FILTER_STRING_FOR_PUBLISHING
pnpm \$PNPM_FILTER_STRING_FOR_PUBLISHING exec 'bash' '-c' 'pnpm pack --pack-destination $RELEASE_TAR_DIR'
```
