### ISSUE TITLE
[Release Automation] Create `.tar.gz` files for all images from kogito-images repository an dupload them to https://dist.apache.org/repos/dist/dev/incubator/kie

### ISSUE THREAD

**Issue by porcelli** [apache/incubator-kie-issues#1250]
- incubator-kie-10.0.0-kogito-base-builder-image.tar.gz
- incubator-kie-10.0.0-kogito-data-index-ephemeral-image.tar.gz
- incubator-kie-10.0.0-kogito-data-index-postgresql-image.tar.gz
- incubator-kie-10.0.0-kogito-jit-runner-image.tar.gz
- incubator-kie-10.0.0-kogito-jobs-service-allinone-image.tar.gz
- incubator-kie-10.0.0-kogito-jobs-service-ephemeral-image.tar.gz
- incubator-kie-10.0.0-kogito-jobs-service-postgresql-image.tar.gz

**Comment by tiagobento** [comment]
Also make sure nothing is being published anywhere other than dist.apache.org.

**Comment by jstastny-cz** [comment]
@rodrigonull I can take this one - I have actually done the gpg sign part already and svn part I wanted sync with you about.

**Comment by jstastny-cz** [comment]
Raised following PRs:
* https://github.com/apache/incubator-kie-kogito-pipelines/pull/1206
* https://github.com/apache/incubator-kie-kogito-images/pull/1770
