### ISSUE TITLE
[Release Automation] Provide a script that is able to change the tag of the images AND the java library versions (using different parameters) in Kogito Images repository

### ISSUE THREAD

**Issue by porcelli** [apache/incubator-kie-issues#1251]

**Comment by tiagobento** [comment]
Jan will raise a PR removing the suffixes of dates for image tags of `kogito-images` nightly jobs.

**Comment by jstastny-cz** [comment]
I think this should do:
* https://github.com/apache/incubator-kie-kogito-pipelines/pull/1206

Removing `-nightly` suffix from image name and also `yyyymmdd` suffix from tag (keeping only branch in place).
