### ISSUE TITLE
[Release Automation] Make sure jitexecutor-native publishing signs the JARs

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#1258]

**Comment by tiagobento** [comment]
https://github.com/apache/incubator-kie-kogito-apps/blob/main/.github/workflows/publish-jitexecutor-native.yml

**Comment by tiagobento** [comment]
I'm not sure we have the Maven credentials setup as a secret for `kogito-apps` repo... Don't remember if we actually talked about this.. cc @rodrigonull @baldimir @jstastny-cz

**Comment by jstastny-cz** [comment]
It's only valid for snapshots uploads now, given you mean GHA env.
