### ISSUE TITLE
Remove references to the `openaApiPath` in the Quarkus Dev UI extensions in `kie-tools`

### ISSUE THREAD

**Issue by pefernan** [apache/incubator-kie-issues#1275]
Both `jbpm-quarkus-devui` & `sonataflow-quarkus-devui` are using the Kogito application `openapi.json` in order to read the Process/Workflows definitions. Due to this, they require a specific `openapiPath` to help building the URL to the `openapi.json`

Recently both devui's started using a `GraphQL` query to read the definitions & endpoints list this configuration is no longer needed and should be removed.

**Comment by thiagoelg** [comment]
Reopening as https://github.com/apache/incubator-kie-tools/pull/2536 only tackles JBPM DevUI

**Comment by fantonangeli** [comment]
@pefernan @thiagoelg  I think this issue can be closed as it has been done in these PRs:
- https://github.com/apache/incubator-kie-tools/pull/2302
- https://github.com/apache/incubator-kie-tools/pull/2537

I just double-checked now and the `openapi.json` is only consumed for the json schema to generate the form.

**Comment by pefernan** [comment]
@fantonangeli yea, that task was more to do a cleanup on the Dev-UI apis because they were still referencing to the openapi path, but now I see they have been removed so I'm ok to close.
