### ISSUE TITLE
Reuse components and retrieve workflow definitions from data index instead of openapi.json in sonataflow-deployment-webapp

### ISSUE THREAD

**Issue by paulovmr** [apache/incubator-kie-issues#1276]

**Comment by kumaradityaraj** [comment]
@fantonangeli pleasen assign me this issue.

**Comment by tiagobento** [comment]
Is this somehow related to 

- https://github.com/apache/incubator-kie-issues/issues/1275

?

**Comment by fantonangeli** [comment]
@tiagobento it's also related to that, but it's the continuous of this 
- https://github.com/apache/incubator-kie-tools/pull/2302

As described here: https://github.com/apache/incubator-kie-tools/pull/2302#issuecomment-2135417701
