### ISSUE TITLE
The Timeline goes to the bottom with long endpoints in WorkflowInstance page

### ISSUE THREAD

**Issue by fantonangeli** [apache/incubator-kie-issues#1281]
Opening a Workflow Instance from https://start.kubesmarts.org/dev/#/runtime-tools/workflow-instances
Changing the endpoint to: 
`https://lorem.ipsum.dolor.sit.amet.lorem.ipsum.dolor.sit.amet.lorem.ipsum.dolor.sit.amet.lorem.ipsum:8080`
The Timeline card goes to the bottom of the page

Expected result: the timeline is on the right of the diagram

![image](https://github.com/apache/incubator-kie-issues/assets/17780574/dbdc16b7-13ab-4bcd-b12a-ae7a3d88009a)

**Comment by danielamorais** [comment]
I'll work on this

**Comment by fantonangeli** [comment]
Hi @danielamorais, is it ok for you if I reassign this task?

**Comment by kumaradityaraj** [comment]
@fantonangeli Please assign me this issue. Thank you.
