### ISSUE TITLE
Remove unnecessary base image from quarkus examples (quay.io/kiegroup/kogito-runtime-jvm:latest)

### ISSUE THREAD

**Issue by porcelli** [apache/incubator-kie-issues#1285]
quay.io/kiegroup/kogito-runtime-jvm:latest

**Comment by tiagobento** [comment]
This image is also referenced in two places of `kie-tools`:
1. https://github.com/apache/incubator-kie-tools/blob/main/packages/sonataflow-operator/bddframework/pkg/framework/util.go#L54
2. https://github.com/apache/incubator-kie-tools/blob/main/examples/sonataflow-greeting-quarkus-example/src/main/resources/application.properties#L31

**Comment by porcelli** [comment]
@nmirasch could you please update the references from kie-tools repository?

**Comment by nmirasch** [comment]
@porcelli  I think, the point 2 from @tiagobento 's  comment related with the container image generation could be the easy one, but the change related with the sonataflow-operator (point1) should be tracked and tried by someone closer with the sonataflow operator knowledge. Maybe the way is to keep this PR at the kie-kogito-examples and close this issue and create another one for the kie-tools repository or just reassign this issue. Feel free to decide whatever makes more sense to you.

**Comment by tiagobento** [comment]
I'm ok with using the same issue. cc @wmedvede @ricardozanini @treblereel ^
