### ISSUE TITLE
chrome-extension: "Open in KIE Sandbox" button doesn't work in a private repository

### ISSUE THREAD

**Issue by ljmotta** [apache/incubator-kie-issues#129]
After configuring the token in the KIE Sandbox and clicking in the button, the following error appears:
![cant import](https://user-images.githubusercontent.com/24302289/222570831-d02f424a-06fc-45a4-a2f5-1c7d8bfa9740.png)

Even though the possibility to import the repository using the import URL is working:
![url import is working](https://user-images.githubusercontent.com/24302289/222570949-7a476fd5-9f2e-4ee2-82b3-0417782fd554.png)

## Backend part
Was addressed by https://github.com/apache/incubator-kie-tools/pull/2087

## Frontend part analysis
We have this kind of views of github repositories

### Project root
- Github url: https://github.com/apache/incubator-kie-kogito-examples 🔴 
- Sandbox import url: https://localhost:9001/#/import?url=https://github.com/apache/incubator-kie-kogito-examples 🟢 

For this view we miss the button in UI, but the backend is able to import using this kind of URL.

### Project folder
- Github url: https://github.com/apache/incubator-kie-kogito-examples/tree/stable/kogito-quarkus-examples/dmn-quarkus-example 🟠  
- Sandbox import url: https://localhost:9001/#/import?url=https://github.com/apache/incubator-kie-kogito-examples/tree/stable/kogito-quarkus-examples/dmn-quarkus-example 🔴  

There is bug in UI that the button is not showed for the folder view if it is opened for the first time, for second opening the button is present. For the backend importing this URL is not supported at all. User receives an error about unsupported URL type.

### Project file
- Github url: https://github.com/apache/incubator-kie-kogito-examples/blob/stable/kogito-quarkus-examples/dmn-drools-quarkus-metrics/src/main/resources/org/kie/kogito/examples/LoanEligibility.dmn 🔴 
- Sandbox import url: https://localhost:9001/#/import?url=https://github.com/apache/incubator-kie-kogito-examples/blob/stable/kogito-quarkus-examples/dmn-drools-quarkus-metrics/src/main/resources/org/kie/kogito/examples/LoanEligibility.dmn 🟢 

When single file is opened, we do not have there 'Open in KIE Sandbox' button.

**Comment by tiagobento** [comment]
We should be "inferring" the authSession from the repo URL. If you're already logged in on KIE Sandbox, we should be able to open the repo normally.. Also, it would be nice to allow users to authenticate in case they're not logged in yet.

**Comment by tiagobento** [comment]
@ljmotta found a bug that prevented people from cloning a different tag after this issue was solved in https://github.com/kiegroup/kie-tools/pull/1665. I reopened the issue so we can revisit this and provide a fix for it that doesn't introduce any regressions.

**Comment by yesamer** [comment]
The bug

 is still present in 0.31.0.

In addition, the "Open in KIE Sandbox" doesn't appear in the project root

https://github.com/kiegroup/kie-issues/assets/16005046/b1b4e814-2975-4200-8d0a-fc0fb238c289

**Comment by ljmotta** [comment]
I gues, the correct approach would be to show the button in the project root and not in the project explorer. The error message shows that it tried to import the /src folder.

**Comment by jomarko** [comment]
Hello everyone, as part of 'Continuous improvements for upstream features/tools/components' effort we are again looking into this issue. Could you please help me in understanding where the button should appear?

### 'Pull Request view'
I see we display the button for this view correctly
![image](https://github.com/apache/incubator-kie-issues/assets/8044780/6fbf7695-af0d-4100-9288-8865d995fbe5)


However not sure if #129 is about showing the button in:

### 01 'Project view'
If this view, what place please? (orange, green, any other place)
![image](https://github.com/apache/incubator-kie-issues/assets/8044780/00bd18a5-e9b6-49cd-91ec-a28fb686190a)

### 02 'Asset view'
If this view, what place please? (orange, green, any other place)
![image](https://github.com/apache/incubator-kie-issues/assets/8044780/c28a1ad4-b52e-418c-9a83-d627ad0dddf6)

**Comment by kbowers-ibm** [comment]
I was always a bit confused why it showed in some views but not others. In my opinion it makes sense to have it in both the Project View and Asset view and I think it would look best at Green in the Project view, and Orange in the Asset view. 
However In terms of upkeep it probably makes the most sense to always have it next to the kie logo (orange in the project view), so we don't lose the button every time GitHub changes something in the project/asset view.

**Comment by ljmotta** [comment]
I guess we should do the `green` in the Project view, and `orange` in the Asset view. The `Open in KIE Sandbox` button makes part of the "file" options, so I don't think it would be good to keep it next to the kie logo.
