### ISSUE TITLE
It's not possibile to sum or subtract a time in `10:30:00@Europe/Rome` format

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#1323]
Requires #69 

In a sum / substract operation, if one of the addends has this format `10:30:00@Europe/Rome` an Error is thrown. 

Examples:
`@"PT1H" + @"10:15:00@Australia/Melbourne"`
`@"-P1D" + @"10:15:00@Australia/Melbourne"`
`@"P1D" + @"10:15:00@Australia/Melbourne"`

The error's root cause is that Time format is converted to a `java.time.format.Parsed` Java Object.

<img width="426" alt="Screenshot 2024-06-17 at 09 27 11" src="https://github.com/apache/incubator-kie-issues/assets/16005046/0807053e-7098-4af3-8981-e216c09f1944">

- `java.time.format.Parsed` is not a public class, so it's not possible to directly manage it;
- For the above reason, `java.time.format.Parsed` objects are not managed in the `AddExecutor` and the `SubExecutor`
- `java.time.format.Parsed` implements `java.time.temporal.TemporalAccessor`

**Comment by yesamer** [comment]
Duplicate of #69

**Comment by jomarko** [comment]
@yesamer hi, just double-checking, am I correct this has no impact for the tooling UI?

**Comment by yesamer** [comment]
I confirm there's no impact on tooling @jomarko

**Comment by yesamer** [comment]
Fixed with #69
