### ISSUE TITLE
In functions with a `scale` parameter, that must be in the range [−6111..6176]

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#1325]
The `scale` parameter of the following operations:

- `ceiling(n, scale)`
- `decimal(n, scale)`
- `floor(n, scale)`
- `round up(n, scale)`
- `round down(n, scale)`
- `round half up(n, scale)`
- `round half down(n, scale)`

must be in the range [−6111..6176] 

As stated in the Specs: 10.3.4.5

**Comment by jomarko** [comment]
### 01
Are `ceiling` and `floor` also affected?

### 02
UI updates here. https://github.com/apache/incubator-kie-tools/pull/2431

**Comment by yesamer** [comment]
@jomarko Good point! 
**decimal** is using it too.

**Comment by jomarko** [comment]
@yesamer ok, thank you, so to recap, UI changes are sent in two PRs:
- https://github.com/apache/incubator-kie-tools/pull/2431
- https://github.com/apache/incubator-kie-tools/pull/2434
