### ISSUE TITLE
`Filter`, `Some` and `Every` expression should fail when the matching function doesn't return a Boolean

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#1326]
Closes https://github.com/apache/incubator-kie-issues/issues/1326

- FilterExpression: The `filter expression` MUST resolve to a Boolean
- FilterExpression: Removed a logic that, when in the `filter expression` and on the first evaluation a number is returned, we are using an index instead of a boolean filter.
That is because in contrast with the previous point AND not described in the specs
- EveryExpression: The `matching expression` MUST resolve to a Boolean
- SomeExpression: The `matching expression` part MUST resolve to a Boolean

**Comment by jomarko** [comment]
The tooling side is probably fine, we offer such 'string join' variant in monaco autocompletions.
