### ISSUE TITLE
kn workflow should verify if the cluster has SonataFlow Operator installed

### ISSUE THREAD

**Issue by treblereel** [apache/incubator-kie-issues#1337]
If you try to run kn workflow deploy in a cluster without Knative installed, the user might face a weird message from the Kube API complaining about the lack of the KService CRD.

It would be nice if this command checks for a Knative installation before attempting to deploy the application.

jira: https://issues.redhat.com/browse/KOGITO-7665

**Comment by ricardozanini** [comment]
Now I see that this imported issue might be confusing. It should be:

> If you try to run kn workflow deploy in a cluster without SonataFlow installed, the user might face a weird message from the Kube API complaining about the lack of the CRDs. It would be nice if this command checks for a SonataFlow installation before attempting to deploy the application.

Also, can you try your PR in an actual cluster without the operator installed so we can get the real message and document in this issue?
