### ISSUE TITLE
Background Table: Properties under assigned instances are inconsistently named 

### ISSUE THREAD

**Issue by kbowers-ibm** [apache/incubator-kie-issues#1343]
When assigning an Instance, it changes the name of its associated property to Expression </>, however any additional properties created under the assigned instance are called property by default. Just wondering whether this is intended, because when changed it will cause some tests to fail. 

https://github.com/apache/incubator-kie-issues/assets/92726146/447b65d2-0bcb-47dd-93b7-1a3bb04f5c62

**Comment by yesamer** [comment]
@kbowers-ibm That is the intended behavior, any new column added will behave in that way.
