### ISSUE TITLE
DMN Form Page not displaying Forms for complex DMN in DMN Dev Deployments

### ISSUE THREAD

**Issue by pefernan** [apache/incubator-kie-issues#135]
The DMN Form page cannot correctly display a Form for complex DMN, for example the [loan sample](https://gist.github.com/pefernan/19bb16be950b1fb4f11f04b12a3c9502) shipped in the `Kie Sandbox`.

After deploying the DMN we can access the DMN Form and the page keeps loading indefinitely until the `Exit page | wait` Dialog appear. 

![Image](https://user-images.githubusercontent.com/2429832/222789305-a6eb61f0-74f8-430e-8b77-0c67f6ce208c.png)

No logs appear in the browser console, but the Pod's log appear to be trapped in a loop.

![Image](https://user-images.githubusercontent.com/2429832/222790230-a5a6cfdf-37af-4cdf-bbe9-fd584aab367f.png)

**Comment by jomarko** [comment]
@pefernan for anyone interested in fixing this issue. Could you please share steps, how to obtain url of deployed DMN form?

**Comment by pefernan** [comment]
@jomarko @tiagobento I think this could be closed, just checked it and seems to be fixed.

![image](https://user-images.githubusercontent.com/2429832/226320979-5b2b4ef4-a97d-4697-8df1-883307e25887.png)
