### ISSUE TITLE
DMN Elements with null IDs are not correctly managed 

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#1356]
DMN spec states that the `ID` attribute of any `DMNElements` is Optional

<img width="859" alt="Screenshot 2024-06-25 at 10 16 29" src="https://github.com/apache/incubator-kie-issues/assets/16005046/a5759aad-2dd6-491b-bf5a-757426d53897">

This is currently not correctly managed in our code base.

The DMNElements are managed in the `DMNModelImpl` in `Maps`

<img width="784" alt="Screenshot 2024-06-25 at 10 19 53" src="https://github.com/apache/incubator-kie-issues/assets/16005046/84d79f2f-2a29-47bd-8812-13b13240a5ea">

Those maps are managed with ID as key.
In case of multiple DMNElements of the same kind (eg. Decision Nodes) with no ID, all those nodes will be added in that Map with `null` key, resulting in a collision.

We should manage this case using a new key (namespace + name), but I guess we should keep the search by `ID` in place, to preserve the API backword-compatibility

**Comment by tiagobento** [comment]
We had the same problem in the new DMN Editor, and our solution was to have a normalizarion process that will make sure there are IDs for each element that can have one.

**Comment by yesamer** [comment]
@tiagobento Thank you for sharing your experience, my concern is that the backend currently has a `getDecisionByID()` public method, so changing the ID could break the backword compatibility

**Comment by tiagobento** [comment]
@yesamer Adding the ID doesn't have to be done to the same model that is exposed back to users. The normalization process can be implemented only for indexing and internal manipulation. This wouldn't break the behavior of `getDecisionByID()` and would allow you to avoid collisions for un-ID'd elements.

**Comment by yesamer** [comment]
Yep, that was my same idea :)
