### ISSUE TITLE
Error during the KN CLI plugin build

### ISSUE THREAD

**Issue by treblereel** [apache/incubator-kie-issues#1361]
1. Clone kie-tools repo https://github.com/kiegroup/kie-tools
2. Clone 9.100.x branch
3. pnpm bootstrap
4. pnpm -r -F @kie-tools/kn-plugin-workflow... build:dev
5. Current result: Build fails
6. Expected result build pass.
7. cd packages/sonataflow-quarkus-devui/
8. pnpm build:dev

{noformat}
[INFO] Reactor Summary for KIE Tools :: SonataFlow Quarkus Dev UI Extension 999-SNAPSHOT:
[INFO] 
[INFO] KIE Tools :: SonataFlow Quarkus Dev UI Extension ... FAILURE [  0.474 s]
[INFO] KIE Tools :: SonataFlow Quarkus Dev UI Extension :: Runtime SKIPPED
[INFO] KIE Tools :: SonataFlow Quarkus Dev UI Extension :: Deployment SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.596 s
[INFO] Finished at: 2024-06-14T08:15:35+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.15.0:pnpm (pnpm build:prod) on project sonataflow-quarkus-devui-parent: Failed to run task: 'pnpm -F serverless-workflow-dev-ui-webapp... -F !@kie-tools/dmn-marshaller-backend-compatibility-tester -F !@kie-tools/dmn-testing-models build:prod' failed. java.io.IOException: Cannot run program "/home/tdavid/Projects/eng/kie-tools/node/node" (in directory "/home/tdavid/Projects/eng/kie-tools"): error=2, No such file or directory -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
 ELIFECYCLE  Command failed with exit code 1.

{noformat}

**Comment by tiagobento** [comment]
This issue doesn't seem to be in the correct place. `kiegroup/*` and `apache/incubator-kie-*` are two separate code bases. If this bug is present on a `github.com/kiegroup/*` repository, please track it somewhere else.
