### ISSUE TITLE
Revisit all React-dependent packages on `kie-tools` declaring `react` as a `dependency` instead of a `peerDependency`

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#1365]
React libraries shouldn't force a specific version of React, but rather declare its compatibility with a React version. This is most likely causing problems for people depending on React libraries/components published by `kie-tools`.

We need to check if Syncpack works for peerDependencies too, as we need alignment between all packages.

**Comment by mareklibra** [comment]
This issue is becoming more urgent, since the "forced" version is React 17 and the React 19 is knocking on our door already. Thank you for looking into it.

There can be a workaround in using "resolutions" in the package.json, but this is nasty.

**Comment by lordrip** [comment]
Yes @mareklibra, we're using resolutions in the Kaoto to do exactly this :)
