### ISSUE TITLE
The width information are not being deleted from DMN when the expression is deleted in the new Boxed Expression Editor

### ISSUE THREAD

**Issue by danielzhe** [apache/incubator-kie-issues#1376]
In the new BEE, when the user deletes an expression the expression widths are not deleted from the model. Those widths should be removed.

See the video on how to reproduce. Notice in that case I already had a previous expression (not shown in the video), so at the end, we have 3 ComponentWidths nodes in the DMN file, while we should have only 1.

https://github.com/apache/incubator-kie-issues/assets/7305741/a12ad2c1-cfa6-4af4-9267-dec9579ba44a

**Comment by jomarko** [comment]
This may be related to #1374, I mean maybe the same area of codebase is needed to touch to provide the fix.
