### ISSUE TITLE
Create new feature on KIE Sandbox to allow the enabling/disabling of the PMML editors as a supported graphical editor

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#138]
Some distributions of KIE Sandbox might not be interested in allowing users to manually tweak PMML files on KIE Sandbox. We need a new environment variable to enable/disable the PMML Editor on KIE Sandbox. This env var must be usable on builds directly, or on `kie-sandbox-image`.

**Comment by jomarko** [comment]
@tiagobento @kbowers-ibm I believe part of this task should be also documentation of this variable. I mean:
- are similar variables, list of them available directly in UI or workbench? can user dynamically turn off/on editor in online-editor? similar feature was in old RHPAM workbench.
- are similar variables documented in kie-tools wiki?
- are similar variables documented in .... ?

**Comment by kbowers-ibm** [comment]
This ticket has evolved from a feature flag to enable/disable the PMML editor, to reworking the EditorEnvelopeLocator to allow users to disable/enable any editor as well as disable/enable their own custom editors. The Homepage will be populated dynamically through the EditorEnvelopeLocatorFactory based on the config in the env.json.
