### ISSUE TITLE
Improve pom.xml generated by kn-workflow-plugin

### ISSUE THREAD

**Issue by treblereel** [apache/incubator-kie-issues#1386]
It looks like, while publishing, the kn-workflow-plugin still uses `0.0.0` version of sonataflow-quarkus-devui.

It must be investigated.
Plus, the apache repository must be added to the generated pom.xml

```
<repositories>
    <repository>
        <id>apache-public-repository-group</id>
        <name>Apache Public Repository Group</name>
        <url>https://repository.apache.org/content/groups/public/</url>
    </repository>
</repositories>
```

**Comment by treblereel** [comment]
^^ @wmedvede @dgutierr

**Comment by treblereel** [comment]
@wmedvede hmm, I did
```
pnpm update-version-to 0.0.1
```

and generated pom.xml contains the right version.

```
        <dependency>
            <groupId>org.apache.kie.sonataflow</groupId>
            <artifactId>sonataflow-quarkus-devui</artifactId>
            <version>0.0.1</version>
        </dependency>

```
so it works.

**Comment by treblereel** [comment]
So, everything is great with `kn-workflow-plugin`, but we need to tune it a little:
1) add apache and apache snapshot repository to the generated pom.xml
2) add a param for `org.apache.kie.sonataflow:sonataflow-quarkus-devui` that must be `0.0.0` by default

**Comment by treblereel** [comment]
If anyone sees this message, please assign this issue to me, as I do not have permission to do it by myself

**Comment by wmedvede** [comment]
> If anyone sees this message, please assign this issue to me, as I do not have permission to do it by myself

done
