### ISSUE TITLE
Fix build  kogito-examples.build-and-test in kogito nightly.native folder

### ISSUE THREAD

**Issue by pibizza** [apache/incubator-kie-issues#1401]
The build is consistently failing due to errors while processing the poms: "[ERROR] 'dependencies.dependency.version' for org.kie:kie-addons-quarkus-tracing-decision:jar is missing. @ line 65, column 17"

https://ci-builds.apache.org/job/KIE/job/kogito/job/10.0.x/job/nightly.native/job/kogito-examples.build-and-test/

**Comment by tkobayas** [comment]
The error was fixed by https://github.com/apache/incubator-kie-kogito-examples/pull/1986

But I see another error. Filed a new issue: https://github.com/apache/incubator-kie-issues/issues/1441
