### ISSUE TITLE
New DMN Editor: Support `read-only` mode

### ISSUE THREAD

**Issue by thiagoelg** [apache/incubator-kie-issues#1445]
To be able to display DMN models using the new DMN Editor, we need to make it support a `readOnly` flag. Navigation must still be possible (E.g., entering the Boxed Expression Editor for a Decision/BKM) or Data Types and Included models, changing the Zoom level etc also must work fine.

**Comment by jomarko** [comment]
@thiagoelg hi. may I ask about this new flag? Is it only a new property of some react component that will be automatically set accordingly? For example false for regular model, true for external model? Or is this new flag also some new UI component, checkbox/toggle, that user can activate and deactivate the read-only mode with? Thank you.

**Comment by thiagoelg** [comment]
Check out this PR: https://github.com/apache/incubator-kie-tools/pull/2538

It's a new prop for the `DMNEditor` component, so whoever uses it (including the standalone editor) can use the editor to display DMNs.
