### ISSUE TITLE
`matches()` function wrongly behaves

### ISSUE THREAD

**Issue by gitgabrio** [apache/incubator-kie-issues#1448]
According to the DMN specs, the `matches()` and `replace()` functions should behave according to the xQuery 1.0 specification. 
Our current implementation doesn't rely on that, using the native Java implementation to manage both.
Unfortunately, the Java regex management differs from the xQuery specs, and natively implementing the xQuery specs leads to huge effort (and complex) work. For that reason, we agreed to rely on an external library that already implemented xQuery specs in Java. 
After a quick analysis (https://en.wikipedia.org/wiki/XQuery#Implementations), we choose [Saxon-He](https://github.com/Saxonica/Saxon-HE) as the best fit for this purpose. 

The scope of the ticket is to integrate this new external dependency into our code base, so both `matches()` and `replace()` can rely on that implementation to correctly behave.

=== _Original description_  ====

TCK Tests revealed some cases where matches() wrongly behaves.

1.     matches("O", "[A-Z-[OI]]", "i") should return false. Before fixing that, double-check in the specs that this is the expected behavior
2.     matches("i", "[A-Z-[OI]]", "i") should return false. Before fixing that, double-check in the specs that this is the expected behavior
 
 
This syntax is invalid for java Pattern
`[A-Z-[OI]]`
and correct one is
`[A-Z&&[^OI]]` (see **_Character classes_** in [docs](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html))

[XML Schema Part 2: Datatypes Second Edition](https://www.w3.org/TR/xmlschema-2/)
makes a distinction between _negation_ (`ˆ`) and _subtraction_ (`-`)
See "Negative Character Group" and "Character Class Subtraction" at [regex chapter](https://www.w3.org/TR/xmlschema-2/#regexs).

_**A negative character group is a [·positive character group·](https://www.w3.org/TR/xmlschema-2/#dt-poschargroup) preceded by the ^ character. For all [·positive character group·](https://www.w3.org/TR/xmlschema-2/#dt-poschargroup)s P, ^P is a valid negative character group, and C(^P) contains all XML characters that are not in C(P).**_

_**A character class subtraction is a [·character class expression·](https://www.w3.org/TR/xmlschema-2/#dt-charexpr) subtracted from a [·positive character group·](https://www.w3.org/TR/xmlschema-2/#dt-poschargroup) or [·negative character group·](https://www.w3.org/TR/xmlschema-2/#dt-negchargroup), using the - character.**_

A "translation" between the different syntax is required

**Comment by jomarko** [comment]
Thank you for reporting. Will we add such example into https://kiegroup.github.io/dmn-feel-handbook/#matches-input-pattern-flags @gitgabrio ?

**Comment by gitgabrio** [comment]
> Thank you for reporting. Will we add such example into https://kiegroup.github.io/dmn-feel-handbook/#matches-input-pattern-flags @gitgabrio ?

@jomarko TBH I do not know. As far as I can see, that page is used only to show the _syntax_ of the different functions. Inside TCK (and also in our unit tests) there are lot of different examples/cases, and I'm not sure the dmn-feel-handbook is meant for that.
@baldimir @yesamer wdyt ?

**Comment by yesamer** [comment]
@gitgabrio  I agree.
