### ISSUE TITLE
Upgrade Quarkus to version 3.8.6

### ISSUE THREAD

**Issue by baldimir** [apache/incubator-kie-issues#1465]
There is a new LTE version of Quarkus available. We need to upgrade to this version.

**Comment by rgdoliveira** [comment]
@baldimir I think Quarkus 3.8.4 is also defined in kie-tools repository, don't we need to update it there too?

**Comment by baldimir** [comment]
@rgdoliveira I am sorry, I forgot to upgrade this ticket. Yes, kie-tools will be upgraded too. However for that, it needs to have a new weekly snapshot of the "backend" libraries. There is work on that currently. When that is ready, we can upgrade kie-tools too.

**Comment by rgdoliveira** [comment]
@baldimir another question, what about kogito-serverless-operator repository?

IIUC, the operator is getting built from kie-tools repository but the main source code of it is still https://github.com/apache/incubator-kie-kogito-serverless-operator, isn't it? shouldn't it also be upgraded?

**Comment by rgdoliveira** [comment]
@baldimir I've created https://github.com/apache/incubator-kie-kogito-serverless-operator/pull/527 as I believe it is needed too, please let me know in case it is not.

**Comment by baldimir** [comment]
@rgdoliveira Thanks. Sorry, I missed the repo. 

Closing this as done as all repos are merged.
