### ISSUE TITLE
BAMOE Canvas installtion fails for 9.1 due to extended service pod crashloopbackoff.

### ISSUE THREAD

**Issue by skaraleDMS** [apache/incubator-kie-issues#1494]
Hi,
We attempted installation of BAMOE 9.1 on EKS (v1.28.12-eks-a18cd3a ). We followed IBM's document. Please find link for the document as follows.
[](https://www.ibm.com/docs/en/ibamoe/9.1.x?topic=installing-canvas)

Issue :
After running 
` helm install my-bamoe-canvas ./canvas-helm-chart --values ./canvas-helm-chart/values-kubernetes.yaml --set global.kubernetesClusterDomain="<YOUR_KUBERNETES_CLUSTER_DOMAIN>" --set global.kubernetesIngressClass="<YOUR_KUBERNETES_INGRESS_CLASS>"`
with updated values from terminal extended-service pods keep failing with error log saying expected integer value.

What is Fix ?

To fix above issue we need pass  this environment variable to extended service deployment  Key: "EXTENDED_SERVICES_PORT" Value: 21345 Then pods become up and running. 

OR

Upgrade Kubernetes to v1.30.3+ 

Please find GIF with action attached with Issue and Fix.
![bamoe-9-rule](https://github.com/user-attachments/assets/84f2adc1-ce5a-4ecf-82cb-4ef1fc2a2735)

Thanks & Regards,
Sachin Karale,
Cloud Solutions Architect,
Decision Management Solutions

**Comment by tiagobento** [comment]
Hi @skaraleDMS. This repository tracks issues for Apache KIE, not IBM BAMOE. Please refer to https://github.com/IBM/bamoe/issues.
