### ISSUE TITLE
Make browser extensions work on other GitHub instances, like github.ibm.com

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#151]
Our browser extensions currently have a fixed domain on their manifests, which makes it only work for github.com and its subdomains.

When accessing other GitHub instances, like github.ibm.com, we should provide a way to run our browser extensions and inject our custom Editors there.

**Comment by jomarko** [comment]
The manifest files we have, contain similar snippets:
```
  "content_scripts": [
    {
      "run_at": "document_idle",
      "js": ["content_scripts/github.js"],
      "matches": ["https://*.github.com/*"],
      "all_frames": true
    }
  ],
```

please notice especially `matches`. Its capabilities are documented [here](https://developer.chrome.com/docs/extensions/develop/concepts/match-patterns).

what is kind of problematic, because if I undestand documentation properly, we can not put there  'regex' like `"https://*.github.*.com/*"` to match for example `https://github.ibm.com`

So options I see are:

### List of github instances as precondition
If the list of supported github instances would be somehow hardcoded (be subjuct of some agreement), then we could have something like:
```
  "content_scripts": [
    {
      "run_at": "document_idle",
      "js": ["content_scripts/github.js"],
      "matches": ["https://*.github.com/*", "https://*.github.company.one.com/*", "https://*.github.company.two.com/*"],
      "all_frames": true
    }
  ],
```

But I tend to think it is very hardly achievable as we are in the opensource software field, and basically anyone is our user. Am I right?


### Dynamic github instance name
So the manifest would look like:
```
  "content_scripts": [
    {
      "run_at": "document_idle",
      "js": ["content_scripts/github.js"],
      "matches": [$GITHUB_INSTANCE_NAME],
      "all_frames": true
    }
  ],
```

where `$GITHUB_INSTANCE_NAME` is set by user, so during installing chrome-extension into browser, or in some chrome-extension setting panel.

Maybe https://developer.chrome.com/docs/extensions/reference/manifest#register-a-content-script
![Screenshot 2024-01-10 162657](https://github.com/apache/incubator-kie-issues/assets/8044780/6773287f-27b8-4a54-8eee-2e1631703162)


I think setting `$GITHUB_INSTANCE_NAME` during `build:dev/build:prod` phase doesn't solve our problem.

**Comment by tiagobento** [comment]
@jomarko Nice investigation! I never had the time to investigate it as deeply as you have, but from my understanding, there's no way we'll be able to dynamically create a manifest.json or even make it parametrized for users to input a URL of their choice. I found [this entry](https://stackoverflow.com/questions/67498257/chrome-extension-create-manifest-json-dynamically) on StackOverflow... Not much but maybe some other path to investigate...

And you're right about the pre-defined list of URLs.. we can't list them all! :)

With all that said, I'd love to see how React's extension or even ad blockers work, though... I mean, do they run on every page and then dynamically decide wether to execute or not? That can be a viable option too. Note that ad blockers even allow you to dynamically pause them on some pages, so that might be very interesting and aligned with our use-case.

**Comment by thiagoelg** [comment]
It might be cool to look at how [Refined Github](https://github.com/refined-github/refined-github) does this. It's pretty much the same use case, and this is how the UI is like 
<img width="409" alt="image" src="https://github.com/apache/incubator-kie-issues/assets/10515135/0e3bdc5a-566f-41c0-aa41-6da5de376568">

**Comment by jomarko** [comment]
@tiagobento @thiagoelg  thank you both for links, they helped me in browsing more information about possible solution.

### Good news
I was able to achieve 'Open in KIE Sandbox' botton on different github instances, yay!

### Bad news
It has limitations described below

#### Github instance version
Each deployed github instance may be different in version, so it means also the locators of our chrome extension for displaying buttons needs to be different. I was able to find a locator for a github repository home screen, that was same for two different github instances [1], however I was not able to find such a locator for a github asset screen.

We should probably add some description into our chrome extension, what github instance versions are supported. Or limit the scope of our chrome-extension only for github repository home screen that is maybe the most stable part of the UI. I really do not know.

#### Hardcoded 'github.com' in source code
- `KogitoMenu.tsx` - `href="https://github.com/settings/tokens"`
- `OpenInExternalEditorButton.tsx` - `return `https://github.com/${prInfo.org}/${prInfo.repo}/tree/${prInfo.gitRef}`;`

not sure if we can overcome this somehow using chrome API to replace those dinamically, bellow is example how to get URL via chrome API
```
chrome.tabs.query({active: true, lastFocusedWindow: true}, tabs => {
    let url = tabs[0].url;
    // use `url` here inside the callback because it's asynchronous!
});
```

### Solution One
I replaced this manifest configuration:
```
  "content_scripts": [
    {
      "run_at": "document_idle",
      "js": ["content_scripts/github.js"],
      "matches": ["https://*.github.com/*"],
      "all_frames": true
    }
  ],
```

with this code in `background.ts`:
```
chrome.action.onClicked.addListener((tab) => {
  if (!tab.url?.includes('chrome://')) {
    chrome.scripting.executeScript({
      target: { tabId: tab.id ?? 0 },
      files: ["content_scripts/github.js"],
    });
  }
});
```


and added `"activeTab", "scripting"` permissions into manifest

The resulting effect is, that the 'Open in KIE Sandbox' button appears only, once user clicks the extension icon:

![Screenshot 2024-01-11 133654](https://github.com/apache/incubator-kie-issues/assets/8044780/4208db5d-b7e6-4ee1-89bd-fcca3e728834)
![Screenshot 2024-01-11 133722](https://github.com/apache/incubator-kie-issues/assets/8044780/ce28a21a-254e-4e36-85fd-e3db72f7a3e0)

### Solution Two
Was to change manifest content_scripts match section to be 'allow all'
```
  "content_scripts": [
    {
      "run_at": "document_idle",
      "js": ["content_scripts/github.js"],
      "matches": ["https://*/*", "http://*/*"],
      "all_frames": true
    }
  ],
```

What then brings this default setting in chrome extension:
![image](https://github.com/apache/incubator-kie-issues/assets/8044780/68496df1-f444-45c5-bfdd-1451bde491db)

^ what is really not idea, but can be changed to:
![Screenshot 2024-01-11 134905](https://github.com/apache/incubator-kie-issues/assets/8044780/c2df198b-80de-4ca7-b142-e198d8a0982d)

^ what makes user responsible for setting only appropriate github instances there

[1]
From:
```
      return document.querySelector("#repository-details-container .pagehead-actions") as HTMLElement | null;
```

To:
```
      return document.querySelector(".pagehead-actions") as HTMLElement | null;
```

**Comment by tiagobento** [comment]
@jomarko Great findings!

Regarding the version of GitHub we should support, I think we should always try and go for "best effort @ latest". It's unrealistic that we'll be able to maintain retro-compatibility with older GitHub Enterprise Server (GHES) versions, especially because we don't have a way to automatically test it. IMHO, our benchmark should always be github.com. Users will then have the option to try and run the extension at their GHES instances, but it might not work.

Regarding which of the two strategies is better for us, my opinion is that we should go with option 2, as users still have the option to fine-tune their permissions.

One thing we must be careful about, is that if our extension is running in all websites, we should make sure it very quickly detects whether or not the current tab is indeed a GitHub page, so that we don't negatively impact the user's experience on websites other than GitHub tabs.

With respect to the hard-coded `github.com` references, I think it's fair to say we should just change it to `location.origin`.

I'm eager to hear other people's opinions too. Once again, well done @jomarko! Thanks!

**Comment by yesamer** [comment]
@tiagobento @jomarko I agree with the above @tiagobento comment. 
Just one point:
> One thing we must be careful about, is that if our extension is running in all websites, we should make sure it very quickly detects whether or not the current tab is indeed a GitHub page, so that we don't negatively impact the user's experience on websites other than GitHub tabs.

I agree with this point, but how to manage it pragmatically? If the extension detects an older github version, should we disable the whole functionality? Should we show a warning somewhere?

**Comment by kbowers-ibm** [comment]
Thanks for all the investigation Jozef! I agree that the 2nd solution is probably the better way to go, especially with the ability to add restrictions that you mentioned. Curently the [README ](https://github.com/apache/incubator-kie-tools/tree/main/packages/chrome-extension)for the chrome extension just contains a title, so potentially you could add the instructions/images that you wrote above to the README as a quick guide for any user who's worried about an extension running on all sites.

**Comment by jomarko** [comment]
@kbowers-ibm yay, great idea, for sure I can add some content into readme.

@yesamer I believe yes, in pseudocode, somewhere really near after the entry point we should have:
```
if (github UI is supported by chrome-extension) {
  log into chrome-extension logs
  return;
}
```

Now big question is, what is `github UI is supported by chrome-extension`, or better to say, how to detect, github instance is the latest available or not.

I had no luck in searching trough github REST api. To me it seems there is no information about gthub UI instance version. I think there is only information about REST api version, in respense header [1] or [here](https://api.github.com/versions).

I think the only ways is to try some jquuery/css locators , if they exists somehow decide if the extension can be active or not. For example entrprise github instances have some information in the UI [2]. Public github.com instance do not have similar information.

[1]
![Screenshot 2024-01-19 083347](https://github.com/apache/incubator-kie-issues/assets/8044780/6e8724bd-e510-400c-bbb4-4003c1081905)


[2]
![image](https://github.com/apache/incubator-kie-issues/assets/8044780/cacf5923-edcc-4dee-85f0-ac3d7989dcf1)
