### ISSUE TITLE
Drools - Quarkus 3 Migration

### ISSUE THREAD

**Issue by gitgabrio** [apache/incubator-kie-issues#153]
Migrate Drools to Quarkus 3

Related tickets:
- [ ] https://github.com/kiegroup/kie-issues/issues/106
- [ ] https://github.com/kiegroup/kie-issues/issues/136
- [ ] https://github.com/kiegroup/kie-issues/issues/146
- [ ] https://github.com/kiegroup/kie-issues/issues/147
- [ ] https://github.com/kiegroup/kie-issues/issues/148
- [ ] https://github.com/kiegroup/kie-issues/issues/149
- [ ] https://github.com/kiegroup/kie-issues/issues/150
- [ ] https://github.com/kiegroup/kie-issues/issues/152
- [ ] https://github.com/kiegroup/kie-issues/issues/154

**Comment by eduardocerqueira** [comment]
all related issues were closed, should this one be closed too or what is there any remaining work for this card? I could not identify what we are tracking on this card

@gitgabrio
