### ISSUE TITLE
Make sure all `.zip` and `.tar.gz` artifacts contain LICENSE, NOTICE, and DISCLAIMER-WIP files

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#1533]
Context on IPMC vote email: https://lists.apache.org/thread/oz1xfz48jwlw05sdy0wvtnrhn27jc72h

Note that it looks like we don't need to tailor the content of those files specifically to each artifact for the 10.0.0 release.

**Comment by LightGuard** [comment]
I believe this is also able to be closed
