### ISSUE TITLE
Remove Maven and Gradle wrapper from source

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#1534]
Context on IPMC vote email: https://lists.apache.org/thread/oz1xfz48jwlw05sdy0wvtnrhn27jc72h

**Comment by porcelli** [comment]
We have a community member that during community call volunteered to tackle this @mcruzdev

(can't assign to @mcruzdev because assign is limit to committers)

**Comment by mcruzdev** [comment]
# incubator-kie-kogito-runtime
- [ ] incubator-kie-kogito-runtimes/quarkus/integration-tests/integration-tests-quarkus-gradle/integration-tests-quarkus-gradle-project/gradle/wrapper/gradle-wrapper.jar
- [ ] incubator-kie-kogito-runtimes/.mvn/wrapper/maven-wrapper.jar
- [ ] incubator-kie-kogito-runtimes/kogito-codegen-modules/kogito-codegen-core/src/test/resources/empty.jar

### PR
- [ ] https://github.com/apache/incubator-kie-kogito-runtimes/pull/3724

# incubator-kie-tools

- [x]  incubator-kie-tools/packages/stunner-editors/errai-ui/src/test/resources/less.jar 

### PR

- [x] https://github.com/apache/incubator-kie-tools/pull/2664

# incubator-kie-kogito-apps
- [ ] incubator-kie-kogito-apps/.mvn/wrapper/maven-wrapper.jar

### PR
- [ ] https://github.com/apache/incubator-kie-kogito-apps/pull/2115

cc: @porcelli @tiagobento

**Comment by porcelli** [comment]
@mcruzdev not all .jars need to be removed;

Majority seems needed for testing the compiler and other internal pieces of the code that manipulate jars

**Comment by porcelli** [comment]
i'd say that everything in test folders should be kept; and we'll just mention it somewhere - maybe in the notice file
