### ISSUE TITLE
kogito-decisions-spring-boot-starter | Spring 3 support?

### ISSUE THREAD

**Issue by oisco135** [apache/incubator-kie-issues#1558]
Hi Team,

This is just a general question re: Spring 3 support.

I'm trying to upgrade a spring project which uses kogito-decisions-spring-boot-starter to Spring 3.

But it seems the generated code fails compilation due to the fact that it still uses javax.annotation imports.

I've tried updating kogito-decisions-spring-boot-starter to version 1.44.0.Final, but to no avail.

Should this be a bug report or else is spring 3 support a WIP?

Many thanks

**Comment by yesamer** [comment]
Hi @oisco94, the upcoming Apache KIE version 10 will support SpringBoot 3.2.4 (https://github.com/apache/incubator-kie-kogito-runtimes/pull/3463)
