### ISSUE TITLE
Improve README of KIE Sandbox image

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#16]
- Static sandbox assets like logos, images, and style sheets should be documented on the image README. 
- This will enable users to replace parts of it in a derived image with the patches.
- For the CSS stylesheet, it's challenging to make style sheets fully configurable, so this JIRA doesn't intend to allow users to create a full CSS 'theme' and replace the KIE Sandbox one (pattern fly), but we only target small tweaks on CSS. 
- On the image README, it’s expected that we have instructions on how to do this patching process for static assets.
- Better documentation for configuring the image for a custom deployment is also expected.
- Information about Environment Variables and `env.json` is very important.

**Comment by glaty1719** [comment]
Hello!
I am a newbie.Is there anything that I can do?

**Comment by tiagobento** [comment]
Hi @slackuj, please filter the board for issues with the "good first issue" label. They're simple issues that are good fitted for first-time contributors! :)

**Comment by tiagobento** [comment]
Closing as we just did #283
