### ISSUE TITLE
Document the process of locally developing Dev deployments when we make changes to the base images

### ISSUE THREAD

**Issue by thiagoelg** [apache/incubator-kie-issues#160]
Right now Dev Deployments use the `daily-dev` tag from the quay.io repo by default, making impossible to test new changes to the `dmn-dev-deployment-base-image` image without publishing a build somewhere else and altering the env vars.

Think about:
- Build:dev and Build:prod
- Development workflow with
  - Local K8S
  - Remote K8S/OpenShift

Questions:
- How do I test my local changes when developing to a local K8s?
- How do I test my local changes when developing to a remote K8s/OpenShift?
- How do I merge my PR without breaking the `main` branch when I made changes to the base images?

Notes:
Cross-compiling images: E.g., I’m on an Arm-based macOS but want to use my image on OpenShift, which only supports x86. We need to use Buildkit to do that.
Have a script ready on `package.json` to do that. Configuring Buildkit needs to be done prior.

**Comment by rxo09** [comment]
lnbc1400u1pnkatccpp50qv23c8usfz9gu3dne4m5htvn265fdhauemgxc3qgtcne97s272qdxj2pskjepqw3hjqnt9d4cx7mmvypqkxcm9d3jhyct5daezq2z0wfjx2u3qf9zr5grpvd3k2mr9wfshg6t0dckkyv3kx33kzd33xcenwvmz8pjxgvphx5ekydesve3nvc33xvmxzcnrxqenxep3xp3kydrrvf3n2en9xajrxwfnvvuxzetxvsenvwpkvcknzdenx5enqdesxvcn2ve49ycqzpuxqz6gsp5jurwwxr2tdv76g7896nhd9tur7curx4lqq7ts27r80x5yyy4wptq9qxpqysgqpfvhfjj2xwmhklcxpw4xlajes5lw8fpakz452g98k52qwcpcqq2jffd55hnh6fpequ8fujy6aeaq6v80hff9jey5v6y0mnrsk7ah87qqg6fuey of that new id _
