### ISSUE TITLE
Remove binaries from test resources on main

### ISSUE THREAD

**Issue by porcelli** [apache/incubator-kie-issues#1602]
Based on recent comment from @justinmclean [1][2] - we need properly remove binaries (compiled code) from our test resources.

[1] https://lists.apache.org/thread/3176kvtgo0o9cljyzsc3dqj6svrxpd21 
[2] https://lists.apache.org/thread/q6zp3v3lwxslh0mmydyzlb22r5ght2p8

Related issue: https://github.com/apache/incubator-kie-issues/issues/1601

**Comment by porcelli** [comment]
- [x] @thiagoelg https://github.com/apache/incubator-kie-tools/pull/2722
- [x] @gitgabrio https://github.com/apache/incubator-kie-kogito-runtimes/pull/3759
- [x] @mariofusco https://github.com/apache/incubator-kie-drools/pull/6141

**Comment by tiagobento** [comment]
https://github.com/apache/incubator-kie-tools/blob/main/packages/dev-deployment-upload-service/tests/test.zip doesn't contain any compiled code, so I guess we can keep it on `main`. Nothing against removing it on `10.0.x` though, if it helps the release.

**Comment by porcelli** [comment]
@tiagobento we then need to add a NOTICE-BINARY file to justify it, for 10.0.0 better remove all the friction...

**Comment by porcelli** [comment]
@jomarko here

https://github.com/apache/incubator-kie-kogito-runtimes/pull/3760#pullrequestreview-2412311451

**Comment by jomarko** [comment]
Thank you for tracking `integration-tests-quarkus-gradle/pom.xml` comment @porcelli . Feel free to add me as reviewer for #1602 if needed once opened.

**Comment by tkobayas** [comment]
Hi @porcelli , we will rewrite the tests in `main` branch so that we don't need to have binaries in the codebase. But `10.0.x` branch will go with disabling the tests, correct? (= we will not backport the rewrite-fix to `10.0.x`)

**Comment by porcelli** [comment]
thank you @tkobayas - for 10.0.x I already addressed removing and disabling everything. We just need address this on main.

**Comment by tkobayas** [comment]
Done by
https://github.com/apache/incubator-kie-tools/pull/2722
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3759
https://github.com/apache/incubator-kie-drools/pull/6141
