### ISSUE TITLE
Fix Drools Drools Ansible RuleBook Integration Check to re-enable this check as part of PRs

### ISSUE THREAD

**Issue by porcelli** [apache/incubator-kie-issues#1603]
The existing Drools Ansible RuleBook Integration PR check relies on external repo hosted in kiegroup organization. 

This needs to be addressed in order to enable this PR check again.

**Comment by tkobayas** [comment]
Filed a PR https://github.com/apache/incubator-kie-drools/pull/6143

@porcelli , Sorry for not taking care of it earlier.

We maintain such a GHA in kiegroup side and the GHA was already removed in main. The PR is for 10.0.x.

After merging the PR, the GHA will no longer exist, so you will not need to "re-enable" it.

**Comment by tkobayas** [comment]
Done by https://github.com/apache/incubator-kie-drools/pull/6143
