### ISSUE TITLE
DMN JIT Executor successfully executing invalid DMN

### ISSUE THREAD

**Issue by gitgabrio** [apache/incubator-kie-issues#1605]
There is an interesting issue, that once the DMN Runner (JIT Executor) start to execute a DMN model, this model can be updated to be 'invalid', but the runner keeps executing it as it would be a valid one.
Steps to reproduce

    Start BAMOE Canvas with extended services running
    Create simple DMN model
    (Person Age: number) -> (Can Drive?: boolean), where 'Can Drive?' is a literal expression: 'Person Age >= 18'
    Execute such model with inputs: (Person Age: 15) and (Person Age: 30) you will see correct results in the runner form on the right side
    Now remove the edge between (Person Age) and (Can Drive?), the problem tab will inform about a problem
    Try again change the DMN Runner (Person Age) input, it will still continue to evaluate the results [issue]

**Comment by yesamer** [comment]
Can't assign the ticket to @AthiraHari77 - @gitgabrio Assigning it to you as you're leading the initiative.
