### ISSUE TITLE
notice file for drools is not correct

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-kie-issues#1616]
https://github.com/apache/incubator-kie-drools/blob/main/NOTICE has a list of dependencies. NOTICE files are to describe the copyright for the source files in the repo. A valid NOTICE file:

https://github.com/apache/spark/blob/master/NOTICE (you won't need the Export Control bit).

If your repo contains 3rd party source code, you may need to copy the details from the NOTICE files for the original projects (if these projects have NOTICE files).

The Drools NOTICE has a long list of dependencies. These are not supposed to appear in NOTICE files (for source releases).
This seems to apply to all the NOTICE files that I checked in [apache-kie-10.0.0-incubating-sources.zip](https://dist.apache.org/repos/dist/dev/incubator/kie/10.0.0-rc3/apache-kie-10.0.0-incubating-sources.zip)

https://dist.apache.org/repos/dist/dev/incubator/kie/10.0.0-rc3/

**Comment by LightGuard** [comment]
Thanks PJ. We'll take a look.

**Comment by pjfanning** [comment]
If the list of 3rd party projects relates to the 3rd party source code that appears in KIE, then this list should be in the LICENSE. The references should include the names of the KIE source files so that we can cross check that the KIE source files retain the source headers from the original 3rd party source files.

Non Apache licenses from the 3rd party projects should be copied into KIE. You should retain any copyright info (if present) from the 3rd party licenses.

The NOTICE only needs the NOTICE details from the 3rd party projects (if present).

**Comment by jomarko** [comment]
@pjfanning thank you for all hints and comments, just to double-check my understanding, this part of spark/NOTICE:
```
Metrics
Copyright 2010-2013 Coda Hale and Yammer, Inc.

This product includes software developed by Coda Hale and Yammer, Inc.

This product includes code derived from the JSR-166 project (ThreadLocalRandom, Striped64,
LongAdder), which was released with the following comments:

    Written by Doug Lea with assistance from members of JCP JSR-166
    Expert Group and released to the public domain, as explained at
    http://creativecommons.org/publicdomain/zero/1.0/
```

Is a copied from some `Coda Hale and Yammer, Inc.` NOTICE file?

**Comment by pjfanning** [comment]
@jomarko I can't find a NOTICE in dropwizard/metrics (which I believe is forked from codahale/metrics) so what the Apache Spark team may have done here may not be best practice.

The Licensing requirements are described here:
https://infra.apache.org/licensing-howto.html

The KIE source release
* needs to look at the names of your license files - some of them don't use the name LICENSE or LICENSE.txt (eg Drools)
* prefer to include the license details of 3rd party source in the LICENSE and only add to the NOTICE when necessary (the idea of keeping the NOTICE as short as possible)
* list the files that have 3rd party source so IPMC reviewers can cross check with those files (to check those file's source headers)
* maybe, it would be best to get your mentors and possibly other IPMC members to review the PRs for license changes

**Comment by tkobayas** [comment]
Hi, here are things I have checked so far. I didn't have time to create a PR today. If no one have time for this, I will start working on a PR tomorrow.

> If your repo contains 3rd party source code, you may need to copy the details from the NOTICE files for the original projects (if these projects have NOTICE files).
> The NOTICE only needs the NOTICE details from the 3rd party projects (if present).

 - lunr: No NOTICE file in https://github.com/olivernn/lunr.js/tree/master
 - Saxon-HE: This is just a dependency, not source code. So I think we don't need to list this in NOTICE. Could you confirm? @yesamer 
 - search-ui: No NOTICE file in https://gitlab.com/antora/antora-lunr-extension
 - antora ui-bundle: No NOTICE file in https://github.com/stephengold/antora-ui-bundle
 - (Only for main. This doesn't exist in 10.0.x) JavaParser, JavaLexer: No NOTICE file in https://github.com/antlr/grammars-v4/tree/master/java

> If the list of 3rd party projects relates to the 3rd party source code that appears in KIE, then this list should be in the LICENSE. The references should include the names of the KIE source files so that we can cross check that the KIE source files retain the source headers from the original 3rd party source files.

 - lunr: ./drools-docs/supplemental-ui/js/vendor/lunr-2.3.9.min.js
 - Saxon-HE: -
 - search-ui: ./drools-docs/supplemental-ui/css/search.css
              ./drools-docs/supplemental-ui/js/search-ui.js
 - antora ui-bundle: ./drools-docs/ui-bundle/ui-bundle.zip (This should be listed in LICENSE-BINARY ?)
 - (Only for main. This doesn't exist in 10.0.x) JavaParser, JavaLexer: ./drools-drl/drools-drl-parser/src/main/antlr4/org/drools/drl/parser/antlr4/JavaParser.g4
                                                                        ./drools-drl/drools-drl-parser/src/main/antlr4/org/drools/drl/parser/antlr4/JavaLexer.g4

> Non Apache licenses from the 3rd party projects should be copied into KIE. You should retain any copyright info (if present) from the 3rd party licenses.

 - lunr: LICENSE file exists in https://github.com/olivernn/lunr.js/tree/master
 - Saxon-HE: -
 - search-ui: LICENSE file exists in https://gitlab.com/antora/antora-lunr-extension
 - antora ui-bundle: LICENSE file exists in https://github.com/stephengold/antora-ui-bundle
 - (Only for main. This doesn't exist in 10.0.x) JavaParser, JavaLexer: No LICENSE file exists in https://github.com/antlr/grammars-v4/tree/master/java

**Comment by pjfanning** [comment]
I think you will need to contact the antlr team to find out about what license file applies. What source code have you taken from antlr grammars?

**Comment by yesamer** [comment]
> Saxon-HE: This is just a dependency, not source code. So I think we don't need to list this in NOTICE. Could you confirm? 

@tkobayas Correct, you can safely remove it.

**Comment by tkobayas** [comment]
> I think you will need to contact the antlr team to find out about what license file applies. What source code have you taken from antlr grammars?

We can confirm from the license headers that they are BSD.

https://github.com/apache/incubator-kie-drools/blob/main/drools-drl/drools-drl-parser/src/main/antlr4/org/drools/drl/parser/antlr4/JavaLexer.g4
https://github.com/apache/incubator-kie-drools/blob/main/drools-drl/drools-drl-parser/src/main/antlr4/org/drools/drl/parser/antlr4/JavaParser.g4

> No LICENSE file exists in https://github.com/antlr/grammars-v4/tree/master/java

I meant just a `LICENSE` file doesn't exist under https://github.com/antlr/grammars-v4/tree/master/java . So we can create `LICENSE-antlr-grammars-v4-java.txt` file by copying the license header?

**Comment by tkobayas** [comment]
Done by
https://github.com/apache/incubator-kie-drools/pull/6153 (main)
https://github.com/apache/incubator-kie-drools/pull/6167 (10.0.x)

**Comment by pjfanning** [comment]
@tkobayas I haven't looked at the other KIE git repos in detail- do you know if the LICENSE/NOTICE files in the other git repos are ok? This includes the LICENSE/NOTICE that appears in the sources zip that is part of the release. We don't need to fix every issue but we need to know what work is incomplete. This relates to the issues found in https://lists.apache.org/thread/nrq50szwx37doopb23wyq33v0t3bbccg but it can be assumed that we might find more issues if we do efforts for each KIE repo like the Drool effort undertaken here.

**Comment by tkobayas** [comment]
@pjfanning Thank you for the comment.

Other repos are/were being worked by:

- https://github.com/apache/incubator-kie-optaplanner/pull/3130 (merged in main. not yet for 10.0.x)
- https://github.com/apache/incubator-kie-kogito-runtimes/pull/3714 (work-in-progress in main. not yet for 10.0.x)
- https://github.com/apache/incubator-kie-kogito-apps/pull/2111 (work-in-progress in main. not yet for 10.0.x)
- https://github.com/apache/incubator-kie-tools/pull/2746 (work-in-progress in main. not yet for 10.0.x)

To track all issues for 10.0.0 release, we have:

- https://github.com/apache/incubator-kie-issues/issues/1525

Thanks!
