### ISSUE TITLE
Setup `rowSpan` for header cells on tables with multiple header levels on DMN Editor's Boxed Expression Editor table

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#162]
# Description
This change affects Boxed Expression Editor however should be reusable on more places if needed (DMN Runner table view, Scenario Simulation grid)

We introduce this change because of DMN Decision Tables (DT). DT grid editor should display merged header cell for DT Inputs and  DT Annotations. We can understand this as single header cell per DT Input or DT Annotation column. While DT Output column has always two level header cells.

See the desired state below:
![Screenshot 2023-04-14 072212](https://user-images.githubusercontent.com/8044780/231948535-79ac971e-44ff-4fb3-90e0-1a2067baa21d.png)

Similar change however brings a lot of use cases, that may be affected and should be checked.

```[tasklist]
### Acceptance criteria
- [ ] Header cells should have their **rowSpan** set according to the column structure of the table. From the screenshot above, **input-1**, **input-2** and **annotation-1** should have **rowSpan** set to **2**. **Expression name**, **output-1**, **output-2** and **output-3** should have **rowSpan** set to **1**
- [ ] Header cells with **rowSpan** greater than **1** should have their **rowIndex** based on the most bottom row they occupy. From the screenshot above, **input-1**, **input-2** and **annotation-1** should have **rowIndex** set to **-1**. **Expression name** should have **rowIndex** set to **-2**. **output-1**, **output-2** and **output-3** should have **rowIndex** set to **-1**
- [ ] Header cells that span all the way to the last header row need to have their borders set properly.
```

**Comment by jomarko** [comment]
This issue was closed with https://github.com/tiagobento/kie-tools/pull/89

Demo of using rowSpan in table will be created as https://github.com/kiegroup/kie-issues/issues/224
