### ISSUE TITLE
[RELEASE] Drools DISCLAIMER-BINARY lists files that are no longer in the source release

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-kie-issues#1622]
https://github.com/tkobayas/drools/blob/ceb92b6fd5de0034e1abbd72c6c06bfd3aadd758/DISCLAIMER-BINARY

Probably best to remove this file - none of the listed jars appear in the source release. The name is also not a good name for this file. DISCLAIMER is used for very specific text provided by the Apache Incubator team.

**Comment by pjfanning** [comment]
fyi @porcelli @LightGuard @tkobayas

**Comment by porcelli** [comment]
@pjfanning I think those are reflecting the current state of main, not 10.0.0

**Comment by pjfanning** [comment]
The filename is wrong and this should not be included in the source release if it is kept.

I think you would be better off centralising this in your build docs.

**Comment by LightGuard** [comment]
Did this get fixed with https://github.com/apache/incubator-kie-drools/pull/6153 ?

**Comment by pjfanning** [comment]
> Did this get fixed with [apache/incubator-kie-drools#6153](https://github.com/apache/incubator-kie-drools/pull/6153) ?

No. This was raised because this issue was not addressed in the PR.

**Comment by tkobayas** [comment]
Removing `DISCLAIMER-BINARY` with the PR https://github.com/apache/incubator-kie-drools/pull/6157

Also filed https://github.com/apache/incubator-kie-drools/issues/6158 for removing the jars on main.
