### ISSUE TITLE
Research ReactFlow library to replace DMN Editor canvas

### ISSUE THREAD

**Issue by ljmotta** [apache/incubator-kie-issues#165]
Research the ReactFlow [1] library as possible candidate to replace the actual DMN Editor canvas.

[1] https://reactflow.dev/

**Comment by tiagobento** [comment]
At this point I can say that the research phase is done. The new React-based DMN Editor is almost ready to be shared with a wider audience, missing just some minor details about editing Edges and Waypoints. Of course, full parity with the current DMN Editor is not going to be reached at this time, and more iterations will have to be done.

ReactFlow is an amazing library, with a vibrant community and excellent code and documentation. I was able to use the majority of the features ReactFlow provides to solve problems that exist on the DMN Editor diagram editing.

ReactFlow is being renamed to XYFlow, which will require us to make some changes pretty soon. 

Stay tuned for updates here:
- #439
