### ISSUE TITLE
In DMN Editor's Boxed Expression Editor Context Menu, make possible to add N rows/columns with a single click

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#168]
If user wants to add N columns or rows in Boxed Expression Editor, the user needs to click N times in the add icon or N times in Insert left/right above/below.

Example:
![Screenshot 2023-05-16 164607](https://github.com/kiegroup/kie-issues/assets/8044780/a6a63a10-460a-4ec9-b033-1c4c274c0ecc)

It should be possible to add N row/columns above/below with few clicks.

```[tasklist]
### Acceptance criteria:
- [ ] Create an option in Context Menu where user can add add N rows/columns in any direction.
- [ ] Address all FIXMEs referring to this issue (grep codebase for `https://github.com/kiegroup/kie-issues/issues/168`)
```

**Comment by tiagobento** [comment]
Let's consider splitting this task in two:
1. Make BeeTable's ContextMenu mechanism aware of cells and selections (enhancement)
2. Make BeeTable's ContextMenu mechanism aware of the available space on screen (bug)

**Comment by jomarko** [comment]
Discussed with @danielzhe , we should add one more bullet point for changing context menu look for header cells, when user is about to pick a data type for the cell. In case a lot of custom data types are defined, the current context menu grows to big size.

One of proposals was to use multilevel context menus similar we use in sandbox workspace assets management.

![image](https://github.com/kiegroup/kie-issues/assets/8044780/8486b19f-e757-45dc-807c-1af32a30c3a3)
