### ISSUE TITLE
Searching within the DMN Editor is not functioning properly

### ISSUE THREAD

**Issue by phungvannarich-kepler-aavn** [apache/incubator-kie-issues#1683]
1. When I use the search function in DMN, it can locate the data, but it does not select the field that contains the data it found.
![image](https://github.com/user-attachments/assets/619c767a-b51b-4e9c-bf95-a0334752d177)
![image](https://github.com/user-attachments/assets/c2709417-c21f-4105-81d4-92ddf5a6a18d)

I expect it to select the field.
![image](https://github.com/user-attachments/assets/842b091e-62d3-41f8-b520-c3b10db9fba7)

2. It cannot search for data inside the model:
![image](https://github.com/user-attachments/assets/19266c54-9be8-4307-b4c1-70c8595b683c)

**Comment by yesamer** [comment]
Hi @phungvannarich-kepler-aavn thank you for reporting that.
This is a known issue for the Classic DMN Editor. 
The Classic editor should be considered deprecated, and it will be removed in a future Apache KIE release in favor of the new DMN editor, which is already available.
For that reason, no effort is planned on the Classic Editor different than CVE resolution and blocker issues.
Thank you.

**Comment by phungvannarich-kepler-aavn** [comment]
@yesamer Thanks for your response!
I am using the Apache KIE™ Kogito Bundle v10.0.0 extension on VS Code as my editor. I was not aware that this is deprecated.
![image](https://github.com/user-attachments/assets/f80f1084-6e38-4dcb-ae45-b29f3f498df8)

Could you tell me more about the new DMN editor? Where can I find it?

**Comment by yesamer** [comment]
@phungvannarich-kepler-aavn That extension contains both editors:

https://github.com/user-attachments/assets/003f9333-5fac-4d71-abd2-9fd3cdea098b

The Classic is still the default, but you can change it in case.

**Comment by phungvannarich-kepler-aavn** [comment]
Ah, I see. So, there is no search functionality in the new editor anymore. :(
Thanks anyway, @yesamer!

**Comment by yesamer** [comment]
I guess it's planned as a future enhancement :)
