### ISSUE TITLE
ASF releases like KIE 10.0.0 should appear in your download page

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-kie-issues#1687]
https://kie.apache.org/docs/start/download has not been updated to provide a link to the 10.0.0 source release.

Could you have a look download pages in various Apache projects to see what they include?
Example - https://pekko.apache.org/download.html

Things to highlight include the checksum and signature - and details about to verify the release files using these.

ASF rules/guidelines:
https://infra.apache.org/release-distribution.html

I would highlight the closer.lua and download.apache.org guidelines.

You might also want to add the Maven details for the 10.0.0 release. The snapshots should be linked from somewhere else. ASF download pages are for releases. Maybe you could have a separate snapshot page.

**Comment by porcelli** [comment]
@pjfanning this has happened today https://kie.apache.org/docs/start/download 

we have some delay between the release approved and the publishing of the artifacts

**Comment by pjfanning** [comment]
As Sebb points out on the mailing list, the source zip link for the artifact downloads are wrong. They must use the 'closer.lua' links described in https://infra.apache.org/release-distribution.html.

The KEYS file must be linked (but not using closer.lua - just a link using downloads.apache.org.

**Comment by porcelli** [comment]
~~sorry for the ignorance, but can you clarify what you mean by `closer.lua` ?~~

never mind, found it!

**Comment by pjfanning** [comment]
This is the right link for closer.lua https://infra.apache.org/release-download-pages.html#download-scripts - apologies for the wrong link

**Comment by porcelli** [comment]
it's updated now
