### ISSUE TITLE
Wrap up 10.0.0 release

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#1688]
- [x] Send announcement email to dev@, users@, and general@incubator
- [x] Update Downloads page on websites (https://github.com/apache/incubator-kie-issues/issues/1687)
- [x] New blog post about the release
- [x] Remove old RCs from https://dist.apache.org/repos/dist/dev/incubator/kie (https://github.com/apache/incubator-kie-issues/issues/1686)

**Comment by pjfanning** [comment]
No harm also announcing on announce@apache.org. Emails to this list must be from an apache.org address and the list is moderated. There is a good chance that the mail will be rejected if the mail is not in right format (see examples in list link below) and there is an expectation that the Download page is ready before the mail is sent.

https://lists.apache.org/list.html?announce@apache.org
