### ISSUE TITLE
The VS Code extension does not support DMN 1.5 in the SCESIM editor

### ISSUE THREAD

**Issue by phungvannarich-kepler-aavn** [apache/incubator-kie-issues#1721]
The VS Code extension does not support DMN 1.5 in the SCESIM editor:
![image](https://github.com/user-attachments/assets/e0c78490-a85f-4b78-b6f3-343928588d8f)

Below is the version of my SCESIM editor:
![image](https://github.com/user-attachments/assets/6b651529-96ec-426a-a132-ed6753b481e6)

I am using version 10.0.0 of the extension:
![image](https://github.com/user-attachments/assets/b04aabd4-93e8-43bd-9b72-4d2dfcc1a589)

The new DMN editor automatically upgrades my DMN file to version 1.5, which causes the SCESIM editor to stop working. 
Could you please help me resolve this issue?

**Comment by yesamer** [comment]
@phungvannarich-kepler-aavn Thank you for raising that. We are currently developing the new Test Scenario Editor --> https://github.com/apache/incubator-kie-issues/issues/453 that will support DMN 1.5. Please use that ticket to track the progress. At this moment, if Test Scenario is a critical asset for your project, please still use the Classic Editor.
