### ISSUE TITLE
Inline "Add row/column" buttons on BeeTable cells are disappearing when in upper/left positions, after clicked

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#187]
```[tasklist]
### Acceptance criteria
- [ ] Write a nice description for this issue.
- [ ] Add acceptance criteria here.
```

**Comment by jomarko** [comment]
I was not able to reproduce this issue. However it should be probably rechecked after #168 is finished.

**Comment by danielzhe** [comment]
I was not able to reproduce either. Can you provide more info about how to reproduce?

**Comment by tiagobento** [comment]
Yep, I tried to reproduce, but wasn't able to as well. That's good. it was an annoying bug :D Closing this issue `¯\_(ツ)_/¯ `
