### ISSUE TITLE
Support negation of duration in DMN

### ISSUE THREAD

**Issue by baldimir** [apache/incubator-kie-issues#21]
Currently it is not possible to negate a duration like e.g. this `-duration("PT1H")`. Add support for duration negation in the DMN implementation. 

Acceptance criteria: 
- Use cases like -duration("PT1H") work.
- Use cases like duration("PT1H")*-2 work.
- New code has 100% test coverage.
- New code has 0 new security vulnerabilities.

**Comment by gitgabrio** [comment]
@baldimir 
NOt sure about the request.
I've searched for "negation" [here](https://www.omg.org/spec/DMN/1.4/Beta1/PDF) and I found:
`arithmetic negation = "-" , expression ;`
`Arithmetic negation (grammar rule 2.d) is defined only when its operand is a number: in that case, its semantics is
according to the specification of op:numeric-unary-minus.`

What should be the behavior of negating a duration ?

**Comment by gitgabrio** [comment]
https://www.omg.org/spec/DMN/1.5/Beta1/PDF#%5B%7B%22num%22%3A281%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C51%2C126%2C0%5D

**Comment by gitgabrio** [comment]
@yesamer
