### ISSUE TITLE
Remove DMN Guided Tour from KIE Sandbox

### ISSUE THREAD

**Issue by porcelli** [apache/incubator-kie-issues#212]
# Context
This issue is about removal of the component below:
![Screenshot 2023-04-20 091359](https://user-images.githubusercontent.com/8044780/233289360-be8d0adf-aa4b-4e4b-b24f-6462fc731960.png)

It contains three options
## Skip tour and start DMN Runner
This option brings user to this popup below:
![Screenshot 2023-04-20 091935](https://user-images.githubusercontent.com/8044780/233290415-15f3a10a-79fa-4797-95ca-a171c6dc9167.png)

This popup is not accessible from other application menus or buttons. The question is if we should simplify DMN Guided tour popup from the first screenshot to contain just **Start DMN Runner** option or we should remove also **Setup DMN Runner** popup as part of kiegroup/kie-issues/issues/212

## Skip tour
This option simply closes the guided tour popup, there is no action item to take into account

## Take tour
This option brings user to wizard with few steps like below:
![Screenshot 2023-04-20 092717](https://user-images.githubusercontent.com/8044780/233291980-06a333c6-0061-4bd1-9787-82ad88696a13.png)

So we need to be sure we remove source code of
- [ ] wizard pages views
- [ ] logic of communicating between wizard react component and gwt events executed in canvas of the diagram

**Comment by jomarko** [comment]
Hi @porcelli @tiagobento .

Isn't complete removal of this component in conflict with effort to have as much self documented editor as possible?

I understand this component is quite problematic as it integrates two worlds a React with GWT and has some bugs. From my point of view can be still helpful if we have some read-only wizard , maybe with some gifs, for new users. I think this is quite common in similar tools. I totally agree we do not need to keep in interactive and guide user to drag a node to a canvas or similar.

Or maybe we should at least move some documentation/hints from the current Guided tour into other existing parts of KIE sandbox.

Last question, if we decide really for removal from sandbox, I think we want to remove it completely from source code, I mean from all kie channels, right?

**Comment by porcelli** [comment]
I don't think it's a conflict, the main reason is because the current implementation of the tour is not functional. 

The general feedback is that it gets in the way instead of helping. 

Try to patch and fix will likely require a lot of more work and the results wouldn't be garnered; without UX support the risk would be way too big.

So, today the best option is to remove (from all channels in the codebase).

**Comment by jomarko** [comment]
@tiagobento could I assign this to myself?

**Comment by tiagobento** [comment]
@jomarko Yes :)

**Comment by jomarko** [comment]
@porcelli @tiagobento I did some analysis before I start this task. See especially point about **Skip tour and start DMN Runner** please.
But feel free to comment any detail for sure.

**Comment by tiagobento** [comment]
@jomarko This popup is accessible by clicking the "Run" button at the Editor page when Extended Services is not connected.
