### ISSUE TITLE
Rewrite DMN Editor's "Data Types" tab in React

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#213]
As the title says, the scope of this task is to come up with a new implementation of the Data Types tab for the DMN Editor.

This implementation needs to be 100% in React, and provide all the features that are available on the DMN Editor today.

There's work that has already been done in this area, but never made it to the `main` branches. @kelvah did a lot of progress in the past, and he shared some details with me. See https://github.com/kelvah/kogito-tooling/tree/DTE-prototype-2-treeview. There are some other resources for information I can share with whoever takes this task.

Keep in mind that we're gonna be developing this without having the DMN Editor ready to use it, as a rewrite is also ongoing for it in React. It is expected that the new component called DmnDataTypesTab exposes enough features that will allow the new DMN Editor to use it without problems. We need to think about it and agree on the props that the DmnDataTypesTab component will have.

```[tasklist]
### Acceptance criteria
- [ ] A new package called `dmn-data-types-tab` is created.
- [ ] The `dmn-data-types-tab` has its own dev webapp, and works in isolation.
- [ ] The `dmn-data-types-tab` exports a component called `DmnDataTypesTab` to be consumed by the `dmn-editor` package.
- [ ] The `DmnDataTypesTab` component is  able to provide all the features available on the current Data Types tab in in the DMN Editor.
- [ ] The `DmnDataTypesTab` is entirely written in React nas has no dependencies with GWT.
- [ ] Some basic unit tests are expected for pure functions with minimal mocking necessary.
- [ ] Some basic E2E tests are expected, using PlayWright against the dev webapp.
```

**Comment by jomarko** [comment]
may we add a acceptance crieteria to update docs? feel free to assign to me such point

**Comment by tiagobento** [comment]
As many things that were planned as individual tasks before, I'm going to close this ticket and address it as part of 
- #577 

The Data Types screen has changed a little bit too. I still think it may be a good idea to extract a new package called `dmn-data-types`, especially because there is so much logic related to external ItemDefinitions. But this won't be done right away. For now, all Data Types-related logic is going to be inside `dmn-editor`.

Here's a sneak peak of the new interface.

<img width="1777" alt="image" src="https://github.com/kiegroup/kie-issues/assets/1584568/16f7935b-5980-4ff0-b01f-1553f352ca4f">
