### ISSUE TITLE
DMN's Editor Boxed Expression Editor: It's not possible to delete a table row in Safari

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#216]
The user experience in SAFARI suffers from some issues. This issue reports a couple of them, although the overall experience of the new component should be deeply checked.

Issues found so far:
- To keep the BEE menu open, you need to hold the mouse click. At the "mouse-up" event, the menu disappears.
- If you try to delete a row, nothing happens

https://user-images.githubusercontent.com/16005046/232757684-3e185300-9855-4c7a-b841-c67ea8c090a6.mov

```[tasklist]
### Acceptance criteria
- [x] BEE menu should keep open after releasing the mouse button in SAFARI
- [x] It should be possible to delete a row in SAFARI
- [x] Check that the overall UX works well in SAFARI
```

**Comment by danielzhe** [comment]
I know you already opened a PR, but it seems to working fine in the online editor, using Safari 16.5 and an external mouse:

https://github.com/kiegroup/kie-issues/assets/7305741/22cd174a-bdd8-42aa-b7b6-ac7b5b8a8028
