### ISSUE TITLE
Create new Marshallers for BPMN, DMN, and SceSim, based in TypeScript and able to run in the browser and Node.js

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#220]
# Description 
We have to create a new `dmn-marshaller` Typescript package to be used in the new `dmn-editor`. The package should expose the DMN Types that will be used in the Editor and both the `unmarshalling` (convert the a DMN xml string into a DMN TS Model) and `marshalling` (convert a DMN TS Model into a DMN xml string) APIs. 

The new `dmn-editor` will target to the DMN `1.5` version but it should be able to open any previous version, so the new marshaller should be able to support all DMN versions but always output DMN TS Models / DMN xml's version `1.5`. 

## Unmarshalling
The `DMN Marshaller` will be able to convert a DMN xml string into a DMN TS Model to be used by the editor. As stated before, the marshaller should be able to always output `1.5` models, so it should include a conversion API to convert from old DMN versions to the latest `1.5` version required by the editor.
![image](https://user-images.githubusercontent.com/2429832/236154196-65dce955-2ff1-4d15-93d5-ad8d852c940e.png)

## Marshalling
Given a DMN TS Model provided by the DMN Editor(always `1.5` version) the `DMN Marshaller` will convert it into DMN xml string. The output will always be a DMN `1.5` and it won't be converted to any other previous version.
![image](https://user-images.githubusercontent.com/2429832/236154265-9f2cffd3-8f6f-4b66-b0bb-e0ccb2d4ddc2.png)

```[tasklist]
### Acceptance criteria
- [x] Contain Typescript types for the DMN TS Models that will be used in the editor (DMN 1.5)
- [x] Expose a good a Typescript API for to `marshall` and `unmarshal` DMN files.
- [x] Should be able to `unmarshall` the content of DMN file (`any` version) and convert it to the `latest` DMN TS Model version used by the Editor (`1.5`) .
- [x] Should be able to `marshall` the given DMN TS Model (always `1.5` version) provided by the editor and generate the right DMN xml (string)
```

**Comment by jomarko** [comment]
@tiagobento do I understand correctly this task is about backend changes? In the task @yesamer mentions kiegroup/kie-issues#3 there we keep track for some visual changes. In past we were always in state that backend supports more versions of the specification as the editor UI. Should we check what should be added into editor UI or 1.4 and 1.5 DMN spec?

**Comment by tiagobento** [comment]
@jomarko This task ir not related to backend. We are going to be creating a new package to be able to transform DMN XMLs into JavaScript objects, so we can work with them easily on the new UIs we're going to build in React.

This task should not track anything related to the UI or anything.

Regarding your question: _"Should we check what should be added into editor UI or 1.4 and 1.5 DMN spec?"_
Would be good for us to have a complete assessment of what is new compared to the versions of DMN, I don't recall seeing a document with the changes comparing versions of it. Would you like to work on that @jomarko ?

**Comment by jomarko** [comment]
@tiagobento sure, lets see my analysis in https://github.com/kiegroup/kie-issues/issues/231

**Comment by tiagobento** [comment]
Alright, so this task has evolved to more than just the DMN Marshaller. I'll update the title and link a PR with a good description of what's being done.
