### ISSUE TITLE
Unable to upload/import a bpmn2 file, or any supported file extension containing capital letters, to KIE Sandbox

### ISSUE THREAD

**Issue by kbowers-ibm** [apache/incubator-kie-issues#221]
**Description:**
Uploading and importing a bpmn2 file, or a file with any supported file extension containing capital letters, results in a "Can't open file" error. These bugs were introduced to the main branch on Mar 30th (so are not on live), as a result of a recent change in how we handle extensions https://github.com/kiegroup/kie-issues/issues/91. 

**How to Reproduce:**
For capital letter bug:
1. Go to https://sandbox.kie.org/dev/#/
2. Import URL https://github.com/kbowers-ibm/kogito-examples/blob/stable/kogito-quarkus-examples/dmn-drools-quarkus-metrics/src/main/resources/org/kie/kogito/examples/LoanEligibility.dMn
3. Will receive a can't open file error

https://user-images.githubusercontent.com/92726146/233146934-c2d63870-6298-4c59-b235-6b60b2724c4a.mp4

For bpmn2 bug:
1. Go to https://sandbox.kie.org/dev/#/
2. Import URL https://github.com/kbowers-ibm/kogito-examples/blob/stable/kogito-quarkus-examples/kogito-travel-agency/basic/src/main/resources/org/acme/travels/flightBooking.bpmn2
3. Will receive a can't open file error

https://user-images.githubusercontent.com/92726146/233146957-ea31eac7-a002-4338-9626-36f63a8ee3f8.mp4

**Acceptance Criteria:**
- [x] Be able to upload and import a .bpmn2 file and successfully enter the bpmn editor page
- [x] Be able to upload and import a file with capitals in the extension and successfully enter the respective editor page
- [x] Improve test coverage of the affected area

**Comment by tiagobento** [comment]
@kbowers-ibm This is on `main`? What change introduced this error? This is a regression. Please attach a video, add clear steps to reproduce and write the acceptance criteria for this issue...
