### ISSUE TITLE
Create BeeTable component example

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#224]
### Context
We should prepare new example (https://github.com/kiegroup/kie-tools/tree/main/examples) for `BeeTable` component introduced as part of https://github.com/kiegroup/kie-tools/pull/1562. 

it should demonstrate how many different column structures (it can be seen in header cells) it may hold.

- [ ] all columns have same level of nesting
- [ ] each column has different level of nesting
- [ ] columns with same level of nesting are divided with other group of columns

**Comment by tiagobento** [comment]
I think with the new strategy @ljmotta is developing, we're going to have plenty of exemples for the Boxed Expression Editor directly in the package. I'm closing this for now.
