### ISSUE TITLE
Changing a nested data type will not erase the input value, making it possible to break the DMN Runner

### ISSUE THREAD

**Issue by ljmotta** [apache/incubator-kie-issues#226]
Changing a nested data type will not erase the fild value, this can break the DMN Runner table/form.

### Steps to reproduce: 
- Create a Structure DataType in the DMN editor; e.g. "myStruct"
- Create a type inside the Structure DataType; e.g. "myNestedType" with type "number".
- Fill "myNestedType" input using the DMN runner;
- Change "myNestedType" DataType to another one that is not compatible with thre previous type; e.g. "data and time";
- The previous input will not be erased from the DMN Runner persistence, and it will break the table/form.

### Example
https://user-images.githubusercontent.com/24302289/234085848-73f1eee2-c672-4b48-9a0e-6f1452b95f78.mp4

```[tasklist]
### Acceptance criteria
- [ ] Change a nested DataType should not break the DMN Runner;
- [ ] Change a nested DataType should erase the input field; e.g. Downloading the DMN Runner inputs should not contain the field value after the type change.
```

**Comment by jomarko** [comment]
What is a nested data type please. Is it:
- a custom data type that is a `Structure`?
- a custom `Structure` that has one of fields another `Structure` ?

**Comment by ljmotta** [comment]
It's a type that is inside a `Structure` data type. So:
```
myStruct: Structure
 - myNumber: number
```
`myNumber` is nested inside the `myStruct` data type. So if you add a value to it in the DMN runner, and for example, you change `myNumber` type to be a `date-time`, the input will not be deleted, and it will break the table. I will update the issue description.
