### ISSUE TITLE
Investigate DMN standard changes up to 1.5

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#231]
# Context 
DMN standard is evolving and currently there is version 1.5 that our team is planning to support with #220.

Aim of this issue is to summarize changes in particular versions 1.3, 1.4. and 1.5 that were not implemented in the KIE DMN editor yet.

## DMN 1.3
Analysis of this were done during work on #3 and we reported these outstanding work to support 1.3 by editor:
- [ ] #4 
- [ ] #48

## DMN 1.4
Changes needed according to the https://www.omg.org/spec/DMN/1.4/PDF/changebar

### New features
- [ ] https://github.com/kiegroup/kie-issues/issues/232
- [ ] https://github.com/kiegroup/kie-issues/issues/235
- [ ] https://github.com/kiegroup/kie-issues/issues/236
- [ ] https://github.com/kiegroup/kie-issues/issues/237
- [ ] https://github.com/kiegroup/kie-issues/issues/238
- [ ] https://github.com/kiegroup/kie-issues/issues/239

## DMN 1.5
List of changes according to the https://www.omg.org/spec/DMN/1.5/PDF/changebar

### Input data representation 
input data visual representation as file with folded corner possible ![Screenshot 2023-04-25 100150](https://user-images.githubusercontent.com/8044780/234213289-c10b31fe-5de9-42cc-b5ab-639397fba114.png)
![Screenshot 2023-04-25 115429](https://user-images.githubusercontent.com/8044780/234241688-974d3716-201e-4509-ad50-627e4913713d.png)

### The default expression language URI
The default expression language URI is updated slightly to be `https://www.omg.org/spec/DMN/20230324/FEEL/`

### Import empty names
Multiple imports with empty import names are allowed in the default namespace and their
precedence is resolved according to their definition order.
When the import name attribute is an empty string, the elements are imported in the default namespace of the
model. When a name collision occurs between an element in the default namespace and an imported element,
the imported element does not replace the one already in the default namespace while the elements without
name collision are imported.

### Unused InformationRequirements 
Tracked as https://issues.omg.org/issues/DMN15-88. We should verify the Snadbox problems tab do not report unused InformationRequirements as a problem. 

### ItemDefinition allowedValues deprecation
`allowedValues` attribute is deprecated from 1.5 secification version:
```
. The allowedValues
attribute has been deprecated as of DMN 1.5 and replaced with the typeConstraint attribute. The
typeConstraint attribute differs from allowedValues by not projecting onto collection elements but
directly constraining the collection
```
We should check what is the consequence for the constraint editor https://issues.omg.org/issues/DMN15-135

### Scientific numbers
Editor should support scientific numbers notation, e.g. 1.23e-45

https://issues.omg.org/issues/DMN15-107

### Range built-in function
should be offered as part of monaco autocompletions.
![Screenshot 2023-04-25 114829](https://user-images.githubusercontent.com/8044780/234240206-e71c622b-b914-47f1-b64d-d2dc5ed7e9e8.png)

https://issues.omg.org/issues/DMN15-99

### list replace built-in function
should be offered as part of monaco autocompletions.
![image](https://user-images.githubusercontent.com/8044780/234240574-31845745-088c-43af-a09e-5afecbc35a11.png)

https://issues.omg.org/issues/DMN15-143

## Older DMN Outstanding tasks
- [ ] https://github.com/kiegroup/kie-issues/issues/233
- [ ] https://github.com/kiegroup/kie-issues/issues/234
- [ ] https://github.com/kiegroup/kie-issues/issues/185

**Comment by jizuzqui** [comment]
Hello,

sorry if this is not the right place to have this discussion, but I was passing by when I saw the words "DMN" and "1.5" all together. Are you foreseeing in this kie-issue the open issues that DMN tf will tackle for v1.5? DMN 1.4 has been released just a few days ago [1], so I was wondering what are you going to tackle with regards to v1.5. Just asking as I'm collaborating on several projects that are using DMN and some of the developers are curious about this.

Thanks in advance!

[1] https://www.omg.org/spec/DMN#spec-versions

**Comment by jomarko** [comment]
@jizuzqui you are correct. 1.5 DMN version is in early phase . This issue was to get some initial preview of the scope of changes needed. I can recommend just to watch the changebar linked in the issue description.

The same we will done once 1.5. is officially released.
