### ISSUE TITLE
Make it possible to collapse DMN Decision service nodes on the DMN Editor diagram

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#233]
From DMN spec:
A decision service may be defined in one DRD and then shown in a different DRD when invoked internally within
the decision model by another decision. In the case of a decision service invocation internal to the decision model,
a decision service may also be shown without the details of its definition, as in a “collapsed state”. 

You can read more in [**6.2.5 Decision service**](https://www.omg.org/spec/DMN/1.4/PDF/)

![Screenshot 2023-04-25 143705](https://user-images.githubusercontent.com/8044780/234278038-29886399-20dc-455b-8574-03066f901d1b.png)

```[tasklist]
### Acceptance criteria
- [ ] Expanded/collapsed state is preserved between file reopening
```

**Comment by tiagobento** [comment]
Will be done as part of #577.
