### ISSUE TITLE
Identify DMN DRD elements with collapsed dependencies with ellipsis (...) notation

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#234]
DRG Elements with requirements not displayed on the current DRD SHOULD be notated with an ellipsis (...) to
show that this is the case.

See the "Routing" decision at the DRD below.

<img width="660" alt="image" src="https://user-images.githubusercontent.com/1584568/234333224-9ae2f999-a263-4cfc-afab-f3a0bcc49177.png"/>

From the [**DMN 1.4 spec**](https://www.omg.org/spec/DMN/1.4/PDF)  , page 167 (181 on the PDF)

**Comment by ljmotta** [comment]
The information regarding the "Partial view and hidden information" can be found on chapter 6.2.4 of the DMN 1.5 spec.
