### ISSUE TITLE
Create Helm Chart to install KIE Sandbox and its related services

### ISSUE THREAD

**Issue by porcelli** [apache/incubator-kie-issues#240]
**Description**

This task will help us to install KIE Sandbox in Kubernetes. Currently, the only way to run KIE sanbox is to manually install all the containers and connected them directly using standard Kube yaml files. This will speed up and streamline the process for users to install their instance of KIE Sandbox on Kubernetes.

Helm Charts is a technology that can enable us to install these multi-container services with a single command ([read more](https://helm.sh)).

**Acceptance Criteria**

- A Helm chart file should be created containing configurations to run KIE Sandbox and all related services.
- On running command `helm install kiegroup/kieserver`, All services related to KIE Sandbox should run in their specified port.
- We should be able to access KIE Sandbox

**Comment by LightGuard** [comment]
It would be good to see a docs PR for this as well.

**Comment by KostLinux** [comment]
Hey
@rodrigonull @thiagoelg How does the helm chart generation goes?
