### ISSUE TITLE
Create a Docker Compose file to run KIE Sandbox and its related services

### ISSUE THREAD

**Issue by RishiRajAnand** [apache/incubator-kie-issues#245]
**Description**

This task will help us to quickly get the KIE Sandbox running on local. Currently, the only way to run KIE sanbox is to manually install all tools on the infrastructure like Node 18, Java 11 etc. In addition to this, KIE Sandbox also needs other services to run, For example, KIE Sandbox (at kie-sandbox-image), Extended Services (at extended-services-image), and the Git CORS Proxy (at git-cors-proxy-image). This will speed up and streamline the process for users to run their instance of KIE Sandbox on local. 

Docker Compose is a technology that can enable us to run these multi-container services with a single command ([read more](https://docs.docker.com/compose/)). 

**Acceptance Criteria**

- A docker compose file should be created containing configurations to run KIE Sandbox and all related services.
- On running command `docker compose up`, All services related to KIE Sandbox should run in their specified port.
- We should be able to access KIE Sandbox at the port specified in docker-compose.yml file.

**Comment by LightGuard** [comment]
Do we have this documented somewhere?
