### ISSUE TITLE
Chrome Extensions are not working with GitHub's "New Code Search and Code View"

### ISSUE THREAD

**Issue by ljmotta** [apache/incubator-kie-issues#247]
GitHub Feature Preview "New Code Search and Code View" changes their UI significantly, making our query selectors obsoletes. The View and Edit pages are not loading the extension and the Editors.

### Project view (works)
![image](https://user-images.githubusercontent.com/24302289/236070535-b834f270-3833-4648-a8ef-61794ba74336.png)

### View BPMN (not working)
![image](https://user-images.githubusercontent.com/24302289/236070720-a6d0a5a2-5a1d-4d5f-8680-8bf3c0e5f5a5.png)

### Edit BPMN (not working)
![image](https://user-images.githubusercontent.com/24302289/236070950-ce53f19c-41d9-493d-9475-1026c478b3c9.png)

### View DMN (not working)
![image](https://user-images.githubusercontent.com/24302289/236070767-17042be6-2f90-41cb-9a05-0f53c526d3f0.png)

### Edit DMN (not working)
![image](https://user-images.githubusercontent.com/24302289/236070909-2b559e26-af24-4338-9545-98791e6cd899.png)

### PR (works)
![image](https://user-images.githubusercontent.com/24302289/236070836-cf0472e7-51b5-4091-a7d8-fcf9f628e76a.png)

## Code
The query selectors are located in the `packages/chrome-extension/src/app/Dependecies.ts` file.

```[tasklist]
### Acceptance criteria
- [ ] The BPMN and DMN Editors should render in `readonly` mode in the View page;
- [ ] The BPMN and DMN Editors should render and properly work in the Edit page;
```

**Comment by thiagoelg** [comment]
Seems like this is not a Feature Preview anymore and was rolled out to all users (https://github.blog/changelog/2023-05-08-the-new-code-search-and-code-view-is-now-generally-available/)

**Comment by tiagobento** [comment]
Looks like there's working being done here: https://github.com/kiegroup/kie-tools/pull/1720

**Comment by thiagoelg** [comment]
The new code view is enabled for anonymous users as well, breaking our CI: https://github.blog/changelog/2023-07-06-anonymous-users-have-access-to-new-code-view-and-navigation/

Disabling tests for now: https://github.com/kiegroup/kie-tools/pull/1813/commits/fd88d5f09875cf1f4bafa461760e995596631d54

**Comment by ljmotta** [comment]
Closed with https://github.com/kiegroup/kie-tools/pull/1720
