### ISSUE TITLE
Concatenation of string (a basic function on strings) is missing in the FEEL handbook

### ISSUE THREAD

**Issue by hanjoosten** [apache/incubator-kie-issues#248]
See https://kie.zulipchat.com/#narrow/stream/232676-kogito/topic/FEEL.20handbook.20missing.20string.20concatenation

Acceptance criteria: 
- New section in the [FEEL expressions section](https://kiegroup.github.io/dmn-feel-handbook/#feel-expressions) with the name "string concatenation" exists.
- The new section contains description and some examples. 

Repository for the handbook is [here](https://github.com/kiegroup/dmn-feel-handbook).

**Comment by baldimir** [comment]
PR is here: https://github.com/kiegroup/dmn-feel-handbook/pull/14

**Comment by baldimir** [comment]
PR merged.
