### ISSUE TITLE
Width changes are not correctly persisted

### ISSUE THREAD

**Issue by danielzhe** [apache/incubator-kie-issues#250]
This is a ticket to map all the persistence issues found during the tests in the new Boxed Expression Editor.

**Issue 1: List widths and Business Knowledge Models (Function expressions) widths are not persisted**

1. Add a List expression
2. Resize its size
3. Save the DMN file
4. Open it again
5. You will notice that the size is not persisted

**Issue 2: Annotation column in inner Decision Tables**

1. Add a Context Expression
2. Add an inner Decision Table
3. Resize the annotation column
4. Save the DMN
5. Open it again
6. The size of the Annotation Column is not persisted

```[tasklist]
### Acceptance Criteria
- [x] Literal: Width changes should be persisted (modify - save - reopen the dmn file)
- [x] Context: Width changes should be persisted (modify - save - reopen the dmn file)
- [x] Relation: Width changes should be persisted (modify - save - reopen the dmn file)
- [x] List: Width changes should be persisted (modify - save - reopen the dmn file)
- [x] Function: Width changes should be persisted (modify - save - reopen the dmn file)
- [x] Invocation: Width changes should be persisted (modify - save - reopen the dmn file)
- [x] Decision Table: Width changes should be persisted (modify - save - reopen the dmn file)
- [x] Nested Literal: Width changes should be persisted (modify - save - reopen the dmn file)
- [x] Nested Context: Width changes should be persisted (modify - save - reopen the dmn file)
- [x] Nested Relation: Width changes should be persisted (modify - save - reopen the dmn file)
- [x] Nested List: Width changes should be persisted (modify - save - reopen the dmn file)
- [x] Nested Function: Width changes should be persisted (modify - save - reopen the dmn file)
- [x] Nested Invocation: Width changes should be persisted (modify - save - reopen the dmn file)
- [x] Nested Decision Table: Width changes should be persisted (modify - save - reopen the dmn file)
```

=======

Original issues (moved to other tickets)

**Issue 1: The name of "output columns" if a single output column exist is not persisted**

1. Add a decision table with a single output column
![image](https://user-images.githubusercontent.com/7305741/236478473-c2887391-7b0d-45b4-ada4-097dc27c66bc.png)

2. Save the DMN file
3. Open it again
![image](https://user-images.githubusercontent.com/7305741/236478642-4bfbadbe-b529-4886-b8a5-a63a38f8928f.png)

4. You will notice that the "output-1" now is called "Decision-1"

This issue only happens if there is only a single output column.

**Issue 4: Empty expressions width**

Currently user can resize columns with empty expressions (the "Select Expression" cell). But there is nowhere to save the width information since the expression in this case is null.
User should not be allowed to resize those columns.

**Comment by danielzhe** [comment]
@yesamer

**Comment by yesamer** [comment]
@danielzhe I slightly changed the scope of this ticket. The first issue you reported "**Issue 1: The name of "output columns" if a single output column exists is not persisted**" is not a valid state, so that will be managed in #252 
"**Issue 4: Empty expressions width**" will be managed in #179
