### ISSUE TITLE
A Decision Table's single output column header should be merged

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#252]
**ISSUE 1**

In the case of a single output column in the decision header, the header contains 2 different rows, as shown

![image](https://user-images.githubusercontent.com/7305741/236478473-c2887391-7b0d-45b4-ada4-097dc27c66bc.png)

From DMN Specs:

`
A decision table consists of:

- A list of output clauses (one or more). Each output clause is made of a name and optional allowed values for the output entries that correspond to the clause. The output entries are contained in the rules, and the ith output entry corresponds to the ith output clause **A single output clause has no name**. 

Therefore, we should merge the 2 header rows, as the old editor did before.

<img width="405" alt="Screenshot 2023-05-09 at 20 57 26" src="https://github.com/kiegroup/kie-issues/assets/16005046/3f54efcc-ea3b-4d47-95ac-f5a091aa294c">

**ISSUE 2**

In this ticket, I would evaluate merging the "U" and "O" cells in the first header column.

```[tasklist]
### Acceptance Criteria
- [ ] Creating a Decision table based on an output simple type should have a single merged header row
- [ ] The output column should correctly be persisted (save /close / reopen )
- [ ] Merging the "U" and "O" on the first header row (HIT POLICY Cell)
```

**Comment by jomarko** [comment]
Same issue is true for a relation expression, please double check if that is fixed as part of this issue or not.
