### ISSUE TITLE
Spring-Boot 3.0.5 Migration: Review examples

### ISSUE THREAD

**Issue by pefernan** [apache/incubator-kie-issues#263]
While working in https://github.com/kiegroup/kie-issues/issues/260 we had to upgrade the `infinispan-spring-boot-starter` to the `spring-boot-3` version, it would be good to review all the Spring-Boot examples in Kogito Examples that use infinispan persistence to fix any possible issue due to this dependency.

Acceptance criteria

- [ ] Review all the Spring-Boot examples that use infinispan
- [ ] Verify that work and upgrade the starter dependency if needed

**Comment by eduardocerqueira** [comment]
not relevant for 9.1 release.

**Comment by pefernan** [comment]
This issue was already fixed by adding the `infinispan-spring-boot3-starter-remote` to the examples that require infinispan persisntence during the final migration to `spring-boot` `3.0.5` in December. 

@baldimir this starter comes from the Infinfispan bom, maybe we have to upgrade the infinispan version when we upgrade to `spring-boot` `3.2.2`?

**Comment by baldimir** [comment]
I will check during my upgrade work. Thanks for checking it.

**Comment by pefernan** [comment]
Closing as it is done!
