### ISSUE TITLE
DMN Decision components filtering stops to work after element dragged to canvas

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#269]
DMN Users can filter their decision components in the right side panel as shown in the picture below. There user filtered just 'Input data' nodes.
![Screenshot 2023-05-17 154625](https://github.com/kiegroup/kie-issues/assets/8044780/e74a58d7-d97f-4c65-8168-3212a951fa7c)

The problem is if user interacts with these nodes, it means he/she drags such node from 'Decision Components' to the canvas. The filtering stops to work and all nodes are back in the list.
![Screenshot 2023-05-17 154634](https://github.com/kiegroup/kie-issues/assets/8044780/0c528991-b3e6-4ab1-916f-5745055d7960)

**Comment by tiagobento** [comment]
@jomarko See https://github.com/kiegroup/kie-issues/issues/218#issuecomment-1724417372... Maybe we can close this issue :)

**Comment by yesamer** [comment]
I agree to close this. 
We would consider adding a filter in the new panel you introduced and described here  https://github.com/kiegroup/kie-issues/issues/218#issuecomment-1724417372, in a similar way we do in the type selector of BEE

<img width="323" alt="Screenshot 2023-09-19 at 08 27 10" src="https://github.com/kiegroup/kie-issues/assets/16005046/f73e71c0-38a9-4dfb-821b-c58fa2d9e8ca">

**Comment by jomarko** [comment]
Closing as requested
