### ISSUE TITLE
DMN Runner execution identifies wrongly missing requirements

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#270]
### Steps to reproduce
1. open sandbox.kie.org and setup kie extended services to be able to run DMN models
2. import this model (remove .txt extension before importing)
[habitability.dmn.txt](https://github.com/kiegroup/kie-issues/files/11498940/habitability.dmn.txt)
3. Open DMN tabular runner for it [1], double check the 'oxygene' and 'temperature' are empty
4. move to problems, execution anch the messages, there is twice message about missing 'temperature', however there should be one for 'temperature' one for 'oxygene' [2]

[1]
![Screenshot 2023-05-17 155947](https://github.com/kiegroup/kie-issues/assets/8044780/df3572c1-9f1e-4214-8364-f6e8aab156ab)

[2]
![Screenshot 2023-05-17 155902](https://github.com/kiegroup/kie-issues/assets/8044780/baf58121-e113-4663-a91a-66bf8dd1261a)

**Comment by ljmotta** [comment]
I investigate it a little, the problem is in the response of the JIT Executor. Not sure why this is happening but the `dmnresult` route from the `extended-services` response has two equal messages.

**Comment by jomarko** [comment]
yes, as stated above, the issue, really seems to be in `kogito-apps/jitexecutor`

because if we check the typescript code in `ExtendedServicesClient`, slightly updated due to debugging,
```js
  public async result(payload: ExtendedServicesModelPayload): Promise<ExtendedServicesDmnResult> {
    if (!this.isPayloadValid(payload)) {
      return { messages: [] };
    }

    const response = await fetch(this.DMN_JIT_EXECUTOR_DMN_RESULT_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json, text/plain, */*",
      },
      body: JSON.stringify(payload),
    });
    const txt =  await response.json();
    console.error("plain text to check: " + JSON.stringify(txt))
    return txt;
  }
```

we already see duplicated messages
![image](https://github.com/kiegroup/kie-issues/assets/8044780/310b1d65-1df6-4ffa-b046-5fde4e5e2556)

**Comment by tiagobento** [comment]
@jomarko Is this fixed? I saw there was a PR (https://github.com/apache/incubator-kie-drools/pull/5461) that was merged already.. Maybe we can close this issue?

**Comment by jomarko** [comment]
Hi @tiagobento , sorry for a late response, I rechecked the apache/incubator-kie-issues#270 with 0.32.0 prerelease

yes, the drools PR was merged, however the fix is not visible kie-tools, probably, because:
- drools  PR was for main, drools main is 8.45.0-SNAPSHOT
- kie-tools depends on kogito-runtimes  or kogtio-apps  version 1.40.0.Final  see https://github.com/kiegroup/kie-tools/blob/main/packages/root-env/env/index.js#L57-L59
- kogito-runtimes / kogito-apps   1.40.0.Final  depend on drools  version 8.40.0.Final  see https://github.com/apache/incubator-kie-kogito-runtimes/blob/1.40.0.Final/kogito-build/kogito-kie-bom/pom.xml#L21

So think these options are possible
- we can close apache/incubator-kie-issues#270, however online-editor user will not experience the fix
- we can bump up dependencies of kie-tools to some newer kogito-runtimes
- we can backport kie-issues drools PR to drools 8.40.0.Final 
- or maybe some combination of the above?

What is your suggestion please?

**Comment by jomarko** [comment]
As explained above, the issues is not in DMN Runner itself however now in dependencies of kie-tools, we will finish the complete fix via https://github.com/apache/incubator-kie-issues/issues/634
