### ISSUE TITLE
run-tests-with-build implement pluggable goals

### ISSUE THREAD

**Issue by jstastny-cz** [apache/incubator-kie-issues#275]
Currently the configuration of invoker goals is explicit, overridable in pom configuration only.

There might be room for parameterization (on top of #274 ), which would allow to optionally disable/enable particular goal.

E.g. once the build would be invoked with goals: `clean`, `unpack`, `test`. And on the second invocation it would be `verify`, keeping the previous three goals disabled and relying on using the previously prepared build directory.

Caution needs to be taken with "download sources" implementation, that might be also candidate for similar changes.

This could be achieved using plain maven properties holding default values `<invoker.goal.clean>clean</..>` and matching "enable/disable" property, e.g. `-Ddo.clean`, `-Ddo.unpack`, etc (or `-Dno.clean`, `-Dno.unpack`,...) which would activate a profile that would set/unset the default value.

And the use case mentioned above would turn out as:
1. `mvn clean verify`
2. `mvn clean verify -Dno.clean -Dno.unpack -Dinvoker.goal.test=verify`

It's debatable, what the default mode of operation should be to preserve backward compatibility - in this sense it might make more sense to use explicit disabling rather than enabling, i.e. default would be "on", not "off".

Upside of these changes compared to plain mvn invocation is keeping the scope of execution (maven reactor) identical between invocations.

**Comment by baldimir** [comment]
Closing this for now as not needed.
