### ISSUE TITLE
Projects extending org.jboss:jboss-parent

### ISSUE THREAD

**Issue by jstastny-cz** [apache/incubator-kie-issues#277]
Following projects have org.jboss:jboss-parent as a parent (transitive in some cases):
* drools (version 36)
* kogito-runtimes (version 39)
* kogito-apps (from kogito-runtimes)
* kogito-examples (from kogito-runtimes)

Version 39, being the latest, was released in 2021 already, version 36 in 2019.

Plugin management of these parent projects might introduce an outdated plugin version unless overridden on project's side.
It might be worth assessing the benefits of using such parent generally.

**Comment by eduardocerqueira** [comment]
is it still a valid issue? Would that change @baldimir did during repos migration got it covered?

**Comment by baldimir** [comment]
There is no JBoss Parent anymore. Closing this.
