### ISSUE TITLE
Helm Charts for Kogito Workflow

### ISSUE THREAD

**Issue by porcelli** [apache/incubator-kie-issues#285]
As a user I want be able to install in my Kubernetes cluster the Kogito Workflow infrastructure needed (like Job Service, Data-Index, Management consoles and all required dependencies) using Helm Charts.

**Comment by radtriste** [comment]
IIRC there was an old effort done one or 2 years ago to create some Helm charts alongside Kogito Operator to deploy easily services
@spolti can you remember who was in charge ?
I am thinking about @msmagnanijr but not sure

**Comment by spolti** [comment]
@radtriste it was Kevin Mock, ou intern at that time, since he left, this work was transferred to Mauricio, but Mauricio has moved to another team, and get back now.

**Comment by RishiRajAnand** [comment]
@tiagobento Feel free to assign it to your team or close as needed.
