### ISSUE TITLE
Decision Service nodes don't correctly encapsulate nodes

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#286]
Original Issue: https://issues.redhat.com/browse/KOGITO-8791
Zulip thread: https://kie.zulipchat.com/#narrow/stream/232676-kogito/topic/Relation.20table.20remains.20empty.20at.20runtime
Reproducer: https://github.com/hanjoosten/rvp-business/releases/tag/Relation-table-remains-empty-at-runtime

Consider a service defined with quite a few decisions in it. It is quite hard to define whether or not a decision is part of the service or not. The decisions do not 'stick' to the service canvas:

![decision doesnt snap to service](https://github.com/kiegroup/kie-issues/assets/16005046/d3530238-e560-4dd8-80b4-fdc715275a82)
drag it up again):

Also, during debugging, I sometimes want some of the encapsulated decisions to have visible output. In such a case, I drag the borderline (between the output decision and encapsulated decisions ) down. That idea works fine for debugging, however, when there are lots of lines in the visual, it is hard or sometimes impossible to grab the line to move it. (And after debugging, 

![move devider line handle dissapears](https://github.com/kiegroup/kie-issues/assets/16005046/1d57e4c8-ccef-48fa-8207-aca928ebc901)

It is not visible in the graphic layout if a decision is part of the service or not. It can result in pretty-hard-to-discover bugs. An example of such a bug was discussed [in this thread at Zulip](https://kie.zulipchat.com/#narrow/stream/232676-kogito/topic/Relation.20table.20remains.20empty.20at.20runtime)

```[tasklist]
### Acceptance Criteria
- [ ] Any Input Node inside a Decision Service MUST be stuck with it, in any condition
- [ ] Any Output Node inside a Decision Service MUST be stuck with it, in any condition
```

**Comment by tiagobento** [comment]
This will be addressed on the new React-based DMN Editor, as part of #577.
