### ISSUE TITLE
Lienzo - The end of the arrow does not match the cursor location when zooming in/out

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#29]
The end of the arrow does not match the cursor location when zooming in/out

![Peek 2021-03-17 08-33](https://user-images.githubusercontent.com/16005046/203071052-90201460-7871-46b3-a647-8ad2a94a8372.gif)

**Comment by Josephblt** [comment]
I did a pre-analysis on this and have some ideas on how to solve it. So feel free to ping or leave a comment here.

**Comment by yesamer** [comment]
@Josephblt I guess the same behavior affects https://github.com/kiegroup/kie-issues/issues/102 as well, so could it make sense to discuss with @inodeman to find a common solution?

**Comment by Josephblt** [comment]
Hello @yesamer. I think it is related, yes. @inodeman please ping me if you need to talk about this.

**Comment by inodeman** [comment]
Hi @yesamer @Josephblt I have looked at it and I remember the cursor issue, it is related as to the fact that the issue is because of zooming, but the 102 is about the toolbox, and this one is about a faulty calculation related to the zoom scale

**Comment by tiagobento** [comment]
As we're planning a big overhaul in the DMN / BPMN Editors in the short/medium term, I think we should not work on this ticket.
