### ISSUE TITLE
Stunner - Sometimes nodes are created in duplicity using the mouse

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#30]
Creating a node from another node sometimes will trigger the action two times, creating a node in duplicity. This happens using the node widget.

https://issues.redhat.com/browse/KOGITO-7095

https://user-images.githubusercontent.com/16005046/203073625-824626fa-a47c-4b3f-9f96-1df66106ab19.mp4

**Comment by Josephblt** [comment]
Hello @yesamer. The error is easily reproducible. All you need to do is click the button while moving the mouse.

**Comment by yesamer** [comment]
Great @Josephblt , I just copied and paste the Kogito ticket :)

**Comment by Josephblt** [comment]
@yesamer, I updated the PR to have the KOGITO ticket. Thanks.
