### ISSUE TITLE
Create BAMOE Canvas Quarkus Accelerator

### ISSUE THREAD

**Issue by thiagoelg** [apache/incubator-kie-issues#307]
Create the Accelerator in this repo: https://github.com/ibm/bamoe-canvas-quarkus-accelerator

Tag/branch versions based on BAMOE versions (starting on 9.0.0)

Use BOM straight from BAMOE instead of dependencies from `pom.xml`

**Comment by tiagobento** [comment]
Now that I think about it, I think https://github.com/ibm/kie-roadmap is the appropriate place for this issue.

**Comment by thiagoelg** [comment]
Closing in favor of: https://github.com/IBM/kie-roadmap/issues/140
