### ISSUE TITLE
Compiler error should state the name of the .dmn file 

### ISSUE THREAD

**Issue by hanjoosten** [apache/incubator-kie-issues#308]
# What happend?
I Got the following error, when I compiled my project:

`One of the supplied DMN Models has failed validation; cannot proceed to validation of the remaining DMN Models`

# What did I expect?
I make errors all over the time. I expect the compiler to help me to get my model right. So if there is any error, the error message should be helpful. In this case, I expect a clue to where the validation failed. The name of the .dmn file would be minimal. My model contains several .dmn files. So which one is problematic?

![image](https://github.com/kiegroup/kie-issues/assets/1159672/0a3fe225-48d3-478a-853a-93615c746097)

**Comment by yesamer** [comment]
@hanjoosten Thank you, I think we can close this as duplicate, we already have a ticket for that --> https://github.com/kiegroup/kie-issues/issues/271
