### ISSUE TITLE
Support for FEEL variable names in function parameters

### ISSUE THREAD

**Issue by hanjoosten** [apache/incubator-kie-issues#316]
In FEEL, variable names may contain multiple words (e.g. : `this is a valid FEELname`).  However, if such a variable name is used in a literal expression as the parameter of a function invocation, the parser will throw an error:

![image](https://github.com/kiegroup/kie-issues/assets/1159672/fcae582f-c26f-4235-b4cc-52436e8290d2)

The parser should be able to parse every parameter as a feel name correctly.

**Comment by tiagobento** [comment]
@hanjoosten Hi! Thanks for reporting this issue. Indeed it looks like a bug. May I ask that you give us a reproducer, please?

**Comment by hanjoosten** [comment]
@tiagobento , I tried to make a tiny reproducer, but I cannot reproduce it myself. I solved the issue in my project before I committed the changes, by renaming some variables. So in my project I cannot reproduce it either. Sorry. I am fine with it to close this issue. It can be reopened when a reproducer is there.

**Comment by hanjoosten** [comment]
[reproducer.dmn.txt](https://github.com/kiegroup/kie-issues/files/11661147/reproducer.dmn.txt)
This is a reproducer that shows that the parsing of multi-word variable names just works. It doesn't show a bug.
