### ISSUE TITLE
Deleting Decision Table top output header cell throws an error

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#324]
Once user decides to delete a decision table output, and he/she does it via top header cell, an exception is thrown
![Screenshot 2023-06-08 084625](https://github.com/kiegroup/kie-issues/assets/8044780/1c00e057-33d8-486e-8887-fb72caf41d12)

error
![Screenshot 2023-06-08 084857](https://github.com/kiegroup/kie-issues/assets/8044780/649bb1b6-9b23-40cf-ace9-330f2e3beb78)

The issue should be solved by updating mechanism of 'allowed operations' for context menus. This code is present in `BeeTableContextMenuhandler` , however set of 'allowed operations' is specific for each expression. So in this case we need to have a look into `DecisionTableExpression` -> `allowedOperations`. Please keep in mind this is topic of refactoring in #259 

Please have a look into this code:

```
      const columnCanBeDeleted =
        columnIndex > 0 &&
        atLeastTwoColumnsOfTheSameGroupType &&
        (conditions.columns?.length ?? 0) > 2 && // That's a regular column and the rowIndex column
        (conditions.column?.columns?.length ?? 0) <= 0;
```

**Comment by tiagobento** [comment]
Closing because this should be done as part of #259
