### ISSUE TITLE
Fix KIE tools target origin related security vulnerabilities

### ISSUE THREAD

**Issue by jstastny-cz** [apache/incubator-kie-issues#342]
Based on SonarQube scan, there are 6 occurrences of unspecified target origin of postMessage invocations:
```
var iframe = document.getElementById("testiframe");
iframe.contentWindow.postMessage("secret", "*"); // Noncompliant: * is used
```

The list of occurences:
* packages/editor/src/embedded/embedded/EmbeddedEditor.tsx
  * `{ postMessage: (message) => iframeRef.current?.contentWindow?.postMessage(message, "*") },`
* packages/envelope/src/embedded/EmbeddedEnvelopeFactory.tsx
  * `window.postMessage(message, "*");`
  * `iframeRef.current?.contentWindow?.postMessage(message, "*");`
* packages/online-editor/src/envelope/BpmnEditorEnvelopeApp.ts
  * `bus: { postMessage: (message, targetOrigin, _) => window.parent.postMessage(message, "*", _) },` 
* packages/online-editor/src/envelope/DmnEditorEnvelopeApp.ts
  * `bus: { postMessage: (message, targetOrigin, _) => window.parent.postMessage(message, "*", _) },`
* packages/online-editor/src/envelope/PMMLEditorEnvelopeApp.ts
  * `bus: { postMessage: (message, targetOrigin, _) => window.parent.postMessage(message, "*", _) },`

**Comment by jstastny-cz** [comment]
Moving back to Ready to take. The problem is more complex, we can't just specify any particular value during buildtime, it would break functionality.

**Comment by tiagobento** [comment]
As we discussed, this is by design to allow cross-origin communication between iframes and their parent window.
