### ISSUE TITLE
In DMN Editor's Boxed Expression Editor, Context menus for selecting data types can become too big

### ISSUE THREAD

**Issue by danielzhe** [apache/incubator-kie-issues#354]
In DMN Editor's Boxed Expression Editor, the drop down menu for selecting data types grows in size too much in cases a lot of custom data types are defined.
![image](https://github.com/kiegroup/kie-issues/assets/7305741/71ab5d6c-72b6-4536-a28f-625d004dc8d2)

There should be a better way to visualize the custom data types like, for instance, a drill down menu like the one in the online editor, menu "New File", option "Samples":

https://github.com/kiegroup/kie-issues/assets/7305741/87804025-2677-407b-b382-99b10adb4b7d

```[tasklist]
### Acceptance criteria
- [ ] There is a better way to visualize and select custom Data Types
```

**Comment by hanjoosten** [comment]
A similar issue with the dropdown menu is created [here](https://issues.redhat.com/browse/KOGITO-9413)

**Comment by danielzhe** [comment]
Thank you, @hanjoosten ! We gonna check the issue you reported.

**Comment by danielzhe** [comment]
Closing this issue because it is not anymore a really issue now that menus fits in the screen.
