### ISSUE TITLE
Gist 'root' name does not use name of kie sandbox folder

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#360]
Please compare the folder on KIE Sandbox, in this case 'Untitled folder' with gist root name, in this case 'Untitled-1.bpmn'

KIE Sandbox 'Untitled folder' contains a workflow 'Untitled-1.bmn', however it doesn't sounds as proper 'root' name on gist.

### KIE Sandbox

![Image](https://github.com/kiegroup/kie-issues/assets/8044780/1a42b1bf-91c8-4c9f-aabc-47179ab9bb62)

### Gist

![Image](https://github.com/kiegroup/kie-issues/assets/8044780/6d2bcc57-9693-4014-b55c-1ad319cd6f1f)

**Comment by ljmotta** [comment]
The Gist name reflects the first file created on it. It's not possible to set the Gist name as "Untitled Folder" without a "Untitled Folder" file, which **can't** be empty. This would be a problem when the user clones back the Gist, so I'd say this is the correct approach.

**Comment by ljmotta** [comment]
Closing as not planned.

**Comment by ljmotta** [comment]
Closing as not planned.
