### ISSUE TITLE
FEEL function `split(string, delimiter, flags)` should be removed from the DMN engine

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#364]
[Here](https://github.com/kiegroup/drools/blob/main/kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/SplitFunction.java#L41),  a FEEL function  `split(string, delimiter, flags)` is defined, even if not part of DMN 1.4 specs. 
As a result of this [conversion](https://kie.zulipchat.com/#narrow/stream/232677-drools/topic/DMN.20sort.20function.20alternatives), It should be removed keeping the `split(string, delimiter)` function only

**Comment by jomarko** [comment]
isn't this completed as part of https://github.com/kiegroup/kie-tools/pull/1757/files ?

**Comment by yesamer** [comment]
@jomarko  No, the scope of this ticket is to remove it from the engine, as not part of the specs.
//cc @baldimir
