### ISSUE TITLE
Exclude 'WEB-INF' folder and html files of gwt-editors from 'dist' folder

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#37]
Our kie-tools channels (KIE Sandbox, VS Code Extension ....) have dependency for gwt-editors builds. These gwt-editor builds contains also assets, that are not used by mentioned kie-tools channels.

We should exclude :
- WEB-INF folder
- html files

from kie-tools channels 'dist' folder.

**Comment by yesamer** [comment]
Fixed here https://github.com/kiegroup/kie-tools/pull/1347
