### ISSUE TITLE
Create new `cors-proxy` package on KIE Tools

### ISSUE THREAD

**Issue by pefernan** [apache/incubator-kie-issues#370]
Create a new `cors-proxy` package unifying the features of `@isomorphic-git/cors-proxy` & the `extended-services` cors-proxy.

- [ ] Create a new `cors-proxy` package in `kie-tools`

**Comment by thiagoelg** [comment]
Right now the extended-services package doesn't have a way for the `Allow InsecureSkipVerify` feature to be controlled without the systray.

It would be good if this new `cors-proxy` package uses an environment variable to control this feature, making it configurable during startup inside or outside a container.

Also, this might be relevant to this refactor: https://github.com/kiegroup/kie-issues/issues/389

**Comment by pefernan** [comment]
@thiagoelg good catch.. I was using yargs to build a cli to pass the those settings (port, insecure, hots...) that the proxy may need. Using envs could simplify the image config
