### ISSUE TITLE
[DMN Editor] Enable modification of constraints on DT columns

### ISSUE THREAD

**Issue by hanjoosten** [apache/incubator-kie-issues#371]
As @jomarko  described in [this blog](https://blog.kie.org/2023/01/automatically-generating-decision-tables-in-dmn.html), it is possible to add restrictions to an input row of a decision table. If a common type is being used during the generation of the DT, the values of that type are copied into the definition of that column. 
However, as a user of the editor, I have no control of these values. If the list of values in the type is modified, there is no way to `sync` those values. There is no way to see the restrictions, let alone to modify them. Currently the only way to do so is to hack the xml in a text editor. 
Wat I would like to have:

- A way to view and edit the restrictions of a column
- A button to sync the values with the given data type
- Some visual indication that tells whether or not the given values are in sync with the values of the given data type.

(This was first discussed in [this zulip thread](https://kie.zulipchat.com/#narrow/stream/232676-kogito/topic/Input.20values.20of.20an.20input.20column.20of.20a.20decision.20table.3F))

**Comment by jomarko** [comment]
@hanjoosten thank you for a issue. I tend to think _A way to view and edit the restrictions of a column_ is already available in the modeler.

Here is how my custom type is defined:
![Screenshot 2023-06-28 112557](https://github.com/kiegroup/kie-issues/assets/8044780/9fceb7ba-8fb9-4a11-aed4-5f3364be3f30)


Then I prepared one InputData node `InputData-1` connected to a decision node `Decision-1`. Then Setting expression type for `Decision-1` as Decision Table I get.

![Screenshot 2023-06-28 112623](https://github.com/kiegroup/kie-issues/assets/8044780/2153f6d0-5133-4586-b4cb-a8535c4ca034)

Please notice `Constraint` section in the panel on right side.

**Comment by hanjoosten** [comment]
@jomarko thanks for this clarification. I totally overlooked the properties in this regard. I tend to right-click in the blue header box when in search of such things. My bad.
So only remains a feature to keep the values in the constraint in sync with the actual type.
