### ISSUE TITLE
DMN's Decision Table: Changing the column data type doens't work after changing Decision node type

### ISSUE THREAD

**Issue by ljmotta** [apache/incubator-kie-issues#373]
Changing the Decision Node type to a specific type and tweaking the outputs column on the Decision Table to the same type doesn't trigger an update.

## Steps
1. Create a Decision Node;
2. Open the decision node and set it root expression as a Decision Table; do not change output column data type
3. Return from the boxed expression editor to the diagram editor
4. Select the Decision Node and change its type to a specific one (e.g. "number") using Properties panel on right side;
5. Again open  the boxed expression editor of the Decision node
6. Please notice output column data type is _Undefined_ instead of _number_
7. Try change the Output column type to _number_ via popover menu and close this popover, outoput column data type will be still a _Undefined_

## Workaround
1. Create a Decision Node;
2. Open the decision node and set it root expression as a Decision Table; do not change output column data type
3. Close and reopen the file
4. From now on the the data type sync seems to work in all scenarios, doesn't matter if data type is changed via properties panel in diagram or output column popover

## Video
https://github.com/kiegroup/kie-issues/assets/24302289/e110e1d2-4a1d-41f1-8c42-6e874ed07543

```[tasklist]
### Acceptance Criteria
- [ ] It should be able to change the Outputs column type idependently of the Decision Node type.
```

**Comment by jomarko** [comment]
@ljmotta thank you for the report. Could you please confirm the version of modeler you are using contains this PR https://github.com/kiegroup/kie-tools/pull/1718?

**Comment by ljmotta** [comment]
@jomarko I tested in the 0.30.0, and this commit is there.
