### ISSUE TITLE
DMN Editor: user can not increase the number of added rows/columns quickly in nested expressions

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#374]
This is an issue related to #168 feature. there is a corner case the new context menu is emptied:
![image](https://github.com/kiegroup/kie-issues/assets/8044780/5efd0019-0709-448c-b9ff-9ff332cdb90d)

**This issue can be reproduced only for nested expressions!**

### Steps to reproduce

1. open a decision node
2. set it root expression as context
3. set the context first entry as decision table
4. invoke context menu for the decision table
5. select **insert**
6. in the show sub context menu start to quickly clicking o `+` or `-`. Please notice if user click slowly, nothing happens. It is probably something with mouse events handlers, maybe doubleclick handlers?

**Comment by tiagobento** [comment]
While testing this reproducer I found another issue 😅

Btw this one looks like a very simple case of `e.stopPropagation()` at the number input component.

**Comment by danielzhe** [comment]
I found out that this issue is not reproducible exactly like this anymore, but there's still a very similar issue, but now the menu disappears instead of being blank.
See the video bellow:

https://github.com/apache/incubator-kie-issues/assets/7305741/f8e1b710-e0d8-42db-b959-108298873498
