### ISSUE TITLE
DMN Runner context menu options are not appropriate regarding the selected cell

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#376]
One general question, is by design columns can not be added/deleted neither for inputs not outputs table?

### Outputs Data cell
![Screenshot 2023-06-30 141958](https://github.com/kiegroup/kie-issues/assets/8044780/47795ba6-9700-4e50-9422-2cd7e546838a)

- Should we offer operations `Insert`,  `Delete`, `Duplicate`, `Reset`? Currently none of them works.
- Should we offer operations like `Copy`,  `Cut`, `Paste`, `Reset`? Currently none of them works. We should make only **Copy** working?

### Inputs Data cell
![Screenshot 2023-06-30 141932](https://github.com/kiegroup/kie-issues/assets/8044780/c8396bef-2487-4a11-9312-23a2ce696936)

- Should we offer operations `Insert`,  `Delete`, `Duplicate`, `Reset`? Currently none of them works.
- Should we offer single operation **Copy**?

### Outputs Header cell
![Screenshot 2023-06-30 141926](https://github.com/kiegroup/kie-issues/assets/8044780/e6744b6c-a652-40e4-9a95-162d61b8ad0b)

- Should we offer operations `Insert`,  `Delete`, `Duplicate`, `Reset`? Currently none of them works.
- Should we offer operations like `Copy`,  `Cut`, `Paste`, `Reset`? Currently none of them works. We should make only **Copy** working?

### Inputs Header cell
![Screenshot 2023-06-30 141851](https://github.com/kiegroup/kie-issues/assets/8044780/faf615ea-dd13-409d-94d9-eb13ae61a972)

- Should we offer operations `Insert`,  `Delete`, `Duplicate`, `Reset`? Currently none of them works.
- Should we offer single operation **Copy**?

**Comment by ljmotta** [comment]
## Output cell
It shouldn't have any row control. We could add support for the `Copy`.

## Output header
It shouldn't have any row or cell control.

## Input cell
It shouldn't have any row control. We could add support for the `Copy`, `Cut`, `Paste`, `Reset`.

## Input header
It shouldn't have any row control.
