### ISSUE TITLE
PIM removes dynamic task description of Human Tasks

### ISSUE THREAD

**Issue by martinweiler** [apache/incubator-kie-issues#386]
After migrating a process instance, the "Description" property of human tasks is without content. Before the process is migrated, the task has a value in that field.

During tests, if the "Description" property contains a fixed value, after migrating its value is preserved. Conversely, if the property has variable data (for example #{my_data}), after migration the "Description" field is shown blank.

**Comment by martinweiler** [comment]
Note: this is caused by changes from https://issues.redhat.com/browse/JBPM-9507 - https://github.com/kiegroup/jbpm/commit/b0cd4dd80a9ca0a18199267c740ca44327210622

**Comment by martinweiler** [comment]
Test case: https://github.com/kiegroup/jbpm/compare/main...martinweiler:jbpm:kie-issues-386

**Comment by elguardian** [comment]
https://github.com/kiegroup/jbpm/pull/2301

**Comment by martinweiler** [comment]
Scheduled for inclusion in 7.13.4 / 8.0.4: https://issues.redhat.com/browse/RHPAM-4749

**Comment by martinweiler** [comment]
Fixed in BAMOE 8.0.4, closing this issue.
