### ISSUE TITLE
Include environment variables on all KIE Sandbox-related images to configure the port used

### ISSUE THREAD

**Issue by thiagoelg** [apache/incubator-kie-issues#389]
Right now all our images (`kie-sandbox-image`, `git-cors-proxy-image`, and `kie-sandbox-extended-services`) run on specific ports and can't be configured at build or runtime.

Adding support to environment variables will enable the services running on the container to use different ports as well as expose different ports on the container, this is important for scenarios where there are port conflicts.

The running applications AND the Containerfile should support the same environment variable, for easy configuration.

**Comment by Josephblt** [comment]
Hello @thiagoelg, @tiagobento. When I translated the extended-services to Java, I used two variables to do that. 
You can see this here:
https://github.com/Josephblt/kie-tools/blob/d5eec252d1a8eb2c8802f09eeaf55ffd6e4d7776/packages/kie-sandbox-extended-services-image/Containerfile#L36
I could replicate the same for the other images. What do you guys think?

**Comment by thiagoelg** [comment]
That sounds good! As long as we keep the same ports we have now as defaults (initializing the ARGs with the default values should be enough)
