### ISSUE TITLE
Context menu sometimes shows the options for the previously selected cell on the DMN Editor's Boxed Expression Editor

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#391]
Check the videos below for reproducers. The ideal scenario would be to stop showing the Context Menu `onMouseDown` instead of `onClick` with the left-mouse-button. That's only a visual glitch, but should be fixed.

https://github.com/kiegroup/kie-issues/assets/1584568/4b7bfa21-eecf-4c90-8a48-3929ff5f4324

This second problem is more serious, where the options for a cell are wrong.

https://github.com/kiegroup/kie-issues/assets/1584568/6867dd72-142d-4995-9961-c5f7ff3d23bb

**Comment by danielzhe** [comment]
I think this issue is related to https://github.com/kiegroup/kie-issues/issues/420

I'm investigating, I think we can fix both issues with the same PR
