### ISSUE TITLE
chrome-extension: Some DMN Files are not correctly loaded

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#399]
Step to reproduce:

1. Install the KIE chrome-extension version 0.31.0
2. Try to open any DMN file with spaces in the file name (eg. "Traffic Violation.dmn") part of any repository
3. The editor works, but data is not loaded (DRG and Data Types are not loaded)

Files with no space (eg. "TrafficViolation.dmn") work correctly.

https://github.com/kiegroup/kie-issues/assets/16005046/a363bf3a-1598-4419-b76b-7c458f4dd780

**Comment by ljmotta** [comment]
When the filename has empty spaces the file fetch is wrongly performed to the "undefined" branch.

![image](https://github.com/kiegroup/kie-issues/assets/24302289/77298eb6-9ed6-43c3-97de-8a5afc8e00ef)
