### ISSUE TITLE
Implement DMN 1.3 Group Element

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#4]
The aim of this ticket is to add the *Group* node as defined in DMN 1.3 version.

**Group**
A Group consists of a rounded corner rectangle drawn with a solid dashed line that groups elements together informally.

<img width="561" alt="Screenshot 2022-10-07 at 11 02 49" src="https://user-images.githubusercontent.com/16005046/198632037-dbd636d4-0cba-41b8-9c2d-6ad6d1733c37.png">

The Group object is an Artifact that provides a visual mechanism to group elements of a diagram informally.
Groups are often used to highlight certain sections of a Diagram without adding additional constraints for performance.
The highlighted (grouped) section of the Diagram can be separated for reporting and analysis purposes. Groups do not affect the execution of the Decisions.
As an Artifact, a Group is not a DRGElement, and, therefore, cannot be connected to/from an Information Requirement, Knowledge Requirement, or Authority Requirement. It can only be connected to/from an Association.

**DataModel changes**

    Definitions attributes and model associations
    artifact: Artifact [0..*] Artifacts include text annotations, groups, and associations among DMN elements.
    Group model associations
    name: String[0.. 1] The descriptive name of the element.

**Comment by tiagobento** [comment]
Will be delivered as part of #577.
