### ISSUE TITLE
DMN Editor's Boxed Expression Editor: cut/paste functionality must generate new IDs

### ISSUE THREAD

**Issue by hanjoosten** [apache/incubator-kie-issues#401]
In the DMN editor, functionality is present to duplicate rows and to cut and paste (multiple) cells. In these cases, all newly created cells must become an id of their own. Currently, the id is being copied, which obviously is a bug. Note that when a cell is being copied that contains a decision table or context, there can be cells contained in there too. These cells must become an id of their own as well.

Today I have been editing a context, using cut/paste of decision tables inside the context. When compiling, I got the following error message:

~~~
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.252 s
[INFO] Finished at: 2023-08-07T11:12:41+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.kie.kogito:kogito-maven-plugin:1.36.0.Final:generateModel (default-generateModel) on project rvp-machine: Execution default-generateModel of goal org.kie.kogito:kogito-maven-plugin:1.36.0.Final:generateModel failed: DMN Validation schema and model validation contained errors
[ERROR] You may configure kogito.decisions.validation=IGNORE to ignore validation errors
[ERROR] DMN Validation errors:
[ERROR] : Failed XML validation of DMN file: cvc-id.2: There are multiple occurrences of ID value '_EC229F1E-A277-4B95-8B36-622536A10A73'.,
[ERROR] : One of the supplied DMN Models has failed validation; cannot proceed to validation of the remaining DMN Models.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
~~~

And here is the result after my editing:
[pvc_PlannenVaccinatieComponent.zip](https://github.com/kiegroup/kie-issues/files/12274499/pvc_PlannenVaccinatieComponent.zip)

**Comment by tiagobento** [comment]
I think this will be much easier once we have #455 , since we'll be able to use 
- https://github.com/tiagobento/kie-tools/blob/dmn-editor/packages/xml-parser-ts/src/idRandomizer.ts
