### ISSUE TITLE
Identify pipelines that should be moved to Apache

### ISSUE THREAD

**Issue by eduardocerqueira** [apache/incubator-kie-issues#415]
Includes:

- automated PR checks (validation, running unit/smoke tests, code scanners, etc.)
- nightly, weekly jobs to we have
- any other automation required by current CI

**Comment by eduardocerqueira** [comment]
moved to description ^

**Comment by radtriste** [comment]
@mareknovotny let me know if you need any help for Kogito/Drools8 part

**Comment by mareknovotny** [comment]
I guess we need to take https://github.com/kiegroup/kogito-pipelines/tree/main and clean or replace all environmental configurations
Also *prod* specifics will need to stay in mirrored github repository only. I am not sure if it is better to copy only source related to new Apache repositories and environment. So this repository stays as it is and we will disable things for upstream on kie org and our internal Jenkins instance. WDYT @radtriste ?

**Comment by radtriste** [comment]
I think it depends also which branch(es) are moved.

DSL configs:
- [Kogito](https://github.com/kiegroup/kogito-pipelines/tree/main/dsl/config)
- [Drools](https://github.com/kiegroup/drools/tree/main/.ci/jenkins/config)
- [OptaPlanner](https://github.com/kiegroup/optaplanner/tree/main/.ci/jenkins/config)

**Comment by mareknovotny** [comment]
@radtriste branches doesn't matter for first phase, only main should be active on Apache from beginning

**Comment by radtriste** [comment]
ok. I am working on trying to setup the seed job correctly on Jenkins.
Here are the config changes on Kogito for now: https://github.com/kiegroup/kogito-pipelines/pull/1039
We will need to apply same for Drools and OP later.

For prod config, most of the prod jobs are defined in `kie-ci` repository, using one or 2 files from `kogito-pipelines`
I don't think it will be a huge change. We may move the repository to Apache, create the mirror in Red Hat and remove then on Apache the prod related stuff. wdyt ?

**Comment by mareknovotny** [comment]
i would keep kie-ci in the kiegroup org and move there only necessary stuff for Apache CI

**Comment by eduardocerqueira** [comment]
closing this issue, pipelines have been identified!
