### ISSUE TITLE
Gather information on Apache infrastructure and available tools for running CI

### ISSUE THREAD

**Issue by eduardocerqueira** [apache/incubator-kie-issues#416]
research about Jenkins and infrastructure constraints for running the workload

**Comment by eduardocerqueira** [comment]
moved to description ^

**Comment by jstastny-cz** [comment]
As a first step I'll create an INFRA Jira asking for dedicated Jenkins folder, which would be editable by all commiters.

EDIT: Created https://issues.apache.org/jira/browse/INFRA-24897 .

**Comment by radtriste** [comment]
Gathering document: https://docs.google.com/document/d/1F1FIwGN0W3KEQbYLJz5pYOwDV2qmKONpeixlTD6w6cw/edit?usp=sharing

**Comment by baldimir** [comment]
Closing this as done. The document is the reference.
