### ISSUE TITLE
EPIC - Move pipelines and CI to Apache

### ISSUE THREAD

**Issue by eduardocerqueira** [apache/incubator-kie-issues#417]
Actual work for moving pipelines to Apache.

depends on:

- https://github.com/kiegroup/kie-issues/issues/415
- https://github.com/kiegroup/kie-issues/issues/416
- #605

**Comment by eduardocerqueira** [comment]
moved to description ^

**Comment by radtriste** [comment]
We also need to take care of those for Jenkins:
- tools (jdk, maven, golang)
- GH credentials
- Apache nexus snapshot/release repositories urls and creds
- Maven settings file
- Quay credentials

a quick overview can be found in https://github.com/kiegroup/kogito-pipelines/blob/main/dsl/config/branch.yaml

**Comment by radtriste** [comment]
We should ask the Nexus team to get in touch with Sonatype to remove the sync between Central and JBoss Nexus about those group ids:
- org.kie
- org.drools
- org.optaplanner

**Comment by eduardocerqueira** [comment]
This Epic will be updated next week.
