### ISSUE TITLE
Create proposal for guidelines and conventions for issue tracking and labeling on `kie-issues`

### ISSUE THREAD

**Issue by eduardocerqueira** [apache/incubator-kie-issues#418]
Create a document outlining:

- A template for issues
- Suggested labels
- Process for moving tickets through the various boards

Stretch
- Outline a review process for tickets and pull requests
  - We've already decided that there will be no commits directly to the main branch, it all needs to happen through PRs. Those PRs will at the beginning need to have two reviewers. Any committer and a PPMC member from the Apache KIE Community

**Comment by tiagobento** [comment]
I'd like to be part of this one, I think I might have valuable contributions :)

**Comment by LightGuard** [comment]
Feel free to add yourself to it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tiagobento** [comment]
I don't have bandwidth to lead this effort right now, @LightGuard :/

**Comment by LightGuard** [comment]
I didn’t say lead :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by LightGuard** [comment]
I started a Box note to discuss the template at https://ibm.box.com/s/2975faxug2rn3bpt4phbgdzi4tnif35j

**Comment by LightGuard** [comment]
Discussion happening on the list: https://lists.apache.org/thread/xnn2l491874sqj5xkfw3p7dxgtn4yx92

**Comment by LightGuard** [comment]
The conversation has died on the list; we should revive it. @tiagobento, will you please add a message to the list?

**Comment by eduardocerqueira** [comment]
We will postpone this initiative for now, let's focus on transferring the repos and CI and wait things get settled down after recent enhancement with new [labels](https://github.com/apache/incubator-kie-issues/labels) have been added to the project and a few recent updates to the [Project Board](https://github.com/orgs/apache/projects/295/views/1) to improve transparency, collaboration and tracking.
