### ISSUE TITLE
Identify branches to maintain in each `kiegroup` repository

### ISSUE THREAD

**Issue by eduardocerqueira** [apache/incubator-kie-issues#419]
Repos:

```
https://github.com/kiegroup/drools
https://github.com/kiegroup/kogito-runtimes
https://github.com/kiegroup/kogito-apps
https://github.com/kiegroup/kogito-examples
https://github.com/kiegroup/kogito-docs
https://github.com/kiegroup/kogito-images
https://github.com/kiegroup/kogito-operator
https://github.com/kiegroup/kogito-website
https://github.com/kiegroup/kogito-pipelines
https://github.com/kiegroup/kie-tools
https://github.com/kiegroup/kie-benchmarks
https://github.com/kiegroup/optaplanner
https://github.com/kiegroup/kogito-serverless-operator
https://github.com/kiegroup/optaplanner-quickstarts
https://github.com/kiegroup/kie-docs
https://github.com/kiegroup/kogito-benchmarks
https://github.com/kiegroup/kie-sandbox-quarkus-accelerator
https://github.com/kiegroup/kogito-online-staging
https://github.com/kiegroup/kogito-online
```

**Comment by radtriste** [comment]
@eduardocerqueira @porcelli @baldimir 
here are my questions from the repositories we currently use:
- `kogito-serverless-operator` stays is not moved ?
- `kie-jpmml-integration` should be moved ? cc @danielezonca 
- if `optaplanner` is moved, shouldn't we move `optaplanner-quickstarts` and `optaplanner-website` as well ?
- what about `drools-website` ?
- what would become of `kie-docs` ?

For reference, here are the configuration we use on pipelines to generate Jenkins jobs for Kogito/Drools8/OP8, and it helps to know which repositories are currently in use:
- [drools config](https://github.com/kiegroup/drools/blob/main/.ci/jenkins/config/branch.yaml#L59-L61)
- [optaplanner config](https://github.com/kiegroup/optaplanner/blob/main/.ci/jenkins/config/branch.yaml#L58C1-L60)
- [kogito config](https://github.com/kiegroup/kogito-pipelines/blob/main/dsl/config/branch.yaml#L69-L79)

**Comment by porcelli** [comment]
@radtriste I think all the repositories you listed has been overlooked. I think they should be part of the move.

the -websites are a bit trick, as we need some updated version of the sited under Apache, as we need to better communicate KIE (as it's the official project) and better positioning the sub-projects (drools, jbpm, etc)

@lazarotti @mdproctor @krisv ?

**Comment by MarianMacik** [comment]
@eduardocerqueira @porcelli @baldimir
There is one more repository, which I highlighted in the initial Apache Move Planning document:
`https://github.com/kiegroup/kogito-benchmarks`

**Comment by tiagobento** [comment]
We have https://github.com/kiegroup/kie-sandbox-quarkus-accelerator as well, used on the community production environments of KIE Sandbox, like https://sandbox.kie.org, https://dmn.new, and https://bpmn.new. The branches of this repo are described on its README.

**Comment by tiagobento** [comment]
For these production community environments to work, we also depend on two other repos, that are used for the GitHub Pages deployments: 
- https://github.com/kiegroup/kogito-online-staging
    - Only the `main` branch is necessary
- https://github.com/kiegroup/kogito-online
    - Only the `gh-pages` branch is necessary.

Their names contain `kogito` for historical reasons, but they're both part of the KIE Tools production community infrastructure.

**Comment by tiagobento** [comment]
@ederign Correct me if I'm wrong, but I think https://github.com/kiegroup/serverless-logic-sandbox-deployment is analogous to https://github.com/kiegroup/kogito-online for Serverless Logic Web Tools, right?

**Comment by ederign** [comment]
I think so, but let's confirm with @caponetto

**Comment by caponetto** [comment]
@ederign @tiagobento Yes. The deployment of Serverless Logic Web Tools is on `gh-pages` branch (dev and staging included) and the Quarkus accelerator is on `quarkus-accelerator` branch.

**Comment by porcelli** [comment]
Repos to move:
kogito-serverless-operator
optaplanner-quickstarts
kie-docs
kogito-benchmarks
kie-sandbox-quarkus-accelerator
kogito-online-staging
kogito-online

2nd Phase Move:
*-website (will need updates, will use jbake)

Left behind:
jpmml left behind (probably can't anyway due to license)
serverless-logic-sandbox-deployment

**Comment by MarianMacik** [comment]
> Repos to move: kogito-serverless-operator optaplanner-quickstarts kie-docs kogito-benchmarks kie-sandbox-quarkus-accelerator kogito-online-staging kogito-online
> 
> 2nd Phase Move: *-website (will need updates, will use jbake)
> 
> Left behind: jpmml left behind (probably can't anyway due to license) serverless-logic-sandbox-deployment

@porcelli Where are `kogito-runtimes`, `kogito-apps`, `kogito-examples` and others from the [first comment](https://github.com/kiegroup/kie-issues/issues/419#issue-1847039846)?

**Comment by porcelli** [comment]
@MarianMacik if you check I also updated the description of the issue to incorporate my last comment.

my last comment was just for record the decision that were made during the sync call we had early today between Red Hat and IBM

**Comment by eduardocerqueira** [comment]
At this point all repos were identified. The repos migration is tracked on this issue https://github.com/kiegroup/kie-issues/issues/428
and the copyrights and headers on this https://github.com/kiegroup/kie-issues/issues/413

**Comment by porcelli** [comment]
not so fast @eduardocerqueira 

Just found out https://github.com/kiegroup/drools-lsp

And we also have kie-issues

**Comment by porcelli** [comment]
thank you @tarilabs to spot one more repo that has been left behind.

https://github.com/kiegroup/dmn-feel-handbook#readme

**Comment by porcelli** [comment]
there's also this repository https://github.com/kiegroup/kie-issues

**Comment by eduardocerqueira** [comment]
Thank you everyone for the comments with the missed repos, they were added to the EPIC https://github.com/orgs/apache/projects/295/views/3?pane=issue&itemId=40508194 where we will continue tracking the work for transferring the repos to Apache.

Closing this task, pls use the EPIC listed above for further comments.
