### ISSUE TITLE
DMN Editor: Repeatitive opening of properties panel for List expression

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#42]
If User tries to open properties panel for multiple List Expression entries, an error is thrown - stack size exceeded.

For more details see the issue and attached video there https://issues.redhat.com/browse/KOGITO-2961

Or alternatively:
- Create new diagram
- Add a Decision node
- Open the decision node
- Set its expression type as List expression
- Open and Close (~5times) properties panel for the first list entry
- Add one more list entry
- Again Open and Close (~5times) properties panel for the second list entry
- When properties panel is closed/collapsed, select first list entry
- Try to open properties panel, an exception will be thrown

![Screenshot_20230111_110927](https://user-images.githubusercontent.com/8044780/211778258-d8022171-b8c6-4a7f-927b-d353185cc830.png)

**Comment by yesamer** [comment]
@jomarko Can you please describe how to reproduce this issue with detailed steps? Thank you!

**Comment by jomarko** [comment]
@yesamer done

**Comment by yesamer** [comment]
It seems the root cause is an infinite loop in this method:
`DMNModelInstrumentedBase:getDefaultNamespace()`
The element's parent has a parent reference that points to itself. In this condition, navigating the parents hierarchy lead to infinite loop.


Most likely the issue is located in the new List Item action.

**Comment by yesamer** [comment]
**Observations:**
If the List contains an item only, the issue never occurs.
Just after you add a new list item, selecting the first entry throws the exception. 
Adding n additional elements keeps the behavior immutable: the first entry throws the exception.

**Comment by yesamer** [comment]
Temporary drop this due to other priorities - Feel free to take it
