### ISSUE TITLE
Boxed expression component "insert multiple" columns/rows doesn't reset when opening another cell menu

### ISSUE THREAD

**Issue by ljmotta** [apache/incubator-kie-issues#421]
The "insert multiple" columns/rows doesn't reset when opening the context menu from another cell.

## video
https://github.com/kiegroup/kie-issues/assets/24302289/d91601af-c640-4459-8e92-6be6c99d37ec

## steps
1. open a Relation expresion;
2. right click on a cell to open the context menu;
3. click on "Insert >"
4. right click on another cell;
5. the "Insert >" menu will still be opened.

```[tasklist]
### Tasks
- [ ] The option to insert multiples lines should reset when opening another cell's context menu
```

**Comment by tiagobento** [comment]
Not reproducible anymore. Thanks for testing it again @danielzhe!
