### ISSUE TITLE
Adjust forms-generation-tool to properly release the cli for Linux, macOS and Windows

### ISSUE THREAD

**Issue by porcelli** [apache/incubator-kie-issues#424]

**Comment by tiagobento** [comment]
Releasing on NPM with a `bin` entry should be enough for people to be able to use it... All agree?

**Comment by porcelli** [comment]
for now, it's ok!

**Comment by jomarko** [comment]
@tiagobento @porcelli would you mind to add more detailed description, what are acceptance criteria. i see you discussed in comments, but still not sure . Is there any existing librabry on npm repository that can be like example of demanded result?

**Comment by ljmotta** [comment]
@jomarko The `build-env` is an example of package that has a `bin` entry on its `package.json`. With the `bin` entry it'll be possible to directly use it in the CLI after the package is installed. Now, to use without node it would require to release the binaries, and for that we need to add steps in our CI as we have for the `extended-services` and `kn-plugin-workflow` packages.

**Comment by yesamer** [comment]
@porcelli  @tiagobento We completed all the tasks related to form-generation-tool, should we start to work on this ticket too?
//cc @pefernan

**Comment by porcelli** [comment]
+1 from me

**Comment by jomarko** [comment]
Hello team, I just wonder what are the 'acceptance criteria' here.

- what should be the cli command name? should it be `form-generation-tool`? or should the name somehow reflect `apache`, or `kie` ?
- am I correct user will be intended to firstly execute `npm install -g @kie-tools/form-generation-tool` to make this new cli command available on his/her machine?


I was able to prepare a `packages/form-generation-tool/src/cli/cli.js` file:
```
#! /usr/bin/env node
/* License omitted */
require("../../dist/index");
```

then I prepared update in `packages/form-generation-tool/package.json`:
```
  "bin": {
    "form-generation-tool": "./src/cli/cli.js"
  },
```
and was able to execute it as `npm run form-generation-tool`  from the `packages/form-generation-tool` folder


However I somehow feel, this is not enough verification before some `npm publish` is done.


Could somebody help me with better understanding acceptance criteria? How to be sure prepared changes are expected?

**Comment by yesamer** [comment]
> * what should be the cli command name? should it be `form-generation-tool`? or should the name somehow reflect `apache`, or `kie` ?

+1 using `form-generation-tool` as command name

> * am I correct user will be intended to firstly execute `npm install -g @kie-tools/form-generation-tool` to make this new cli command available on his/her machine?

I guess this is inevitable, I mean, the user needs to install the library before using that. I don't see alternatives.

@pefernan @tiagobento can you please share your thoughts too?

**Comment by jomarko** [comment]
@yesamer thank you for your input. I prepared a PR when I follow this naming - `form-generation-tool`.

Anyone, please feel free to have a look on the [PR ](https://github.com/apache/incubator-kie-tools/pull/2123)

**Comment by pefernan** [comment]
Sorry for being late here,

> * what should be the cli command name? should it be `form-generation-tool`? or should the name somehow reflect `apache`, or `kie` ?

+1 to keep the `form-generation-tool` name

> * am I correct user will be intended to firstly execute npm install -g @kie-tools/form-generation-tool to make this new cli command available on his/her machine?

+1 too

**Comment by jomarko** [comment]
FYI, this feature is cancelled with https://github.com/apache/incubator-kie-issues/issues/1493
