### ISSUE TITLE
Create Apache confluence workspace

### ISSUE THREAD

**Issue by errantepiphany** [apache/incubator-kie-issues#430]

**Comment by LightGuard** [comment]
https://cwiki.apache.org/confluence/display/KIE/Apache+KIE+Home Isn't this done?

**Comment by errantepiphany** [comment]
It is, but I'm trying to come up with a structure to the area that will fit our needs, present it to the team, and then create just the skeleton in it, for others to then go ahead and flesh out.

**Comment by errantepiphany** [comment]
Closing issue as the workspace is created. Adding content to it can be separate issues.
