### ISSUE TITLE
[DMN-Editor] Prefix of imported file is used wrongly

### ISSUE THREAD

**Issue by hanjoosten** [apache/incubator-kie-issues#436]
There is a namespace error when using datatypes from an imported model. The attribute names are incorrectly showing the prefix of the type. 

Assume we have a file that contains a data type:
![image](https://github.com/kiegroup/kie-issues/assets/1159672/f8c5dd54-743e-48ba-8724-bdbaa6c32942)

That file is imported from another .dmn file, that consumes the data types:
![image](https://github.com/kiegroup/kie-issues/assets/1159672/66c02275-7acf-4f42-9b3a-67426be2b2f9)

Now in that file we create a decision, and specify the imported data type. We also give it some input:
![image](https://github.com/kiegroup/kie-issues/assets/1159672/342c1719-3cc1-427e-84fd-e844dc6ca328)

If I open the `Edit` button on the decision, I am able to select an expression. I select `decision table`:
![image](https://github.com/kiegroup/kie-issues/assets/1159672/53e15a93-ba9f-4b7d-994a-55ca990643da)

The input and output columns are filled automatically, but wrong:
![image](https://github.com/kiegroup/kie-issues/assets/1159672/e88636a6-ccca-496d-9875-9f50a99f5926)

As you can see, the attribute names are prefixed with the namespace of the imported file. 

What I expected is this:
![image](https://github.com/kiegroup/kie-issues/assets/1159672/12a898b1-6a98-4a37-bbec-b6cd37d7dbbd)

This clearly is a bug.

**Comment by hanjoosten** [comment]
[reproducer_Kie-issues_435.zip](https://github.com/kiegroup/kie-issues/files/12359511/reproducer_Kie-issues_435.zip)

**Comment by hanjoosten** [comment]
I see now that I reported a similar issue: https://issues.redhat.com/browse/KOGITO-7601

**Comment by tiagobento** [comment]
Great catch. Definitely a bug. Thanks for all the issues you're reporting @hanjoosten! We still have a long way to go, but we'll get there. Please do keep reporting everything you find, and feel welcome to propose new ideas as well. Every contribution helps!

**Comment by tiagobento** [comment]
Will be fixed as part of #577.
