### ISSUE TITLE
DMN Editor: Autolayout is broken for decision services

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#44]
If user tries open diagram with decision services, without layout, the autolayout prepares a wrong layout.

What user gets:
![image-2020-06-23-08-19-08-376](https://user-images.githubusercontent.com/8044780/204272334-6ca918ef-d99f-4292-b86d-ddf632af508e.png)

What is expected (not strictly, but it is organized at least semantically, the decision is in decision service):
![image-2020-06-23-08-19-30-423](https://user-images.githubusercontent.com/8044780/204272451-b56a2638-8d8a-4afa-acd9-6052dc67e6d8.png)

Used dmn model: [basicAdd.txt](https://github.com/kiegroup/kie-issues/files/10103516/basicAdd.txt)

**Comment by yesamer** [comment]
Please consider this Ticket too https://issues.redhat.com/browse/DROOLS-7059
