### ISSUE TITLE
DMN Editor: Expression Editor context menu not visible in corner cases

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#45]
The expression editor context menu is not visible/usable if invoked in a corner case. It means for some expression row that is last visible on the screen. See the attachment.

![image-2020-07-16-12-21-06-744](https://user-images.githubusercontent.com/8044780/204273842-71da1239-68a4-4560-9203-ea9a79e721a4.png)

**Comment by yesamer** [comment]
The same issue occurs in SceSim as well.

**Comment by jomarko** [comment]
This issue is being solved via https://github.com/kiegroup/kie-tools/pull/1362
