### ISSUE TITLE
EPIC - Flexible KIE Sandbox Dev deployments (including BPMN!)

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#452]
### Tasks
- [x] https://github.com/kiegroup/kie-issues/issues/475
- [x] https://github.com/kiegroup/kie-issues/issues/476

**Comment by tiagobento** [comment]
Moved

- https://github.com/kiegroup/kie-issues/issues/478
- https://github.com/kiegroup/kie-issues/issues/481

to 

-  #662

**Comment by eduardocerqueira** [comment]
@eduardocerqueira review commitment

**Comment by tiagobento** [comment]
Moved
- https://github.com/kiegroup/kie-issues/issues/477
- https://github.com/apache/incubator-kie-issues/issues/652
- https://github.com/kiegroup/kie-issues/issues/480

to 

- https://github.com/apache/incubator-kie-issues/issues/662
