### ISSUE TITLE
Upgrade `prettier` from `2.x.x` to `3.x.x` on `kie-tools`

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#467]
This will allow KIE Tools to have multiple `.gitignore` files. See https://prettier.io/blog/2023/07/05/3.0.0.html#ignore-gitignored-files-by-default-14731httpsgithubcomprettierprettierpull14731-by-fiskerhttpsgithubcomfisker

**Comment by ljmotta** [comment]
Some `jest` tests depends on `prettier`. The `prettier` `3.x` version are built using ESM, meaning that `jest` should be also use ESM on those cases. To make `jest` emmit ESM we need to use the `--experimental-vm-modules` `node` flag, the `ts-jest` version `27.x`+ [1], and check other transform plugins to emmit ESM. `prettier` version `3.x.x` will be officially supported on `jest` version `30.x`, which is still in alpha [2][3][4].

[1] https://kulshekhar.github.io/ts-jest/docs/26.5/guides/esm-support
[2] https://github.com/prettier/prettier/issues/15769
[3] https://github.com/prettier/prettier/issues/15098
[4] https://github.com/jestjs/jest/issues/13495

**Comment by ljmotta** [comment]
Create https://github.com/apache/incubator-kie-issues/issues/1332 to track the dependencies that were added to `.syncpackrc.json`
