### ISSUE TITLE
Stunner: Differences assessment of the Stunner codebases (BPMN/DMN/SCESIM vs SWF)

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#47]
As a result of the project management changes announced 10 months ago, the Stunner codebase has been forked in two different streams:

1. BPMN/DMN/SCESIM stream 
2. SWF (Serverless Workflow) stream

In the last months, several bug fixing, improvements, and new features have been merged in stream 2. We need to evaluate which of those changes are worthy to be "cherrypicked" in stream 1.

**Comment by jomarko** [comment]
@yesamer to me it seems, we have in codebase now 3 clones of appformer/uberfire. Is addressing it somehow part of #47 too?

![Screenshot from 2022-11-30 11-38-29](https://user-images.githubusercontent.com/8044780/204774700-57ed4385-0191-47a2-9cbe-935f195de12c.png)

**Comment by yesamer** [comment]
@jomarko Yep good point. I would suggest ignoring the Dashbuilder fork because I consider it a totally separate project from ours. In addition, I don't see any valuable fix/feature in its stunner modules  (https://github.com/kiegroup/kie-tools/commits/main/packages/dashbuilder/appformer), these are mostly dependencies for security updates and Dashbuilder-specific issues. WDYT?

**Comment by jomarko** [comment]
My point was rather, aren't we building the same three times during CI for example?

**Comment by yesamer** [comment]
@jomarko Our CI/CD is smart enough to build the modules related to PR changes. Eg. if you modify something on DMN Editor module, the CI will build its parent modules only, and not all the modules in kie-tools. Please correct me if I'm wrong @tiagobento

**Comment by yesamer** [comment]
I completed my analysis (with @romartin support, thank you, man!)

**Fix and Performances fixes to "cherrypick"** _(Higher Priority)_ 
- https://github.com/kiegroup/kie-tools/pull/943 Done 
- https://github.com/kiegroup/kie-tools/pull/1248 Discarded - Minimal impact on DMN/BPMN/SCESIM

**Nice to have new features** _(Lower Priority)_
- https://github.com/kiegroup/kie-tools/pull/997
- https://github.com/kiegroup/kie-tools/pull/1123
- https://github.com/kiegroup/kie-tools/pull/1237

All other PRs are related to SWF only.

The tickets of the first list can be cherrypicked as a 1:1 copy.
The tickets of the second list require integration with the editors, so the required effort is higher.

For this ticket scope, my proposal is to cherrypick the items of the first list only

**Comment by yesamer** [comment]
KOGITO-6974 - DONE
KOGITO-7736 - Discarded: Performance improvements are not significant in BPMN/DMN/SCESIM stream. Please check https://github.com/kiegroup/kie-tools/pull/1357 for further consideration.
