### ISSUE TITLE
Replace copyright headers/comments on `kogito-examples` as part of the migration to Apache

### ISSUE THREAD

**Issue by eduardocerqueira** [apache/incubator-kie-issues#470]
see https://github.com/kiegroup/kie-issues/issues/413#issuecomment-1684324059

**Comment by eduardocerqueira** [comment]
PR: https://github.com/kiegroup/kogito-examples/pull/1779

PS: I expect the checks will fail with the PR above, because it is using the checkstyle from kogito-runtimes https://github.com/kiegroup/kogito-runtimes/blob/main/kogito-build/kogito-build-no-bom-parent/pom.xml#L29 and it will require the new header from https://github.com/kiegroup/kogito-runtimes/pull/3207

**Comment by pefernan** [comment]
@eduardocerqueira PR already got merged into main, can we close this issue or should we keep it open until I send a PR to stable branch?

**Comment by pefernan** [comment]
Since the PR got merged and it cannot directly backported into `stable` (it would require upgrading headers in the whole `1.44`) I'd recommend closing the issue.

**Comment by elguardian** [comment]
closing this one
