### ISSUE TITLE
Replace copyright headers/comments on `kogito-docs` as part of the migration to Apache

### ISSUE THREAD

**Issue by eduardocerqueira** [apache/incubator-kie-issues#471]

**Comment by eduardocerqueira** [comment]
This project doesn't seem to have licenses in file headers. 


```
 grep -R -i "copyright"
```

**Comment by eduardocerqueira** [comment]
@porcelli ^ any thoughts on this?

**Comment by eduardocerqueira** [comment]
I am not seeing any string to be replaced on this project, IMO this project is good to go!

```
grep -R --exclude-dir=target -i -E "copyright|Red Hat"
```

**Comment by porcelli** [comment]
We don't need remove anything, great.

But we need add the Apache headers: https://www.apache.org/legal/src-headers.html#faq-docs

**Comment by jomarko** [comment]
Will be closed via https://github.com/apache/incubator-kie-kogito-docs/pull/512
