### ISSUE TITLE
Implement DMN 1.3 new keywords support

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#48]
We should be sure that 1.3 specific keywords and functions are supported by:
- autocompletion
- during save and reopen of diagram

See list of them
- https://issues.redhat.com/browse/DROOLS-5016
- https://blog.viadee.de/en/this-is-new-in-dmn-1_3

**Comment by yesamer** [comment]
It seems we already have part of the 1.3 new defined functions in autocompletion (https://www.omg.org/spec/DMN/1.3/PDF/changebar). Eg. all RANGES functions are present. I think we should check which functions are missing and eventually add them

**Comment by jomarko** [comment]
@yesamer please have alook on https://github.com/kiegroup/kie-tools/pull/1800 when you have a moment
