### ISSUE TITLE
Stunner: Scrolling outside the editing cell closes the Text Editor losing any change

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#49]
**Steps to reproduce**
- Open a new DMN file
- Add Decision node
- Add Literal expression (or Decision Table)
- Add 5 lines of text
- Scroll down outside the Literal Expression editing area (or outside the DecisionTable text box area)
#Unexpected: focus and last edited data are lost

**Expected behavior**
- Scrolling outside the editing area should not be losing data

https://issues.redhat.com/browse/KOGITO-5599

**Comment by jomarko** [comment]
@yesamer this is a duplicate of https://github.com/kiegroup/kie-issues/issues/45, could you please close one of them? Thank you.

**Comment by yesamer** [comment]
Closing this, thank you @jomarko

**Comment by yesamer** [comment]
Reopened with changed scope

**Comment by yesamer** [comment]
**Solution 1**
Google Spreadsheet behavior: The focused cell stays focused with a fixed position in the canvas

Boxed Expression (Stable)
https://user-images.githubusercontent.com/16005046/207842332-3b48ff22-25e8-4d22-8332-94cd7328728d.mov

I guess the current auto-closing was added to disable this feature. But, considering Google Spreadsheet behaves in that way, enabling it can be an interesting option

**Comment by yesamer** [comment]
**Solution 2**
Simply save any user change before closing and removing the editing Widget.

Implementing this second solution.
