### ISSUE TITLE
[Jakarta] kogito-apps: data-index: OracleIndexingServiceIT is failing

### ISSUE THREAD

**Issue by radtriste** [apache/incubator-kie-issues#496]
repo/branch: `kogito-apps:2.x`

Tests failing:
- [org.kie.kogito.index.service.OracleIndexingServiceIT.testProcessInstanceIndex](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito-2.x/job/2.x/job/nightly/job/kogito-apps.build-and-deploy/10/testReport/org.kie.kogito.index.service/OracleIndexingServiceIT/testProcessInstanceIndex/)
- [org.kie.kogito.index.service.OracleIndexingServiceIT.testJobIndex](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito-2.x/job/2.x/job/nightly/job/kogito-apps.build-and-deploy/10/testReport/org.kie.kogito.index.service/OracleIndexingServiceIT/testJobIndex/)
- [org.kie.kogito.index.service.OracleIndexingServiceIT.testUserTaskInstanceIndex](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito-2.x/job/2.x/job/nightly/job/kogito-apps.build-and-deploy/10/testReport/org.kie.kogito.index.service/OracleIndexingServiceIT/testUserTaskInstanceIndex/)

Error message:
```
Assertion condition defined as a org.kie.kogito.index.service.AbstractIndexingServiceIT 1 expectation failed.
JSON path data.ProcessInstances[0].id doesn't match.
Expected: is "67dcd0e1-97a9-4055-84f3-c655dc176112"
  Actual: null
 within 30 seconds.
```

Stacktrace:
```
HTTP/1.1 200 OK
content-type: application/json
content-length: 32

{
    "data": {
        "ProcessInstances": [
            
        ]
    }
}
```

Persistence problem ?

**Comment by yesamer** [comment]
@radtriste Is this ticket still valid, please?

**Comment by radtriste** [comment]
I guess not
