### ISSUE TITLE
[Jakarta] kogito-apps: SpringBootTrustyExplainabilityEnd2EndIT failing

### ISSUE THREAD

**Issue by radtriste** [apache/incubator-kie-issues#497]
repo/branch: `kogito-apps:2.x`

Tests failing:
- [org.kie.kogito.it.trusty.SpringBootTrustyExplainabilityEnd2EndIT.doTest](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito-2.x/job/2.x/job/nightly/job/kogito-apps.build-and-deploy/10/testReport/org.kie.kogito.it.trusty/SpringBootTrustyExplainabilityEnd2EndIT/doTest/)

Error message:
```
Container startup failed
```

Stacktrace:
No relevant stacktrace ...

**Comment by yesamer** [comment]
@radtriste Is this ticket still valid, please?

**Comment by radtriste** [comment]
I guess not
