### ISSUE TITLE
[Jakarta] kogito-apps: data index-oracle: UserTaskInstanceEntityQueryIT is failing

### ISSUE THREAD

**Issue by radtriste** [apache/incubator-kie-issues#498]
repo/branch: `kogito-apps:2.x`

Tests failing:
- [org.kie.kogito.index.oracle.query.UserTaskInstanceEntityQueryIT.testUserTaskInstanceQuery](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito-2.x/job/2.x/job/nightly/job/kogito-apps.build-and-deploy/10/testReport/org.kie.kogito.index.oracle.query/UserTaskInstanceEntityQueryIT/testUserTaskInstanceQuery/)

Error message:
```
Cannot invoke "java.sql.Blob.length()" because "json" is null
```

Stacktrace:
No relevant stacktrace

**Comment by yesamer** [comment]
@radtriste Is this ticket still valid, please?

**Comment by radtriste** [comment]
I guess not
