### ISSUE TITLE
Add tests for range conversion DMN function

### ISSUE THREAD

**Issue by baldimir** [apache/incubator-kie-issues#5]
In the DMN engine there is support for converting strings to ranges. Tests are missing for this functionality. 

- Tests added to the kie-dmn-feel test suite.
- All tests pass.
- There is no security vulnerability in the new code.
- Sonar PR checks pass on the new code.

**Comment by gitgabrio** [comment]
See [1.4 Spec](https://www.omg.org/spec/DMN/1.4/Beta1/PDF) - 10.3.4.7 Range Functions
