### ISSUE TITLE
Kogito Runtimes enforce Copyright with Checkstyle

### ISSUE THREAD

**Issue by porcelli** [apache/incubator-kie-issues#501]
https://github.com/kiegroup/kogito-runtimes/blob/12aa9d8d5590ecb9a246f14f890530e33fea708b/kogito-build/kogito-build-no-bom-parent/pom.xml#L27-L44

**Comment by eduardocerqueira** [comment]
thanks for reporting it, but I got it updated and tested in my branch, this change will be part of the PR 

https://github.com/eduardocerqueira/kogito-runtimes/blob/kie-issues-473/kogito-build/kogito-build-no-bom-parent/pom.xml#L49

**Comment by porcelli** [comment]
Checkstyle will be disabled!
