### ISSUE TITLE
Assess the impact of JBoss Parent dependency removal

### ISSUE THREAD

**Issue by porcelli** [apache/incubator-kie-issues#503]
The current runtime repositories seems to have a common root root parent that is the JBoss Parent:

https://github.com/kiegroup/drools/blob/main/pom.xml#L5C1-L11C12

How hard and what's the impact to remove such reference?

For reference this is the latest Apache parent pom: https://github.com/apache/maven-apache-parent/blob/apache-30/pom.xml

This is the current version of the JBoss Parent POM that Drools is using: https://github.com/jboss/jboss-parent-pom/blob/jboss-parent-36/pom.xml

**Comment by porcelli** [comment]
@mareknovotny @mdproctor @krisv @baldimir @ederign @LightGuard

**Comment by LightGuard** [comment]
From Gchat, it looked like someone was heading this up, or maybe just talking about it.

**Comment by LightGuard** [comment]
Looks like #511 has become a subtask of this

**Comment by baldimir** [comment]
The issue #511 moved to review, so moving this too.
