### ISSUE TITLE
DMN - Add a new "list replace" function

### ISSUE THREAD

**Issue by baldimir** [apache/incubator-kie-issues#507]
Add a new FEEL function "list replace". 

Two variants should be added: 
list replace(list, position, newItem) - replace item on specified position with newItem. 
list replace(list, match, newItem) - replace all items that match based on the match function with newItem. 

Examples: 
list replace( [2, 4, 7, 8], 3, 6) = [2, 4, 6, 8]
list replace ( [2, 4, 7, 8], function(item, newItem) item < newItem, 5) = [5, 5, 7, 8]

Acceptance criteria: 
- New function is implemented in the FEEL implementation. 
- Tests added that cover 100% of the new code. 
- No new security vulnerability introduced by the new code. 
- ~~Documentation added to the [DMN FEEL Handbook](https://kiegroup.github.io/dmn-feel-handbook/)~~ Addressed by [822](https://github.com/apache/incubator-kie-issues/issues/822)

**Comment by tiagobento** [comment]
@baldimir Is that from DMN 1.4 or DMN 1.5? We need to change something on the Tools side as well to enable it on auto-completion...

**Comment by baldimir** [comment]
It is 1.5.

**Comment by baldimir** [comment]
It is DMN 1.5.
