### ISSUE TITLE
Handle SLA timers during process instance migration

### ISSUE THREAD

**Issue by martinweiler** [apache/incubator-kie-issues#509]
After migrating a process instance, which has an active human task with a defined SLA Due Date, the SLA Compliance remains as "Pending" when the time expires.

To reproduce the problem, create a process model with a human task, put a value in the "SLA Due Date" field, save as V1. Edit the process model and save it as V2. Instantiate a process with V1, then migrate it from V1-->V2, the SLA Compliance does not change when the time expires.

Note: While this description is targeting human tasks, we should make sure that any SLA timers are handled correctly during the migration:

- Process SLA
- Node Instance SLA (including HT)

**Comment by elguardian** [comment]
PR: https://github.com/kiegroup/jbpm/pull/2323

**Comment by martinweiler** [comment]
Note that RH also opened JIRAs (including a PR) to address this:

- https://issues.redhat.com/browse/RHPAM-4773
- https://issues.redhat.com/browse/JBPM-10192
- https://github.com/kiegroup/jbpm/pull/2326
