### ISSUE TITLE
Migrate repositories from JBoss parent to Apache Parent

### ISSUE THREAD

**Issue by mareknovotny** [apache/incubator-kie-issues#511]
[JBoss Parent pom](https://github.com/jboss/jboss-parent-pom) is used to define global properties, plugins, and release configurations related to JBoss org projects.
We need to move to [Apache Parent](https://github.com/apache/maven-apache-parent/blob/master/pom.xml) for global configurations, plugins and add the differences to Kogito parent to achieve the same build environment.

**Comment by baldimir** [comment]
I am starting to work on this as this blocks deployment of artifacts to Apache Nexus, therefore it blocks CI builds. I will start first with Drools repository.

**Comment by baldimir** [comment]
PR for Drools: https://github.com/apache/incubator-kie-drools/pull/5530

**Comment by baldimir** [comment]
PR for kogito-runtimes: https://github.com/apache/incubator-kie-kogito-runtimes/pull/3232. I was not able to run all tests locally due to not having the proper setup for testcontainers on my Macbook with ARM. So if someone is able to execute tests over this PR, please do it.

**Comment by baldimir** [comment]
kogito-apps references kogito-runtimes parent. I was able to compile it locally succesfully, so it should be migrated when kogito-runtimes is merged to main.

**Comment by baldimir** [comment]
Drools PR is merged.

**Comment by baldimir** [comment]
OptaPlanner PR: https://github.com/apache/incubator-kie-optaplanner/pull/2992

**Comment by baldimir** [comment]
kie-benchmarks PR: https://github.com/apache/incubator-kie-benchmarks/pull/264

**Comment by baldimir** [comment]
When I search the Apache organization on GitHub for jboss-parent, there are no other mentions of jboss-parent than the repositories I created PRs for. So when reviewed and merged, this could be closed.

**Comment by baldimir** [comment]
PR with fixes for Drools: https://github.com/apache/incubator-kie-drools/pull/5541. There were some problems that showed up just in fullProfile builds, which is used in nightly jobs.

**Comment by baldimir** [comment]
All fixes should be done. What is left is to go through the review process and merges.

**Comment by baldimir** [comment]
kie-benchmarks PR merged.

**Comment by baldimir** [comment]
optaplanner PR merged.

**Comment by baldimir** [comment]
Kogito-runtimes PR merged. What is left open last is PR with fixes for the full build. It should get merged today too.

**Comment by baldimir** [comment]
Last PR merged.

**Comment by baldimir** [comment]
All of the PRs are merged, moving this to review.
