### ISSUE TITLE
Create apache_migration branch on relevant repositories

### ISSUE THREAD

**Issue by baldimir** [apache/incubator-kie-issues#514]
We need to create a specific branch based on main branch for changes related to apache CI migration. These changes are e.g. changes in the CI automation code, like replacing hardcoded Jenkins node labels etc. 

Acceptance criteria: 
- New branch `apache_migration` created on all repositories where there are changes needed for the CI automation code.

**Comment by radtriste** [comment]
Created branch for those repositories:
- kogito-pipelines
- kogito-runtimes
- kogito-aps
- kogito-examples
- kogito-images
- kogito-operator
- kogito-serverless-operator
- kogito-docs
- radtriste:kie-docs
- kie-tools
- drools
- drools-website
- radtriste:kie-benchmarks
- optaplanner
- optaplanner-quickstarts
- optaplanner-website

**Comment by radtriste** [comment]
@baldimir could you close this issue ?
