### ISSUE TITLE
List credentials / config files to export from Red Hat to Apache Jenkins

### ISSUE THREAD

**Issue by baldimir** [apache/incubator-kie-issues#516]
There are credentials, configuration files or other settings for the CI jobs that need to be exported from Red Hat to Apache Jenkins. These need to be listed. 

Acceptance criteria:
- List of credentials, configuration files and possible other settings exists in this issue.

**Comment by radtriste** [comment]
List will probably grow with testing

**Credentials**
- GH
  - `kie-ci`
  - `kie-ci3`
  - `kie-ci3-token`
  - `kie-ci4`
  - `kie-ci4-token`
  - `kie-ci5`
  - `kie-ci5-token`
- Quay
  - `optaplanner-quay-token`
  - `nightly_kogito` (should be merged with `release_kogito` as `kogito-quay-token`)
  - `release_kogito` (should be merged with `nightly_kogito` as `kogito-quay-token`)
- Zulip
  - `KOGITO_CI_EMAIL_TO` -> `KOGITO_CI_NOTIFICATION_EMAILS`
  - `OPTAPLANNER_CI_EMAIL` -> `OPTAPLANNER_CI_NOTIFICATION_EMAILS`
  - (to be created) `DROOLS_CI_NOTIFICATION_EMAILS`
- Cloud testing
  - `OPENSHIFT_API` (cloud testing)
  - `OPENSHIFT_REGISTRY`
- Docs/Website related
  - `drools-filemgmt`
  - `optaplanner-filemgmt`
  - `KogitoDocsUpload`

**Config files**
- Maven
  - `kogito_release_settings` (will need reconfiguration of mirror and repositories, npm information should be deleted unless we have a mirror registry for it) -> `kie-release-settings`
  - `kogito_pr_settings` (will need reconfiguration of mirror and repositories, npm information should be deleted unless we have a mirror registry for it) -> `kie-pr-settings`

**Comment by radtriste** [comment]
Credentials should be created/update into the `KIE` folder on Apache Jenkins

**Comment by baldimir** [comment]
@jstastny-cz could you please review if we need to list more? If not, we may close this.
