### ISSUE TITLE
Source-map-loader error screen appears running `examples/webapp` in `kie-tools`

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#517]
The `examples/webapp` module contains demo of standalone kie editors. The problem is demonstrated in the attached picture.
Often during interaction with the webapp the error screen appears. User can close it, but it appears again after some time.

### Steps to reproduce
- `pnpm bootstrap`
- `KIE_TOOLS_BUILD__buildExamples=true pnpm -F @kie-tools-examples/webapp... build:dev`
- `pnpm -F @kie-tools-examples/webapp start`
- access `localhost:9100` in browser

![Screenshot 2023-08-23 174530](https://github.com/kiegroup/kie-issues/assets/8044780/5508de28-d28c-484a-848f-ad773011944e)

### Steps to prevent from
We should run basic test, that will simple open examples webapp homepage and check no error screen appears, elements like menu items are present on the page.

The new tests preventing from this situation should be created as part of https://github.com/kiegroup/kie-issues/issues/457

**Comment by yesamer** [comment]
@jomarko It doesn't reproduce in my local with the current **main** version. Weird.
It's a bit slow, but never saw that compilation error.

**Comment by yesamer** [comment]
@jomarko Can you please double check if is still reproducible in your local?

**Comment by jomarko** [comment]
@yesamer I can confirm, the issue is not present on kie-tools `main` branch.

**Comment by yesamer** [comment]
Closing as no more reproducible.
