### ISSUE TITLE
Test Scenario Editor: Settings Dock

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#523]
Creating a new Component that manages the settings data of the scesim file. 
Rule and DMN data are different.

**DMN**

<img width="443" alt="Screenshot 2023-08-29 at 15 25 33" src="https://github.com/kiegroup/kie-issues/assets/16005046/269e458a-c535-4d83-81d9-1876edddf60a">

**RULE**
![Image](https://github.com/kiegroup/kie-issues/assets/16005046/9ab541c5-2c54-43db-ab16-fd3c8fef42e5)

**Comment by jomarko** [comment]
@yesamer hi, but that is expected that DRL and DMN settings are diferent, for example DRL, you want to specify ruleflow group, while for DMN you do not want, because it has not such property. What is this ticket aimed for please?

**Comment by yesamer** [comment]
@jomarko Yes exactly, the component will show different properties based on scesim type (DMN / RULE).
