### ISSUE TITLE
Fix @kogito-apps/form-details: The embedded monaco-editor doesn't show the proper syntax highlighting

### ISSUE THREAD

**Issue by pefernan** [apache/incubator-kie-issues#527]
Once you generate custom forms with the **form-generation-tool** they can be edited in the *Runtime Tools Quarkus Extension* allows editing them on the *@kogito-apps/form-details* component.

The component uses the monaco editor to allow the edition, but it it's missing the syntax highlighting. 

This could be an issue on how the extension is bundled.

Steps to Reproduce:

1. Generate any type of forms using *form-generation-tool* for any BPM Quarkus project in kogito-examples (for example [process-usertasks-quarkus-with-console](https://github.com/kiegroup/kogito-examples/tree/stable/kogito-quarkus-examples/process-usertasks-quarkus-with-console))
2. In the project `pom.xml` add a dependency to the `runtime-tools-quarkus-extension`
3. Start the Kogito project in dev mode (`mvn clean quarkus:dev`)
4. Open the Dev ui (`http://locahost:8080/q/dev`) and click on the *Forms* link inside the *Runtime Tools Quarkus Extension*
5. Once in the forms list, click in any form and you'll be brought to the *form-details* view, on the left side you'll se a monaco-editor. It will show up without any kind of syntax highlighting.

**Comment by jomarko** [comment]
![image](https://github.com/kiegroup/kie-issues/assets/8044780/b8f9ef9e-57f7-4dfb-aa34-60a351912bcc)

There is a lot of errors regarding loading `.woff2` assets. Error says for them 404 - not found on given url. One example of such url is:
- `http://localhost:9000/webapp/fonts/_/_/node_modules/.pnpm/@patternfly+react-core@4.276.8_react-dom@17.0.2_react@17.0.2/node_modules/@patternfly/react-core/dist/styles/assets/fonts/RedHatDisplay/RedHatDisplay-Bold.woff2`

Then when I do `grep` for that file in `kogito-apps/ui-packages` I get multiple matches, but these two seems to be as most similar path:
- `./dist/resources/webapp/_/_/node_modules/.pnpm/@patternfly+react-core@4.276.8_react-dom@17.0.2_react@17.0.2/node_modules/@patternfly/react-core/dist/styles/assets/fonts/RedHatDisplay/RedHatDisplay-Bold.woff2`
- `./dist/fonts/_/_/node_modules/.pnpm/@patternfly+react-core@4.276.8_react-dom@17.0.2_react@17.0.2/node_modules/@patternfly/react-core/dist/styles/assets/fonts/RedHatDisplay/RedHatDisplay-Bold.woff2`
