### ISSUE TITLE
On nested Decision tables the input and output columns are not set by the parent expression

### ISSUE THREAD

**Issue by ljmotta** [apache/incubator-kie-issues#536]
Currently, nested Decision tables doesn't correctly create the inputs and outputs columns. e.g. on a Boxed Context with a Decision table as a result should load all context entries as input and its output should be the decision name.

## Video
The following video shows what is happening and is the expected behavior:
https://github.com/kiegroup/kie-issues/assets/24302289/0cb120c1-8f35-4f83-a6f2-b13eaa0ad46d

**Comment by tiagobento** [comment]
Probably fixed on https://github.com/apache/incubator-kie-issues/issues/455. Can you please check?

**Comment by ljmotta** [comment]
Yes, it was solved on this issue.
