### ISSUE TITLE
In the Boxed Expression Editor, the context menu shows wrong options

### ISSUE THREAD

**Issue by danielzhe** [apache/incubator-kie-issues#537]
In the Boxed Expression Editor, when a cell that is not part of column index is selected in Decision Table expression (or other expressions that have row count) and user right-clicks in one of the cells in the row index column it have erratic behavior:

1. If user clicks in the index column in the same line, the displayed options are not the correct options;
2. If user clicks in the index column in another line, the context menu shows wrong height;

See the video bellow for more clarification:
 
https://github.com/kiegroup/kie-issues/assets/7305741/91e66eaf-4fc7-4955-94ce-c9a339a48361

```[tasklist]
### Acceptance Criteria
- [ ] When user have multiple cells selected, the context menu must show valid options for that selection
- [ ] When user have multiple OR single cells selected and clicks outside that selection, the context menu must show valid options for the new selection
```

**Comment by ljmotta** [comment]
@danielzhe It's duplicated from https://github.com/kiegroup/kie-issues/issues/420
