### ISSUE TITLE
Colorize imported nodes names in FEEL inputs on DMN Editor's Boxed Expression Editor

### ISSUE THREAD

**Issue by danielzhe** [apache/incubator-kie-issues#539]
This ticket is part of https://github.com/kiegroup/kie-issues/issues/159

Imported nodes are note being colorized in DMN Editor's Boxed Expression Editor as reported in [this comment](https://github.com/kiegroup/kie-tools/pull/1869#pullrequestreview-1594899731).

Steps to reproduce:
1. Include some model in the DMN editor
2. Add some of the included nodes in the diagram
3. Add a new Decision Node in the diagram
4. Connect the included node to the new Decision Node
5. Open the Boxed Expression Editor for the new Decision Node
6. Add the included node name in an expression
7. The included node name inside the expression should be correct colorized (dark orange, not red)

```[tasklist]
### Acceptance Criteria
- [ ] Imported node names should be colorized with dark orange color in Boxed Expression Editor
- [ ] Unknown imported node names should be colorized with red
- [ ] Not-connected imported node names should be colorized with red
```

**Comment by tiagobento** [comment]
This issue will be addressed on the `tiagobento/kie-tools:dmn-editor` branch. It will be available in `main` once #439 is completed.
