### ISSUE TITLE
Update jpmml version

### ISSUE THREAD

**Issue by gitgabrio** [apache/incubator-kie-issues#56]
Quarkus is moving from javax libraries to jakarta ones. To keep in sync, jpmml libraries (especially jpmml-model) have to be upgraded to 1.6.4, but this breaks the kie-pmml-trusty compilation (and probably other pieces of code).

Update JPMML version and adapt client code on top of quarkus3_jakarta branch.
Keep track of modification (patch ?) to easily create an OpenRewrite recipe later.

**Comment by baldimir** [comment]
This is a blocker that blocks the Quarkus 3 update.

**Comment by porcelli** [comment]
food for thought: some projects like Hibernate took the path to automate such changes and included it as part of the build

**Comment by gitgabrio** [comment]
For the moment begin, there is the following issue:

1. current code is based on jpmml 1.5.1
2. jpmml 1.6.0 introduced API changes that makes the current code uncompatible
3. switch to jakarta requires jpmml => 1.6.0
4. migrating trusty-pmml code to new jpmml requires that code modification for new API and drools repository switch to jakarta happen atomically

Two possible solutions could be

1.  have to branches of drools, one "javax" and the other "jakarta", and adapt code only on the latter (for the moment being, keeping in sync the two, fro pmml, should not be a big issue)
2. write an OpenRewrite recipe that adapt pmml code to new jpmml API, so that it can be applied, together with the javax -> jakarta one, whenever is needed.

 The former could be easier, but it would depend on a commonly agreed-upon decision to follow such strategy for the future. The latter would be more challenging, but it could be applied on the current situation.

For the moment being, this ticket is in stand-by

**Comment by baldimir** [comment]
Moving this back to Backlog as it is not ready to be worked on until we have a decision about how we want to handle the javax to jakarta namespace change.

**Comment by gitgabrio** [comment]
Start working following  agreement at https://chat.google.com/room/AAAAhh5e2m4?cls=1
