### ISSUE TITLE
replace copyrights headers/comments in `kie-sandbox-quarkus-accelerator`

### ISSUE THREAD

**Issue by eduardocerqueira** [apache/incubator-kie-issues#571]

**Comment by kbowers-ibm** [comment]
https://github.com/kiegroup/kie-sandbox-quarkus-accelerator
I believe this can be moved to done, as it only consists of a LICENSE (which is in the correct Apache format already) and a readme file

**Comment by kbowers-ibm** [comment]
Main only consists of a License and a readme, so no headers are required and only a NOTICE should be needed  
Repo: https://github.com/kiegroup/kie-sandbox-quarkus-accelerator
Closed by PRs to the following branches:
Main: https://github.com/kiegroup/kie-sandbox-quarkus-accelerator/pull/4
0.0.0: https://github.com/kiegroup/kie-sandbox-quarkus-accelerator/pull/5
template: https://github.com/kiegroup/kie-sandbox-quarkus-accelerator/pull/6

**Comment by yesamer** [comment]
Repo checked + PR approved. 
@LightGuard can you please review them?

**Comment by yesamer** [comment]
Task completed, thank you @kbowers-ibm !
