### ISSUE TITLE
replace copyrights headers/comments in `kogito-online-staging`

### ISSUE THREAD

**Issue by eduardocerqueira** [apache/incubator-kie-issues#572]

**Comment by jomarko** [comment]
I can not find such repository in apache org:
https://github.com/apache?q=kogito-online-staging&type=all&language=&sort=

should we close this ticket?

**Comment by kbowers-ibm** [comment]
Will be moved to Apache as part of https://github.com/apache/incubator-kie-issues/issues/428
Repo still located with kiegroup for now: https://github.com/kiegroup/kogito-online-staging

**Comment by kbowers-ibm** [comment]
Closed by https://github.com/kiegroup/kogito-online-staging/pull/1
