### ISSUE TITLE
replace copyrights headers/comments in `kogito-online`

### ISSUE THREAD

**Issue by eduardocerqueira** [apache/incubator-kie-issues#573]

**Comment by kbowers-ibm** [comment]
https://github.com/kiegroup/kogito-online
I believe this can be moved to done, as it only consists of a LICENSE (which is in the correct Apache format already) and a readme file

**Comment by kbowers-ibm** [comment]
Main only consists of a License and a readme, so no headers are required and only a NOTICE should be needed.
Repo: https://github.com/kiegroup/kogito-online.
Closed by PRs to the following branches:
Main: https://github.com/kiegroup/kogito-online/pull/13
Chrome-Extension-Resources: https://github.com/kiegroup/kogito-online/pull/15
Chrome-Extension-Resources-0.2.0: https://github.com/kiegroup/kogito-online/pull/17
gh-pages: https://github.com/kiegroup/kogito-online/pull/18
