### ISSUE TITLE
Initial ASF Jenkins CI setup

### ISSUE THREAD

**Issue by jstastny-cz** [apache/incubator-kie-issues#574]
Following the repository migration we need to set up CI.

Adapt jenkins pipelines based on kogito-pipelines framework to ASF jenkins instance.

The primary goal is to have:
* PR checks
* Nightly builds
working.

Non-mandatory things will be delayed and tracked separately, e.g.
* environment PR checks
* nexus deploy of nightly artifacts
* ...

**Comment by jstastny-cz** [comment]
apache_migration branches prepared, job generation tested for the branch.

Problem with running PR checks on other than main branch will be for now ignored and hopefully things settle down once in main, will hotfix on main if needed (pipelines expect one script to reside in main branch, but the file is being added as part of the effort, so is not yet there).

**Comment by eduardocerqueira** [comment]
Closing this ticket as at this current moment the "initial" setup for KIE projects running on ASF Jenkins has been achieved and most of projects have been migrated as we can follow on the link https://ci-builds.apache.org/job/KIE/

The team continue working on improving the stability for pipelines and applying enhancement to each project as needed.
