### ISSUE TITLE
Data Audit app for kogito

### ISSUE THREAD

**Issue by elguardian** [apache/incubator-kie-issues#576]
1) store raw events
2) provide a graphql API to retrieve information
3) provide some sort of dynamic queries to retrieve custom information from the database.
4) embedded mode & service

https://github.com/apache/incubator-kie-kogito-apps/pull/1905
https://github.com/apache/incubator-kie-drools/pull/5571
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3267

**Comment by doogle-oss** [comment]
This will be the best thing for all. We currently do custom auditing from the data index domain changes in mongodb. A native support will be be great.

**Comment by elguardian** [comment]
@debu999 the idea is to have something something like we have in RHPAM 7/jbpm v7... but bit enhaced with graphQL

**Comment by elguardian** [comment]
Under testing.
https://github.com/apache/incubator-kie-kogito-apps/pull/1905
https://github.com/apache/incubator-kie-drools/pull/5571
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3267

**Comment by elguardian** [comment]
done
