### ISSUE TITLE
PIM fails to handle timers when "org.jbpm.timer.disableUnmarshallerRegistration" is set to true

### ISSUE THREAD

**Issue by martinweiler** [apache/incubator-kie-issues#597]
We are setting -Dorg.jbpm.timer.disableUnmarshallerRegistration=true in order to prevent duplicate timer creation in a multi-node environment. However, this leads to problems with timers during process instance migration. Timers fail to get migrated correctly and once the timers are triggered after the migration, the execution fails with a org.kie.internal.runtime.manager.SessionNotFoundException.

We need a solution that works with PIM and guaranteed correct timer handling in multi-node setup (no duplicates).

**Comment by elguardian** [comment]
@martinweiler do we have a stacktrace of what is happening here ?

**Comment by elguardian** [comment]
* checked that during migration the old timer mapping info row is removed.
* flag -Dorg.jbpm.timer.disableUnmarshallerRegistration=true that causes problems during ejb timers should be considered obsolete as timer info should have the means to restore the info field without doing the loop just quering the TimerMappingInfo in a multinode env. In the past this was not happening because we were relying on the ejb database implementation of wildfly that refreshes every x seconds.

**Comment by elguardian** [comment]
OK. I have a possible explanation for this.

https://github.com/kiegroup/jbpm/blob/main/jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/migration/MigrationManager.java#L693-L698

This code requires that the timers are being registered in memory as this flag is set -Dorg.jbpm.timer.disableUnmarshallerRegistration=true the migration process does not load the timers in the system that is being used cause the timer map not being found in the node and therefore not being canceled. As the rest of the system is being migrated the timers fires in the old container causing the session not found.

Funny enough we should see some warnings in the report. What I need to understand is 2 things.
1. The flag was set before the TimerMappingInfo table or not
2. that flag should not be needed. this is not logged but the outcome of hte migration report.

**Comment by elguardian** [comment]
The suggestion should remove the flag org.jbpm.timer.disableUnmarshallerRegistration=true as this should not be needed anymore with the TimerMappingInfo

**Comment by elguardian** [comment]
https://github.com/apache/incubator-kie-drools/pull/5547
https://github.com/kiegroup/jbpm/pull/2346

**Comment by elguardian** [comment]
closing this one as not fix.
