### ISSUE TITLE
EPIC - Migrate kie-tools GH actions to Apache Jenkins

### ISSUE THREAD

**Issue by eduardocerqueira** [apache/incubator-kie-issues#605]
- [x] #606 
- [x] #607 
- [x] #608 
- [x] #609 
- [x] #610 
- [x] #611 
- [x] #612 
- [x] #613 
- [x] #614 
- [x] #615 
- [x] #616 
- [x] #617 
- [x] #618 
- [x] #619 
- [x] #620 
- [x] #621 
- [x] build and tests on multiple OS (macOS, Windows)
- [x] #704

**Comment by tiagobento** [comment]
As discussed today, 
- https://github.com/apache/incubator-kie-issues/issues/611; and
- https://github.com/apache/incubator-kie-issues/issues/613

are not necessary.
