### ISSUE TITLE
Migrate `kie-tools`/ci_build.yml GH workflow to Apache Jenkins

### ISSUE THREAD

**Issue by rodrigonull** [apache/incubator-kie-issues#607]
Migrate kie-tools ci build GH workflow to a Jenkins job that will run on Apache Jenkins
https://github.com/apache/incubator-kie-tools-temporary-rnd-do-not-use/blob/main/.github/workflows/ci_build.yml

**Comment by rodrigonull** [comment]
Problems I've identified so far in this migration:

1.  Some packages that have e2e tests using selenium / cypress and google chrome are failing. I'm still investigating the root cause.
2. Unable to archive the build artifacts and consolidate the junit files. The Jenkins node is running out of memory causing the build to fail. I believe the issue is caused due to the amount of files in the workspace. I'm still investigating a possible to solution for this problem.

**Comment by rodrigonull** [comment]
I finally get the full build working with all tests passing in our internal Jenkins and now I'm dealing with some timeout issues that I have been facing when running the build e2e tests on ASF Jenkins. I should be able to fix all these issues in the next few days.

I also was able to fix the out of memory issue we had and now the test reports on Jenkins are working fine.

**Comment by eduardocerqueira** [comment]
As previously discussed all PR related to GH Actions -> Jenkins (as this one) opened to https://github.com/apache/incubator-kie-tools-temporary-rnd-do-not-use are GOOD to be integrated as it is a temporary repository. 

Track at #704
