### ISSUE TITLE
Migrate `kie-tools`/ci_check_code_formatting.yml GH workflow to Apache Jenkins

### ISSUE THREAD

**Issue by rodrigonull** [apache/incubator-kie-issues#608]

**Comment by rodrigonull** [comment]
Job is created on ASF Jenkins: https://ci-builds.apache.org/blue/organizations/jenkins/KIE%2Fkie-tools%2Fkie-tools-ci-check-code-formatting.

First successful run: https://ci-builds.apache.org/blue/organizations/jenkins/KIE%2Fkie-tools%2Fkie-tools-ci-check-code-formatting/detail/PR-7/2/pipeline

![Image](https://github.com/apache/incubator-kie-issues/assets/3134877/149b8d6c-f242-466c-912f-aadcaa5834b6)

**Comment by jomarko** [comment]
Hi @rodrigonull , ill we do the same for `kogito-apps` react codebase?

**Comment by rodrigonull** [comment]
Hi @jomarko, I believe we are going to move all the GitHub workflows we have in each project. I was looking at kogito-apps repo and it doesn’t have a code formatting workflow, so I don’t think we are going to add this kind of job to kogito-apps as part of the migration. Am I right @eduardocerqueira?

**Comment by jomarko** [comment]
Yes but we have a pre-commit hook that does formatting, I wonder if we want to use two different approaches for automatic formatting

https://github.com/apache/incubator-kie-kogito-apps/blob/main/ui-packages/package.json#L56

**Comment by eduardocerqueira** [comment]
As previously discussed all PR related to GH Actions -> Jenkins (as this one) opened to https://github.com/apache/incubator-kie-tools-temporary-rnd-do-not-use are GOOD to be integrated as it is a temporary repository. 

Track at #704
