### ISSUE TITLE
Migrate `kie-tools`/ci_check_dependencies_consistency.yaml GH workflow to Apache Jenkins

### ISSUE THREAD

**Issue by rodrigonull** [apache/incubator-kie-issues#609]

**Comment by rodrigonull** [comment]
The job is created on Jenkins https://ci-builds.apache.org/job/KIE/job/kie-tools/job/kie-tools-ci-check-dependencies-consistency/view/change-requests/job/PR-8/1/ and it's running as part of PR Check jobs.

**Comment by eduardocerqueira** [comment]
As previously discussed all PR related to GH Actions -> Jenkins (as this one) opened to https://github.com/apache/incubator-kie-tools-temporary-rnd-do-not-use are GOOD to be integrated as it is a temporary repository. 

Track at #704
