### ISSUE TITLE
Migrate `kie-tools`/ci_codeql.yml GH workflow to Apache Jenkins

### ISSUE THREAD

**Issue by rodrigonull** [apache/incubator-kie-issues#610]

**Comment by rodrigonull** [comment]
The job is created on ASF Jenkins and it's generating the reports for go and javascript: https://ci-builds.apache.org/job/KIE/job/kie-tools/job/kie-tools-ci-codeql/view/change-requests/job/PR-9/5/

Still need to discuss the need of uploading the sarif report files to github.

**Comment by eduardocerqueira** [comment]
As previously discussed all PR related to GH Actions -> Jenkins (as this one) opened to https://github.com/apache/incubator-kie-tools-temporary-rnd-do-not-use are GOOD to be integrated as it is a temporary repository. 

Track at #704
