### ISSUE TITLE
EPIC - Release snapshots to Apache Nexus

### ISSUE THREAD

**Issue by baldimir** [apache/incubator-kie-issues#628]
We need to start releasing snapshot Maven artifacts to Apache Nexus instead of JBoss Nexus. 
Documentation is here: https://infra.apache.org/publishing-maven-artifacts.html

Acceptance criteria: 
- Access granted to publish artifacts to https://repository.apache.org/
- Successful nightly builds from main branch publish SNAPSHOT artifacts to the Apache Nexus. 
- No new SNAPSHOT artifacts are published to JBoss Nexus. 

- [ ] https://github.com/apache/incubator-kie-issues/issues/705

**Comment by baldimir** [comment]
INFRA ticket created to get access to the Apache Nexus repository: https://issues.apache.org/jira/browse/INFRA-25077.

**Comment by baldimir** [comment]
Drools PR with switch to Apache Nexus https://github.com/apache/incubator-kie-drools/pull/5553.

**Comment by baldimir** [comment]
kogito-runtimes PR with switch to Apache Nexus https://github.com/apache/incubator-kie-kogito-runtimes/pull/3251

**Comment by baldimir** [comment]
kogito-apps PR with switch to Apache Nexus https://github.com/apache/incubator-kie-kogito-apps/pull/1896.

**Comment by baldimir** [comment]
optaplanner PR with switch to Apache Nexus https://github.com/apache/incubator-kie-optaplanner/pull/3001.

**Comment by baldimir** [comment]
serverless-operator PR https://github.com/apache/incubator-kie-kogito-serverless-operator/pull/279

**Comment by baldimir** [comment]
kie-kogito-operator PR https://github.com/apache/incubator-kie-kogito-operator/pull/1532

**Comment by baldimir** [comment]
kogito-images PR https://github.com/apache/incubator-kie-kogito-images/pull/1705

**Comment by baldimir** [comment]
kogito-benchmarks PR https://github.com/apache/incubator-kie-kogito-benchmarks/pull/17

**Comment by baldimir** [comment]
kogito-pipelines PR https://github.com/apache/incubator-kie-kogito-pipelines/pull/1109

**Comment by baldimir** [comment]
All PRs merged, except the last one waiting for review: https://github.com/apache/incubator-kie-kogito-images/pull/1705

**Comment by tiagobento** [comment]
@baldimir Is this one done?
