### ISSUE TITLE
Addition, substraction, multiplication, division and exponantiation is not defined for combining number and string (e.g. 10 + "10")

### ISSUE THREAD

**Issue by baldimir** [apache/incubator-kie-issues#63]
Based on the Table 57: Specific semantics of addition and subtraction of DMN specification, Table 59: Specific semantics of multiplication and division and Table 60: Semantics of exponentiation, there is not defined a use case for coercing string to number in an addition, substraction, multiplication, division or exponentiation, like `10 + "10"`. Drools DMN engine currently allows this. 

Possible test classes that can be updated with the new test cases (all combinations of possible operations) are [FEELMathOperationsTest](https://github.com/kiegroup/drools/blob/68d53f553a34aec53b7ee664a9b22d82a6313ca7/kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/FEELMathOperationsTest.java) or [FeelStringOperationsTest](https://github.com/kiegroup/drools/blob/12e82a0a9a7555ae073129d47eb79200c47b6556/kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/FEELStringOperationsTest.java)

Example code that is handling the operations can be found in [InfixOpNode](https://github.com/kiegroup/drools/blob/8415835b975edd3424280ca399b33796be3f8f0b/kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/InfixOpNode.java). There may be other classes that needs changing. 

Acceptance criteria: 
- Addition, substraction, multiplication, division and exponentiation returns null for use cases where a number and a string is used. 
- New code has 100% code coverage.

**Comment by baldimir** [comment]
Mentioning @tarilabs, so Matteo knows about this.

**Comment by gitgabrio** [comment]
Hi @baldimir 
Is there a reproducer for that ?
I launched and debugged `DMNInputRuntimeTest.testInputNumberEvaluateAll` replacing the BigDecimal with a String, but it fails because the value is not a allowed. Beside, debugging code I found that `EvalHelper` returns null if a String is received instad of a number. Could you point to relevant code/test ?

**Comment by baldimir** [comment]
I updated the description.
