### ISSUE TITLE
KIE Tools `Publish jitexecutor-native` job is failing due to path names being too long on Windows

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#630]
See https://github.com/kiegroup/kie-tools/actions/runs/6483771203

This problem started on `kogito-apps` 1.44.0.Final, and so far 1.44.1.Final has the same problem.

We should try and configure our GitHub Actions workflow to allow for these longer paths. 

Maybe doing `git config --system core.longpaths true` is enough, but further investigation is necessary....

**Comment by yesamer** [comment]
I guess using `git config --system core.longpaths true` should be enough, let's see

**Comment by yesamer** [comment]
Oppps, it's already there https://github.com/kiegroup/kie-tools/blob/7aa885b73950d6ec79d2c44d200aa4a0ba2a52c4/.github/workflows/publish_jitexecutor_native.yml#L46
