### ISSUE TITLE
Quarkus 3 Migration: fix patches after the headers update

### ISSUE THREAD

**Issue by pefernan** [apache/incubator-kie-issues#631]
After the new Apache headers update, some of the patc files for the quarkus-3 should be fixed.

Affected modules so far are:

- drools
- kogito-runtimes
- kogito-apps
- kogito-examples

**Comment by porcelli** [comment]
Depends on https://github.com/apache/incubator-kie-issues/issues/699

**Comment by pefernan** [comment]
Merged!
