### ISSUE TITLE
Bump up `kogito-runtimes` dependency to `1.45.0.Final` in kie-tools

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#634]
During investigation of apache/incubator-kie-issues#270 we found out an issue in `drools` codebase that we addressed as https://github.com/apache/incubator-kie-drools/pull/5461

Similar fix for kie-tools implemented in its dependencies points to need of dependencies bump. To be more precise, we need to bump up `kogito-runtimes` and `kogito-apps` dependencies of kie-tools.

**Currently**
- [1] kie-tools depends on kogito-runtimes  or kogtio-apps  version 1.44.1.Final  see https://github.com/kiegroup/kie-tools/blob/main/packages/root-env/env/index.js#L57-L59
- [2] kogito-runtimes / kogito-apps   1.44.1.Final  depend on drools  version 8.44.0.Final  see https://github.com/apache/incubator-kie-kogito-runtimes/blob/1.44.1.Final/kogito-build/kogito-kie-bom/pom.xml#L21

However the `drools` fix will be delivered in `8.45.0.Final`. So we need to ensure transitive dependencies of kie-tools points to drools 8.45.0.Final and higher.

**After the fix**
- [1] should be bumped to `1.45.0.Final` or higher
- [2] should be bumped to `8.45.0.Final` or higher

_Originally posted by @jomarko in https://github.com/apache/incubator-kie-issues/issues/270#issuecomment-1757002297_

**Comment by tiagobento** [comment]
I'm closing this one as we're moving with the latest timestamped SNAPSHOT at #967
