### ISSUE TITLE
DMN Monaco highlighting throws error when used with DMN Runner

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#636]
Bellow we can see the issue that appears tot he user.
![Screenshot 2023-10-19 060406](https://github.com/apache/incubator-kie-issues/assets/8044780/55cae25c-7fd0-4d2b-9d59-6d2f14a01722)

Maybe related to the https://github.com/apache/incubator-kie-issues/issues/159

### Steps to reproduce
- Create a simple DMN model: (InputData-1) -> (Decision-1) [1]
- Open the Decision-1
- Start typing InputData-1, it will be red in the beginning [2], then red is gone [3]
- Confirm changes with Enter
- Open DMN Runner panel
- Start to type into InputData-1 field, error will appear

[1]
![Screenshot 2023-10-19 062951](https://github.com/apache/incubator-kie-issues/assets/8044780/89651d54-188e-4455-afb7-6b16d3b089fb)

[2]
![Screenshot 2023-10-19 063432](https://github.com/apache/incubator-kie-issues/assets/8044780/8864131c-6d2c-4d19-a721-d47518b9d74f)

[3]
![Screenshot 2023-10-19 063442](https://github.com/apache/incubator-kie-issues/assets/8044780/a1a824ea-11c9-45c9-a562-f91584b29d46)

**Comment by yesamer** [comment]
<img width="1529" alt="Screenshot 2023-10-19 at 10 28 08" src="https://github.com/apache/incubator-kie-issues/assets/16005046/7c9c5bb6-1fad-40d5-826a-376a0434f4fc">


It seems a monaco-editor related issue ---> https://github.com/microsoft/monaco-editor/issues/4213 

The overlay error panel appears in the devServer only, so I propose to close this ticket

**Comment by tiagobento** [comment]
Hmmm...... IDK... From the logs, seems like we're trying to send a key stroke to the Envelope using the channelKeyboardEvent mechanism. It's weird because I think our keyboard shortcuts subsystem should be ignoring inputs coming from input texts... Might be worth a deeper investigation before we close it.

**Comment by tiagobento** [comment]
@jomarko @danielzhe Did this start to happen recently? Is that somehow possibly related to this? 
- #159

**Comment by danielzhe** [comment]
I'm investigating.
