### ISSUE TITLE
String substraction, multiplication, division and exponentiation is undefined by the DMN spec

### ISSUE THREAD

**Issue by baldimir** [apache/incubator-kie-issues#64]
When having a case of substracting, multipliying, dividing or exponentiating two strings, it is undefined in the spec Table 57: Specific semantics of addition and subtraction, Table 59: Specific semantics of multiplication and division or Table 60: Semantics of exponentiation. However it works when using two strings containing numbers in the Drools DMN engine. 

Possible test classes that can be updated with the new test cases (all combinations of possible operations) are [FEELMathOperationsTest](https://github.com/kiegroup/drools/blob/68d53f553a34aec53b7ee664a9b22d82a6313ca7/kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/FEELMathOperationsTest.java) or [FeelStringOperationsTest](https://github.com/kiegroup/drools/blob/12e82a0a9a7555ae073129d47eb79200c47b6556/kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/FEELStringOperationsTest.java)

Example code that is handling the operations can be found in [InfixOpNode](https://github.com/kiegroup/drools/blob/8415835b975edd3424280ca399b33796be3f8f0b/kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/InfixOpNode.java). There may be other classes that needs changing. 

Acceptance criteria: 
- Substracting, multipliying, dividing and exponentiating two strings returns null. 
- New code and this use case has 100% code coverage.

**Comment by baldimir** [comment]
Mentioning @tarilabs, so he knows about this. It is also related to the coercion like #63 .

**Comment by gitgabrio** [comment]
I think this is a subcase of kie-issues#63: since passing a string as one parameter of math operation lead to "null" return, implicitily passing both parameters as string should already been managed. 
The "add" is managed differently, since with two strings the code executes a concatenation.

**Comment by baldimir** [comment]
Yes, makes sense. It can be checked by running `mvn clean install -P dmn-tck` from the `kie-dmn-tck` module. That runs the TCK suite. I merged new test cases there recently testing this (+ other arithmetic cases that will still be failing and should be fixed part of other DMN bugs I filed). If it is fixed, we need to at least add some test cases for that as part of this ticket. What do you think please?

**Comment by gitgabrio** [comment]
Agree - only adding test cases should be needed. I would add some on the `FEELMathOperationsTest`.
As a side note, I think that that class should not rely so much on hardcoded stuff: it is hard to maintain/adapt on one side, and on the other side such pre-defined cases may miss corner cases

**Comment by baldimir** [comment]
Tests submitted for review.
