### ISSUE TITLE
Timers not removed from session and TimerMappingInfo when jobHandle is not found

### ISSUE THREAD

**Issue by martinweiler** [apache/incubator-kie-issues#645]
If a jobHandle is not found in the session, the engine only emits a [log message](https://github.com/kiegroup/jbpm/blob/main/jbpm-flow/src/main/java/org/jbpm/process/core/timer/impl/GlobalTimerService.java#L162), but does not remove the job from the session. This leads to orphaned records in the TimerMappingInfo table and can also lead to a duplicate timer getting created in certain circumstances (eg. async nodes).

**Comment by martinweiler** [comment]
Related PR: https://github.com/kiegroup/jbpm/pull/2348

**Comment by elguardian** [comment]
https://github.com/kiegroup/jbpm/pull/2348

**Comment by martinweiler** [comment]
Related JIRA: [RHPAM-4835](https://issues.redhat.com/browse/RHPAM-4835)

**Comment by elguardian** [comment]
merged
