### ISSUE TITLE
Duplicate timer created for Task SLA Due date with AsyncMode env setting

### ISSUE THREAD

**Issue by martinweiler** [apache/incubator-kie-issues#646]
Executing a process that contains a Task with an SLA Due date is resulting in a duplicate timer creation with the following setting in kie-deployment-descriptor.xml:
```
        <environment-entry>
            <resolver>mvel</resolver>
            <identifier>new String ("true")</identifier>
            <parameters/>
            <name>AsyncMode</name>
        </environment-entry>
```
Note this will not have any functional impact on the process execution, but adds additional overhead to the timer subsystem.

Run the attached example and monitor the timers created in the database.
[timer-test.zip](https://github.com/apache/incubator-kie-issues/files/13078485/timer-test.zip)

**Comment by elguardian** [comment]
[ENG NOTE] 
JMS is load balancing to other member the execution. During unmarshalling might cause this problem.

https://github.com/kiegroup/jbpm/pull/2355
https://github.com/kiegroup/jbpm/pull/2352

**Comment by martinweiler** [comment]
Related JIRA: [RHPAM-4836](https://issues.redhat.com/browse/RHPAM-4836)

**Comment by elguardian** [comment]
closing this one. as related work is being done.
