### ISSUE TITLE
Document Dev deployments and its requirements on KIE Sandbox

### ISSUE THREAD

**Issue by thiagoelg** [apache/incubator-kie-issues#652]
Describe how Dev deployments work, listing our base and kogito pre-configures images using dev-deployment-upload-service.
Describe how Kubernetes resources are created and managed by KIE Sandbox (including how they are tagged/labeled).
Also, list the limitations and requirements for a successful custom deployment configuration.

**Comment by jstastny-cz** [comment]
This should not block the productization Epic, removing, please make sure it appears in the boards you'd like.
