### ISSUE TITLE
`xml-parser-ts` Doesn't manage Complex Types with Simple Content

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#665]
`xml-parser-ts` it's not able to manage Complex Types with Simple Content, please consider the following example:

**XML**
`<rawValue class="string">Above speed limit: 10km/h and 30 km/h</rawValue>`

**XSD** 
```
<xsd:complexType name="rawValueType">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute type="xsd:string" name="class" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
```

**Current generated type:**
```
export type SceSim__rawValueType =   {

}

```
Fields are missing

**At Runtime:**
```
rawValue: 
@_class: "string"
```
Only the attribute is correctly parsed

**Comment by tiagobento** [comment]
Right, right. Good catch. I don't think DMN nor BPMN have this use-case, but yeah, indeed a flaw on `xml-parser-ts` that needs to be addressed. We'll have to introduce a convention for this, which I'm not a big fan of, but I don't see any other way. Text content will have to be given its own attribute (always), and we'll need to add special treatment for it on the `build` function of `xml-parser-ts` too.

In the example you share, we'll need to generate a type

```ts
export type SceSim__rawValueType = {
  "__$$text": string;
  "@_class": string;
}
```

Note that `__$$text` follows the same absurdity as the `__$$element` property we already have for resolving substitution groups. 

This is not a very complicated change, but definitely will impact everyone using `xml-parser-ts` right now, as it will introduce breaking changes, for example, to `typeRef`s on DMN.

@yesamer How urgent is this for 
- #453 

?
