### ISSUE TITLE
Substracting two date and time types, both need to have or cannot have a timezone defined

### ISSUE THREAD

**Issue by baldimir** [apache/incubator-kie-issues#67]
Defined in Table 57: Specific semantics of addition and subtraction in the DMN specification, when substracting two values of type `date and time`, it requires either both values to have a timezone or both not to have a timezone. Subtraction is undefined for the case where only one of the values has a timezone.

Acceptance criteria: 
- When one of the `date and time` values in substraction has a timezone and the other doesn't have a timezone, returns null. 
- New code and this use case has 100% code coverage.

**Comment by baldimir** [comment]
Mentioning @tarilabs, so Matteo knows about this.

**Comment by tarilabs** [comment]
I might be wrong, but this might be a change in semantic in later version of the spec. I seem to remember a rule that in some ops it would take the other operand TZ. Might be worth checking.

**Comment by baldimir** [comment]
Thanks, I will check.

**Comment by baldimir** [comment]
Yes, it may be new in 1.3 as the mentioned table 57 is not present in the 1.2 specification.

**Comment by baldimir** [comment]
This will be fixed as part of https://github.com/kiegroup/kie-issues/issues/62.
