### ISSUE TITLE
Unexpected loop with JoinNode and FromNode peer

### ISSUE THREAD

**Issue by tkobayas** [apache/incubator-kie-issues#686]
When peers are formed like this:
```
[JoinNode(6)]
  [JoinNode(8)]
    ...
  [FromNode(12)]
    ...
  [FromNode(17)]
    ...
``` 

updating fact causes an infinite loop ignoring the FromNode's constraint.

**Acceptance Criteria**
- Write a test case
- Avoid the infinite loop

**Comment by mariofusco** [comment]
Fixed by https://github.com/apache/incubator-kie-drools/commit/577ebb87bef03376edcae540154a0e9c4c49234e
