### ISSUE TITLE
Investigate the use of Etag with Cache-Control for KIE Sandbox

### ISSUE THREAD

**Issue by porcelli** [apache/incubator-kie-issues#688]
On every major update of KIE Sandbox the user needs to clear the cache to make sure the updated version is properly loaded from server. This experience is a bit clunky, as the user don't necessarily know when a new version was made available.

As alternative, the KIE Sandbox could use Cache-Control: no-cache with Etag, so the browser would automatically know about the need to renovate the cache based on ETag.

**Comment by tiagobento** [comment]
Duplicated of https://github.com/apache/incubator-kie-issues/issues/396
