### ISSUE TITLE
BAMOE Canvas: Import specific file from Bitbucket snippet does not work

### ISSUE THREAD

**Issue by danielzhe** [apache/incubator-kie-issues#695]
When running the sanity check:
1. Create a Model
2. Add some nodes
3. Add a Bitbucket app password using the Settings modal with scopes: "account:write", "snippet:write"
4. Use the "Create Snippet" button under the "Share" menu
**5. Open the Snippet URL and click on the name of your file
6. Import the URL with the #[file-name] and check if the model is the same.
7. Add a new file and check that it's an Ephemeral Workspace**

Step 6 with the URL of the DMN model gives an error:
Url: https://bitbucket.org/snippets/danielzhe/7qn5k6/untitled-folder.git#file-Untitled-1.dmn
Error: 
![image](https://github.com/apache/incubator-kie-issues/assets/7305741/bf4205cd-6487-4aaf-b8f5-baf0245d912c)

**Comment by tiagobento** [comment]
Misplaced issue.
