### ISSUE TITLE
SCA quality issue on generated code

### ISSUE THREAD

**Issue by wengkee** [apache/incubator-kie-issues#698]
I have a client who is using Kogito and their SCA tool returns some issues with the generated source code (e.g. unreleased resources, where the code didn't close the input stream properly, the recommended solution from the SCA tool is to put in finally block).

What is the right way to modify it so that the generated source code will be fixed? I imagine modifying the generated source code is a bad idea as I will need to keep doing it every time I compile it.

**Comment by gitgabrio** [comment]
Hi @wengkee 
Could you please provide a reproducer/model that lead to the creation of the affected code ?

**Comment by fjtirado** [comment]
Answering the initial question, we need the details of the issue to be able to fix it in the code generator. In this case, we know the solution will be to add add the missing finally block, but we do not know (yet) where to add it.

**Comment by wengkee** [comment]
[kogito.zip](https://github.com/apache/incubator-kie-issues/files/13405285/kogito.zip)

Hi, thanks for replying. Here is the source code sample.

**Comment by wengkee** [comment]
Regarding the issue from the SCA tool, it detects unreleased resource at 2 places. Below are the snippet from the report, which indicates that the issue are of high severty.

<img width="834" alt="Screenshot 2023-11-20 at 09 15 50" src="https://github.com/apache/incubator-kie-issues/assets/47697491/b46e5aaa-564f-4109-a351-76c0093a15b3">
<img width="853" alt="Screenshot 2023-11-20 at 09 16 08" src="https://github.com/apache/incubator-kie-
issues/assets/47697491/31de731e-af70-4854-9758-2f7f4e72607e">

**Comment by gitgabrio** [comment]
THanks @wengkee, looking...
