### ISSUE TITLE
Set main version of all repositories to 999-SNAPSHOT

### ISSUE THREAD

**Issue by porcelli** [apache/incubator-kie-issues#699]

**Comment by mariofusco** [comment]
Pull requests opened:
https://github.com/apache/incubator-kie-drools/pull/5629
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3336
https://github.com/apache/incubator-kie-kogito-apps/pull/1939
https://github.com/apache/incubator-kie-kogito-examples/pull/1846

**Comment by pefernan** [comment]
@mariofusco you've been faster than me!

**Comment by porcelli** [comment]
OptaPlanner is missing in the list =/ 

cc/ @lucamolteni

**Comment by mariofusco** [comment]
Implemented by
https://github.com/apache/incubator-kie-drools/pull/5629
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3336
https://github.com/apache/incubator-kie-kogito-examples/pull/1846
https://github.com/apache/incubator-kie-kogito-apps/pull/1939

**Comment by lucamolteni** [comment]
> OptaPlanner is missing in the list =/
> 
> cc/ @lucamolteni

I know, it's still a WIP - let's reopen this

**Comment by lucamolteni** [comment]
Optaplanner https://github.com/apache/incubator-kie-optaplanner/pull/3052

**Comment by pefernan** [comment]
Merged
