### ISSUE TITLE
DMN Editor: Hardcoded string as a feel expression has bad performaces.

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#7]
If there is a huge hardcoded string as a feel expression, then the hashCode javascript function is extremely slow. We have ~ 20kB JSON string hardcoded for testing purposes and after a removal it is faster.

https://github.com/kiegroup/kie-tools/issues/1281#issuecomment-1301988705

**Comment by jomarko** [comment]
@yesamer should we close this now, as gwt 2.10 upgrade is merged?

**Comment by yesamer** [comment]
@jomarko Not sure this is related to GWT update. Honestly, I didn't reproduce this, I opened it because of this comment https://github.com/kiegroup/kie-tools/issues/1281#issuecomment-1301988705

**Comment by msusicky** [comment]
Hi, thanks for updating GWT, it really has an impact on our DMNs. About this - I've realized that when I have 20kB FEEL string variable expression then the hashcode in javascript is consuming a lot of resources - there was a loop with thousands interations. I will try to check if with new GWT is still there. Give me this week please.

**Comment by jomarko** [comment]
@msusicky ok, please keep us informed.

**Comment by yesamer** [comment]
Closing - this is currently part of the next update of the new Boxed Expression editor.
