### ISSUE TITLE
Transfer KIE-Tools to Apache

### ISSUE THREAD

**Issue by eduardocerqueira** [apache/incubator-kie-issues#700]
- [x] Transfer to Apache the [kie-sandbox-quarkus-accelerator](https://github.com/kiegroup/kie-sandbox-quarkus-accelerator) repository
- [x] Transfer to Apache the [kogito-online-staging](https://github.com/kiegroup/kogito-online-staging) repository
- [x] Transfer to Apache the [kogito-online](https://github.com/kiegroup/kogito-online) repository
- [x] Transfer to Apache the [kie-tools](https://github.com/kiegroup/kie-tools) repository

**Comment by porcelli** [comment]
https://issues.apache.org/jira/browse/INFRA-25248
