### ISSUE TITLE
Adjust Jobs Service to properly work with Compact Architecture

### ISSUE THREAD

**Issue by porcelli** [apache/incubator-kie-issues#706]
Apache Thread: https://lists.apache.org/thread/h20y3roz170v6rbshtdry0jw0dx5ys69

This is placeholder issue that aims to track work related to the option 2 discussed in the apache dev mailing list.

**Comment by elguardian** [comment]
I did the tweaks for compact arch. This is a duplicated issue from
https://github.com/apache/incubator-kie-issues/issues/711

https://github.com/apache/incubator-kie-kogito-runtimes/pull/3295
https://github.com/apache/incubator-kie-kogito-apps/pull/1925
