### ISSUE TITLE
Investigate TCK failures and update results for Drools on DMN TCK page

### ISSUE THREAD

**Issue by baldimir** [apache/incubator-kie-issues#709]
Investigate DMN TCK failures and update Drools results on https://dmn-tck.github.io/tck/ webpage with the latest Drools version. 

There are some new failures unreported, investigate and report them in incubator-kie-issues.

**Comment by yesamer** [comment]
Closing as duplicate of https://github.com/apache/incubator-kie-issues/issues/357
