### ISSUE TITLE
Use EvaluationContext in code generated FEEL

### ISSUE THREAD

**Issue by baldimir** [apache/incubator-kie-issues#71]
Currently when using code generated feel (translated to Java instead of interpreted), the evaluation context is not used in the methods that are doing the evaluation. Example is [here](https://github.com/kiegroup/drools/blob/c07f0d800ae7441fcb5b6fe7055088315569e2ae/kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/codegen/feel11/CompiledFEELSemanticMappings.java#L358). 

Acceptance criteria: 
- Context is sent to all AST node methods used in the code generated FEEL. 
- All tests pass. 
- New code has 100% code coverage.

**Comment by tarilabs** [comment]
imho, you are not obliged to "Context is sent to all AST node methods used in the code generated FEEL" meaning all-all methods.

Some (in the codegen flavour) did not have context passed only as a way to simplify as that was not needed (like the case we discussed).

As requirement changed, at least the `div` method now requires that.
You can consider extending the context passing:

- only to `div`
- only to arithmetic methods

without having to refactor for _all_ semantic methods.

But that again, is just my perspective :) hope this helps 😉

**Comment by baldimir** [comment]
@tarilabs Yes, I added it only to the arithmetic ones. The context is used in the other methods already in different ways. Please see the linked PR.

**Comment by tarilabs** [comment]
> Please see the linked PR.

Done as requested.
