### ISSUE TITLE
DMN Decision table column generated from type with constraint

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#75]
needs to reflect the data type constraint. In other words. If the Decision table is generated for a InputData node, that is referring to a custom DataType (myType: is range [1..100]), then also Decision Table Input Data column needs to reflect this configuration like shown bellow.

![Screenshot_20221221_110319](https://user-images.githubusercontent.com/8044780/208878324-0ebe961c-15f6-41cd-b0ce-7819e09346f3.png)
![Screenshot_20221221_110403](https://user-images.githubusercontent.com/8044780/208878325-1c7de165-81ea-4946-9bfe-06a586eeb32b.png)

Furthermore, we should support this just for the first time decision table generation. Any following updates to data type definition or the Input Data Nodes requirements will be not automatically reflected in the decision table columns.

**Comment by jomarko** [comment]
Fix prepared as https://github.com/kiegroup/kie-tools/pull/1383

**Comment by tarilabs** [comment]
ref https://issues.redhat.com/browse/DROOLS-4640

thanks @jomarko
