### ISSUE TITLE
Change GH credentials id for git.author.token_credentials_id

### ISSUE THREAD

**Issue by jstastny-cz** [apache/incubator-kie-issues#751]
kogito images nightlies are not starting due to problem with GH token when resolving forks of the repo, which was not visible before, because original PR was from origin itself.

The problem was present also for buildchain config previously, back then used kie-ci3-token instead.

**Comment by jstastny-cz** [comment]
incubator-kie-optaplanner
and 
incubator-kie-drools

to be adjusted similarly.

**Comment by cimbalek** [comment]
https://github.com/apache/incubator-kie-kogito-pipelines/pull/1150
