### ISSUE TITLE
Fix kogito operator nightly deploy pipelines

### ISSUE THREAD

**Issue by jstastny-cz** [apache/incubator-kie-issues#755]
Nightly builds for kogito and serverless operator are still failing due to pipeline errors.

Naming a few:
* cleanSkopeo is not needed anymore and it's not in cloud shared libraries, remove invocations
  * error from groovy dsl about missing method
* cleanWs() with deferred wipeout can't be used in initial stages (safe to use only in after stage)
  * getCwd fails if not done so
* missing jenkins plugin for lock option?
  * WorkflowScript: 194: Invalid option type "lock". Valid option types: [ansiColor, catchError, checkoutToSubdirectory, datadog, retry, script, skipDefaultCheckout, throttle, timeout, timestamps, waitUntil, warnError, withChecks, withContext, withCredentials, withEnv, wrap, ws] @ line 194, column 17.

**Comment by jstastny-cz** [comment]
@ricardozanini do you have any progress in this area which would not be in main branches? Where can we start?

**Comment by ricardozanini** [comment]
@jstastny-cz I don't have it. @jakubschwan do you have it?
