### ISSUE TITLE
Jenkins jobs failing on ephemeral nodes

### ISSUE THREAD

**Issue by jstastny-cz** [apache/incubator-kie-issues#762]
In ASF jenkins there are 2 types of nodes under the `ubuntu` label.
* buildsXY (label ubuntu)
* EC2 ephemeral nodes (labels ubuntu, ephemeral)

The ephemeral nodes configuration seems to differ in some details to what buildsXY nodes have.
Especially we see failures in docker related actions (docker container startup and stuff).

Investigate these failures and if a fix is not clear, consider filtering out ephemeral nodes using the label expression:
```
agent {
  label 'ubuntu && !ephemeral'
}
```
and maybe also for docker agent configuration:
```
    agent {
        docker { 
            image env.AGENT_DOCKER_BUILDER_IMAGE
            args env.AGENT_DOCKER_BUILDER_ARGS
            label 'ubuntu && !ephemeral'
        }
    }
```

**Comment by eduardocerqueira** [comment]
DONE
