### ISSUE TITLE
Adjust CI configuration for maven projects unifying on project.version 10

### ISSUE THREAD

**Issue by jstastny-cz** [apache/incubator-kie-issues#763]
Below is list of changes needed regarding unification of project versions across Apache KIE maven repositories.
* sanitize SNAPSHOT versioning
  * main on 10.0.0-SNAPSHOT
  * after first release, and in further on
    * bump to 10.1.0-SNAPSHOT
    * branch 10.0.x, there update to 10.0.1-SNAPSHOT
* remove mappings from buldchain configuration files
  * there used to be expression to adjust versions 1.x vs 8.x when having both drools and kogito repositories in chain

**Comment by fjtirado** [comment]
@jstastny-cz Do we really need to update the snapshot after every release?. This basically implies updating all kogito-runtimes parent pom references after every release in main branch.

**Comment by fjtirado** [comment]
I propose to use a fixed snapshot. About the number, we can use one that nobody will ever map to an existing living release, for example 6969-SNAPSHOT

**Comment by porcelli** [comment]
quick update here: has been defined in dev ML that we'll use 999-SNAPSHOT
