### ISSUE TITLE
Fix optaplanner setup-branch jenkinsfiles

### ISSUE THREAD

**Issue by jstastny-cz** [apache/incubator-kie-issues#769]
Optaplanner and optaplanner-quickstarts setup-branch jenkinsfiles have known problems that were fixed elsewhere:
* cleanWs() in initial phase
* wrong docker agent config

**Comment by cimbalek** [comment]
Is this still an issue?

**Comment by cimbalek** [comment]
@jstastny-cz is this still actual?

**Comment by jstastny-cz** [comment]
It's marked as closed already :-)
