### ISSUE TITLE
Allow restricting jenkins agent labels for pipelines

### ISSUE THREAD

**Issue by jstastny-cz** [apache/incubator-kie-issues#777]
In case a node is faulty and not disconnected in time (there are cases taking over one day) it might be useful to have the label configuration parameterized.

Currently this is in place only in case of seed generation, using env.AGENT_LABEL which is set in 0-seed-job explicitly (hardcoded). 
This change though is promoted only through the seeds, not into the generated pipelines.

Generally pipeline Jenkinsfiles can have following label definitions:
```
agent {
  label ''
}
```
```
agent {
  docker {
     image ''
     args ''
     label ''
  }
}
```
and label can be an expression `ubuntu && !builds43`.

It seems that a possible solution would be:
1. set the AGENT_LABEL env variable already in KIE Jenkins folder.
2. rely on the value being inherited by jobs and folders below.
3. in Jenkinsfiles, instead of literal `'ubuntu'` use `env.AGENT_LABEL` as is in `Jenkinsfile.seed.main`
4. remove other places where AGENT_LABEL is set (0-seed-job in root and branches, seed_job_[main|branch].groovy)

**Comment by jstastny-cz** [comment]
@cimbalek please check the pr_check.groovy script, it's the only appearance of scripted pipeline in our pipelines and we've missed it with the faulty labels adjustment: https://github.com/apache/incubator-kie-kogito-pipelines/blob/main/dsl/scripts/pr_check.groovy#L35

I believe wrapping as 
```
node ("label"){
   docker.image(builderImage).inside(dockerArgs.join(' '))
}
```
might do the trick
https://www.jenkins.io/doc/pipeline/steps/workflow-durable-task-step/#node-allocate-node

**Comment by cimbalek** [comment]
Documentation can be found here https://github.com/apache/incubator-kie-kogito-pipelines?tab=readme-ov-file#jenkins-kie-folder

**Comment by cimbalek** [comment]
> @cimbalek please check the pr_check.groovy script, it's the only appearance of scripted pipeline in our pipelines and we've missed it with the faulty labels adjustment: https://github.com/apache/incubator-kie-kogito-pipelines/blob/main/dsl/scripts/pr_check.groovy#L35
> 
> I believe wrapping as
> 
> ```
> node ("label"){
>    docker.image(builderImage).inside(dockerArgs.join(' '))
> }
> ```
> 
> might do the trick https://www.jenkins.io/doc/pipeline/steps/workflow-durable-task-step/#node-allocate-node

@jstastny-cz like this? https://github.com/apache/incubator-kie-kogito-pipelines/pull/1183/files
Will tests show if it works like this or do we need to test it sideways on jenkins first?

**Comment by cimbalek** [comment]
Noone was complaining to me anymore so I consider it done
