### ISSUE TITLE
DMN - Improve performance of InfixOpNode

### ISSUE THREAD

**Issue by gitgabrio** [apache/incubator-kie-issues#781]
THe refactoring of InfixOpNode lead to some loss of performance.
One reason could be the instantiation of new objects (EvaluatedParams, ClassIdentifierTuple) at each invocation.
FInd a way to remove that and use the benchmark created with https://github.com/apache/incubator-kie-issues/issues/780 for comparison
Depends on https://github.com/apache/incubator-kie-issues/issues/780

**Comment by mariofusco** [comment]
Fixed by https://github.com/apache/incubator-kie-drools/commit/20940235993e9f077fef228b99e071154539e784
