### ISSUE TITLE
DMN Editor: backport kie-issues#43 into 7.x stream

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#79]
We should backport [kie-issues#43](https://github.com/kiegroup/kie-issues/issues/43) into 7.x stream as there was a product jira asking to do it.

There was already an ensemble, that can be probably re-used at time this kie-issue is being fixed

- https://github.com/kiegroup/kie-wb-common/pull/3796
- https://github.com/kiegroup/drools-wb/pull/1565
- https://github.com/kiegroup/appformer/pull/1371

**Comment by yesamer** [comment]
@jomarko I added the same info in the RH Jira https://issues.redhat.com/browse/RHPAM-4050. In my opinion, that is the correct place to track it. I think we can close this ticket and rely on the RHPAM only to track it, WDYT?

**Comment by jomarko** [comment]
@yesamer I do not feel in power to answer. Your proposal sounds good to me, however I thought that this ticket was required by @porcelli . I do not know, I am fine with both solutions.
