### ISSUE TITLE
`kogito-operator` disable tests and get CI stable

### ISSUE THREAD

**Issue by eduardocerqueira** [apache/incubator-kie-issues#807]
in order to stabilize the CI pipelines for in preparation for the next release, the best approach will be disabling the tests temporally and get all pipelines running properly. More investigation will be needed for this component.

**Comment by domhanak** [comment]
FYI @jakubschwan

**Comment by rodrigonull** [comment]
PR: https://github.com/apache/incubator-kie-kogito-operator/pull/1535
