### ISSUE TITLE
[Release Automation] Create Jenkins jobs to upload  sources.zip to https://dist.apache.org/repos/dist/dev/incubator/kie 

### ISSUE THREAD

**Issue by cimbalek** [apache/incubator-kie-issues#815]
See `AUTOMATION D` --> Artifacts (Built from RC tag. E.g., 10.0.0-rc1) @ https://docs.google.com/document/d/1t-08b970i9PMBy-TSM64x0RUH46pzwnIhEi-LVeL0lg/edit

Depends on: #828

**Comment by tiagobento** [comment]
All 7 repos of the release
- incubator-kie-10.0.0-sources.zip

**Comment by cimbalek** [comment]
https://github.com/apache/incubator-kie-kogito-pipelines/pull/1202
