### ISSUE TITLE
Remove Oracle driver dependency from codebase

### ISSUE THREAD

**Issue by porcelli** [apache/incubator-kie-issues#817]
Based on this thread [1] and this legal issue feedback [2] - remove Oracle driver is required to comply with Apache Foundation requirements.

[1] https://lists.apache.org/thread/1t29vxrnhfxk63j4n6do6g8jhl6l858j
[2] https://issues.apache.org/jira/browse/LEGAL-663

**Comment by fjtirado** [comment]
Fixed with https://github.com/apache/incubator-kie-kogito-runtimes/pull/3381 and https://github.com/apache/incubator-kie-kogito-apps/pull/1971

**Comment by porcelli** [comment]
Thank you very much @fjtirado !
