### ISSUE TITLE
Drools, Kogito-apps and Kogito-runtimes weekly jobs

### ISSUE THREAD

**Issue by rodrigonull** [apache/incubator-kie-issues#821]
Create a weekly Jenkins job for Drools, Kogito-Runtimes and Kogito-Apps to build and deploy a version that will be consumed by KIE Tools JIT executor Github action.

Job requirements:
- run every week on Sunday at 04:00 AM
- Checkout the code from main branch that was pushed till 2:00 AM: `git checkout 'git rev-list -n 1 --before="2024-01-17 02:00" main'` (The same strategy will be used in the JIT executor Github action to make sure both jobs are using the exact same code)
- Set the project version to: 999-YYYYMMDD-SNAPSHOT   (i.e: 999-20240117-SNAPSHOT)
- Run the build
- Push the build artifacts to Apache repository
- Create a tag in the repository with the project version  (i.e: 999-20240117)

**Comment by ederign** [comment]
@rodrigonull, I was discussing this with Tiago and later with Zanini, and we believe that we should also expand the scope of this task to cover SWF CLI (kn-plugin workflow package). 

Currently, kn-plugin-workflow has the following internal dependencies:
- [go.mod](https://github.com/apache/incubator-kie-tools/blob/c6eb6aa160b54882749a18a39b53059b53424f8e/packages/kn-plugin-workflow/go.mod#L10C69-L10C69) with source dependency to kogito-serverless-operator
- [env/index.js](https://github.com/apache/incubator-kie-tools/blob/main/packages/kn-plugin-workflow/env/index.js) dependencies to:

1. [kogito-version](https://github.com/apache/incubator-kie-tools/blob/main/packages/kn-plugin-workflow/env/index.js#L47): your proposal already covers it via runtime release and is used on our pom.xml file of the generated project;

2. [dev mode image deploy](https://github.com/apache/incubator-kie-tools/blob/main/packages/kn-plugin-workflow/env/index.js#L42):  used on docker runs for 'non-java' serverless workflow projects

I want to check with you if it's possible to include the following requirements on each weekly job execution:
- create a new tag on [incubator-kie-kogito-serverless-operator](https://github.com/apache/incubator-kie-kogito-serverless-operator/) to source consumption via go build;
- build and deploy a new [dev mode image](http://on%20each%20weekly%20job%20execution/) for the CLI consumption.

This standardization is crucial to keep the kie-tools project completely manageable.

Is it feasible? /cc @tiagobento @ricardozanini @porcelli

**Comment by ricardozanini** [comment]
@rodrigonull can we have instead the version being named after the commit hash? e.g. 10.0.0-12345. It aligns well with semver and we can track back to the commit if it's needed.

**Comment by tiagobento** [comment]
@ricardozanini There are multiple repositories involved in this, so I guess it won't be nice for consistency if the versions are different depending on where an artifact comes from...

**Comment by tiagobento** [comment]
@rodrigonull But I agree that having a way to trace back to the commit would be good. I suggest we create tags for all repos for these "timestamped" releases.

**Comment by rodrigonull** [comment]
@ederign I think I can work on adding these 2 extra jobs for kogito-serverless-operator and kogito-images. My only concern is that this task is already taking more time than I expected for the three initial projects, so I'm not sure how long it will take for me to finish it and I know that we don't have much time left for the release 10. 
@porcelli Is there someone that could work with me on this issue?

**Comment by rodrigonull** [comment]
@tiagobento @ricardozanini I added the tag creation as part of this issue. Hopefully our user on Apache Jenkins already have permissions for pushing tags.
