### ISSUE TITLE
Upgrade maven plugin versions inside kogito-runtimes

### ISSUE THREAD

**Issue by gitgabrio** [apache/incubator-kie-issues#824]
Inside kogito runtimes (`kogito-build-no-bom-parent/pom.xml`).  , upgrade versions for
maven-jar-plugin -> `3.2.0`
maven-source-plugin -> `3.2.1`

This will lead to build failure due to missing `java.module.name` property in some modules, that should be fixed

e.g. 

```
  <properties>
    <java.module.name>org.kie.kogito.common.workitems</java.module.name>
  </properties>
```

Needed by https://github.com/apache/incubator-kie-issues/issues/820

Requires 
1. https://github.com/apache/incubator-kie-issues/issues/825
2. https://github.com/apache/incubator-kie-issues/issues/826

**Comment by elguardian** [comment]
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3355

**Comment by gitgabrio** [comment]
Fixed by https://github.com/apache/incubator-kie-kogito-runtimes/pull/3355
