### ISSUE TITLE
Refactor InfixOpNode inside DMN core

### ISSUE THREAD

**Issue by gitgabrio** [apache/incubator-kie-issues#83]
[InfixOpNode](https://github.com/kiegroup/drools/blob/d2b751c25c9d6e5e749177c8d92f1cdfd494d2aa/kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/InfixOpNode.java) class is meant to provide static methods to execute operations on FEEL expressions.
For each operation there is a specific method. Innside each of those methods, the actual type of left and right parameters is checked, a cast is made an the operation is executed.
Invalid parameters/tupla of parameters are currently dealt with on a case-by-case way, with the result that the code is becoming unconsistent and is hard to maintain.

Scope of the ticket is

1. analyze the current design of the class after all the invalid situations are dealt with
2. improve the design of the class to provide a consistent and easy-to-maintain implementation.

Possible suggestions:

1. define, for each operation, the valid types of the left and right parameter/tupla inside a "Collection (Map ? List of a specifically crafted Type-Type tupla ?)
2. replkace all the "if" with iteration over the above "valid-types" tupla
3. for each operation, provide an "isAllowedPArametersFor..." to validate input as first step
4. for each operation, provide one/two methods that could manage all the different parameters tupla based on highest common superclass

Acceptance criteria

1. Performance of refactored code should not be worse then original
2. Behavior of the refactored code should be the same as the original
3. Overall usage of "if" inside operations methods should be removed/reduced as much as possible
4. The definition of the "allowed values" and the actual behavior (invoked operation e.g. `a.plus(b)`)) should be clearly separated/isolated (currently, is embedded in the "if" train) so that whenever a new invalid input situation is discovered, the required modification is isolated only in the former withouth touching the rest of the code

@baldimir @yesamer @kbowers-ibm Please add comment/suggestion or let me know if something on the description is not clear.

**Comment by baldimir** [comment]
I think one of the acceptance criteria should be that the performance stays the same.

**Comment by tiagobento** [comment]
Can we have more context on the name of this issue? The way it is now is too specific and won't be friendly for everyone reading it.
