### ISSUE TITLE
Make Operators (SonataFlow/Kogito) and Kogito Images build reproducible

### ISSUE THREAD

**Issue by ricardozanini** [apache/incubator-kie-issues#830]
Based on Apache policy, or images and operators (golang) must have reproducible builds.

For Go, we might have to upgrade to Go 1.22: https://go.dev/blog/rebuild
For the Images, apart from shipping the Dockerfile generated by Cekit, we might have to add more steps to our build system. Investigation needed.

**Comment by ricardozanini** [comment]
More information easily to digest by non-go developers: https://www.infoq.com/news/2023/09/go-toolchain-reproducible-builds/

**Comment by domhanak** [comment]
@ricardozanini the upgrade to 1.21 should be done imho - https://github.com/apache/incubator-kie-tools/pull/2113 - kietools already did it and moving to new version is now possible as we have it also available downstream

**Comment by ricardozanini** [comment]
Oh yes! I've already upgraded in the operator PR.

**Comment by ricardozanini** [comment]
There are two more PRs to close this issue. (kogito-operator and kogito-images)

**Comment by yesamer** [comment]
I guess this ticket can be closed @ricardozanini. I'm going to close it, but please feel free to reopen it If I'm wrong.
Thank you!
