### ISSUE TITLE
EPIC - Reproducible Build

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#837]
As part of the Apache migration, after adding the required configurations, we need to fully enable the [Reproducible Build](https://maven.apache.org/guides/mini/guide-reproducible-builds.html) mechanism in the following repositories:

- [x] #840
- [x] #839
- [x] #843
- [x] #830 
- [x] #846

The goal is to launch the following command pipeline without any failure:
`mvn clean install`
`mvn clean verify artifact:compare` (It checks against the previous build)
(adding `-DskipTests` is allowed)

Please share in this ticket the failures you found and how you fixed them, to support whoever is working on this task.

**Comment by ricardozanini** [comment]
Please add this: #830

**Comment by yesamer** [comment]
All tasks completed.
