### ISSUE TITLE
Reproducible Build: `kogito-runtime` repo

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#839]
As part of the Apache migration, after adding the required configurations, we need to fully enable the [Reproducible Build](https://maven.apache.org/guides/mini/guide-reproducible-builds.html) mechanism in `kogito-runtime` repo

Current status:

<img width="1316" alt="Screenshot 2024-01-19 at 10 30 49" src="https://github.com/apache/incubator-kie-issues/assets/16005046/ee56c024-52bd-4968-9d99-363c9e013500">

**Comment by baldimir** [comment]
PR submitted: https://github.com/apache/incubator-kie-kogito-runtimes/pull/3393
