### ISSUE TITLE
DMN Editor: Re-enable the new Boxed Expression Editor in Standalone Editor (and Chrome Extension)

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#84]
https://issues.redhat.com/browse/KOGITO-7830

In this PR: https://github.com/kiegroup/kie-tools/pull/973, we removed the new Boxed Expression shift because:

-     Chrome Extension: Because the new editor doesn't support read-only mode
-     Standalone (or Embedded) Editor: Here, the new BEE doesn't work at all

The new editor still doesn't support read-only mode (so far), we can discuss if it makes sense to enable it in the Chrome Extension or not. 
Thus, the minimal requirement of this ticket is to re-enable it in the standalone editor.
To do it, modifying [this line ](https://github.com/kiegroup/kie-tools/pull/973/files#diff-47fa841f9178a2b1068183f5e513c28310ef10539c8f7aace05d0646dc118cdcR110)is required but not enough. As far I remember, the switch doesn't work in Standalone Editor because the required JS files are missing (most likely the [dmn-loader](https://github.com/kiegroup/kie-tools/tree/main/packages/stunner-editors-dmn-loader))

**Comment by yesamer** [comment]
**Analysis**
To correctly enable the GWT-React BEE bridge, is required that `dmn-loader.js` is loaded as a script in the html page and registered with `__KIE__DMN_LOADER__` namespace (see DMNLoader.java)
IIUC, in the standalone app the required `dmn-loader.js` is imported and integrated inside a unique js file (`index.js`). The bridge's link between the namespace and the js file is not managed. As a result, when the editor tries to render the new boxed expression, an NPE is thrown

<img width="1527" alt="Screenshot 2023-01-27 at 10 50 47" src="https://user-images.githubusercontent.com/16005046/215057359-80693177-23bc-41b2-bb35-e80c0c2f31d5.png">

Thus, we need to find a strategy to manage the missing link.

**Comment by yesamer** [comment]
In GWT code, you can modify `ExpressionEditor.java:113` to enable them.

**Comment by yesamer** [comment]
@tiagobento I'm very glad to see that issue doesn't occur in the [bee refactoring branch ](https://github.com/tiagobento/kie-tools/tree/bee-reisizing-perf). 
In that branch, it works nicely with no required changes.

<img width="1523" alt="Screenshot 2023-03-21 at 11 11 10" src="https://user-images.githubusercontent.com/16005046/226576343-60c7c777-0cfd-4127-893e-4c6db5575e8e.png">

Despite I'm very glad that, I don't understand the root cause of the issue we currently have in main, and why it doesn't occur in the refactoring branch.

I think we can close this and double-check again the standalone editor after the merge of the above branch, let me know what you think.

**Comment by tiagobento** [comment]
@yesamer There are so many wrong things with the BEE that's in `main` that I don't really think it's relevant for us to find the root cause of this. Let's blindly celebrate that it's working now! :D
