### ISSUE TITLE
Reproducible Build: `drools` repo

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#840]
As part of the Apache migration, after adding the required configurations, we need to fully enable the [Reproducible Build](https://maven.apache.org/guides/mini/guide-reproducible-builds.html) mechanism in `drools` repo

Current status: 
<img width="1307" alt="Screenshot 2024-01-18 at 16 11 28" src="https://github.com/apache/incubator-kie-issues/assets/16005046/af5fd397-11b4-4234-8d9a-0cb4da8d854a">

- [x] https://github.com/apache/incubator-kie-issues/issues/858
- [x] https://github.com/apache/incubator-kie-issues/issues/859

**Comment by gitgabrio** [comment]
FYI: I saw problem of buildinfo in other places: this is something that -maybe - maybe fixed with some tweak on configuration, but we have to understand exactly what create that

**Comment by baldimir** [comment]
Closing this as done.
