### ISSUE TITLE
Reproducible Build: `kogito-apps` repo

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#843]
As part of the Apache migration, after adding the required configurations, we need to fully enable the [Reproducible Build](https://maven.apache.org/guides/mini/guide-reproducible-builds.html) mechanism in `kogito-apps` repo

Current status: 
<img width="1443" alt="Screenshot 2024-01-19 at 16 06 57" src="https://github.com/apache/incubator-kie-issues/assets/16005046/517d8a13-a554-474d-bec3-ccf973af23e9">

**Comment by baldimir** [comment]
PR for Java code in kogito-apps: https://github.com/apache/incubator-kie-kogito-apps/pull/1981
