### ISSUE TITLE
Quarkus + Kogito extension Maven project with generated DMN resources from another Maven dependency

### ISSUE THREAD

**Issue by gitgabrio** [apache/incubator-kie-issues#847]
See discussion [here](https://community.ibm.com/community/user/automation/discussion/quarkus-kogito-extension-maven-project-with-generated-dmn-resources-from-another-maven-dependency#bmb1e1ec67-dde7-4be3-aa07-018d35869f98)

Core point:
During codegen, scanned path are "hardcoded" to "src/main" (i.e. under the source folder), and that prevent to import files from different jars, even using the standard maven `dependency:unpack-jar` (a possible workaround could be to extract files from imported jars under the "sources" folder, but it would be a pretty bad choice).

Todo:
1. go over original community thread
2. verify problem/involved code
3. implement better path-resolution strategy

**Comment by bgillis** [comment]
Thanks @gitgabrio for adding my request as a Kogito enhancement.
I will subscribe to any update on this ticket.

**Comment by bgillis** [comment]
@gitgabrio 
Shouldn't this ticket created in the project "https://github.com/apache/incubator-kie-kogito-runtimes" instead of "https://github.com/apache/incubator-kie-issues" ?

As a matter of fact, the cause of this issue is Kogito codegen.

**Comment by gitgabrio** [comment]
> @gitgabrio Shouldn't this ticket created in the project "https://github.com/apache/incubator-kie-kogito-runtimes" instead of "https://github.com/apache/incubator-kie-issues" ?
> 
> As a matter of fact, the cause of this issue is Kogito codegen.

For the moment being we are creating tickets under kie-issues, regardless of relevant code (drools/kogito-runtimes/kogito-apps) - see other opened issues
