### ISSUE TITLE
Add more Git operations on KIE Sandbox

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#85]
KIE Sandbox needs to allow users to have more control over their changes before they push. Implementing the operations below will improve the experience considerably.
 
- Reverting changes of a single file (like `git checkout [file-path]`) (Probably at the Kebab menu? This needs a confirmation alert/modal)
- Reverting changes of the entire Workspace (like `git checkout .`), going back to the state of last commit. (Probably at the Kebab menu as well? This needs a confirmation alert/modal).
- Show which files are modified on the File Switcher (for current Workspace only). An icon indicating that a file has changes is enough.
- Add an option on the File Switcher to show only files that contain changes.

EDIT:
- The reverting operation needs to handle also files being deleted and need to be restored.

**Comment by jstastny-cz** [comment]
@tiagobento is there any precaution behind suggestion that the sync-status only in the FileSwitcher component? The other area would be the homepage directly:


![Image](https://user-images.githubusercontent.com/11939909/216322726-dad9f27b-f017-4a92-a295-52646dfac25d.png)

**Comment by jstastny-cz** [comment]
@thiagoelg @tiagobento or anyone :-)
I would use some UX advice on a few things


![Image](https://user-images.githubusercontent.com/11939909/216917692-2d4f9c2f-5a8e-4749-b9da-22d4b71559a8.png)



![Image](https://user-images.githubusercontent.com/11939909/216917794-55ffec29-65ee-41a6-90b9-30fb9c802af6.png)

1. Git-sync status icon position and styling.
  I've implemented the icons as a Label with GitIcon as categorization and with warning or check icons reflecting the actual value (with title text which renders on mouse over).
  Justification of the placement - I would put this status icon either at the beginning or end of the line, while I was not able to alter location of the MenuItem checkbox (in FileSwitcher.tsx component, the first screenshot in this post).
  * EDIT: the other solution could look similarly to 
    ![Image](https://user-images.githubusercontent.com/11939909/216939178-b90fc0c6-4241-4dd0-8505-91313a61214e.png)
  * EDIT2 (current): I tried custom impl of the selection, with the git-sync status and actions on the right:
    ![image](https://user-images.githubusercontent.com/11939909/216975597-8af552c2-4284-47db-bee3-c8aff68aa317.png)



2. Filter by git-sync status
  The filter is implemented as a Select with applicable options, while I am generally fine with the location, maybe styling needs improvement? 
  ![Image](https://user-images.githubusercontent.com/11939909/216919759-7e39cdc5-7a85-4fbd-ad75-857115c627b9.png)

3. Change in FileSwitcher itself - I needed to start listing also the current file, which was filtered out on purpose. Thus I needed to render the checkbox to mark the current file as a result. I find it more in sync with request for this to serve as the workspace overview - we have full view here, the notion of marking the current file is up to discussion - though this way is how patternfly renders it by itself, anything else would probably require manual tweaking (See EDIT2 in point 1. above)

4. I am hitting issues with Dropdown nested in Menu, complaining either in Button being nested in another Button, or, when switching rendering using property `component` where possible, I hit sth as `React does not recognize the "disableHover" prop on a DOM element.` Solution to this might be an `isText` property to the newly added Dropdown. But, it seems only newer version of Patternfly brings this in - https://github.com/patternfly/patternfly-react/issues/6687 , it should have been released in @patternfly/react-core@4.184.0

**Comment by thiagoelg** [comment]
Maybe we could steal some ideas from VSCode? Like adding a "Git" tab to the FileSwitcher component, showing the changed (staged and unstaged - not sure we can differentiate between those) files, and allowing the user to revert or stage one by one:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/10515135/217014591-ed03e408-f20f-4a84-bc1c-04c0b48be69c.png">

Adding a shortcut to create a commit could also be useful.

What do you think?

**Comment by jstastny-cz** [comment]
@thiagoelg 

Currently I've somehow put things together using the approach with dropdowns:

![Image](https://user-images.githubusercontent.com/11939909/217031887-1ac9a1ba-768f-4fce-9321-19d8e30c7dd1.gif)




I'll try to draft the variant you proposed above.

**Comment by jstastny-cz** [comment]
@thiagoelg To your suggestion regarding the git-specific menu, this might be useful in future for sure. We've discussed with @tiagobento more broadly on this topic and the conclusion was to limit the scope of changes here and then adjust based on user's feedback.

I've simplified the UI changes, reusing what we already had in WorkspaceStatusIndicator.tsx which I now tweaked a bit to optionally accept a workspacefile and depending on that render a bit differently in FileSwitcher - leaving out the isSynced information in there - that seems workspace-scoped thus showing only up in the editor toolbar.

One thing I am missing still is the confirmation alert that'd warn user, as mentioned in the initial description.
![revert](https://user-images.githubusercontent.com/11939909/217477299-b265cc08-071f-4328-a042-b38ddc036b83.gif)

**Comment by thiagoelg** [comment]
Yep, that makes sense. This looks great!

Deleting a file will show it in the FileSwitcher component with a `D` icon? Will it be possible to revert the deletion too?
Not sure how complex it would be to implement that, could be another task.

**Comment by jstastny-cz** [comment]
@thiagoelg I am working on that right now. For workspace indicator I thought it would be useful to have set of icons reflecting statuses of each files. In file switcher I show either Modified or Deleted (does not make sense to put both M and D in case of a file).
![image](https://user-images.githubusercontent.com/11939909/217764548-ae04daaa-3b35-4dee-93a0-36e4cdf240c4.png)

For deleted file I prevent click plus put a `(Deleted in workspace)` suffix to item's tooltip, rendering now e.g. as `MyFile.dmn (Deleted in workspace)`. The dropdown with revert operation is still clickable.

Same for carousel, there I just wonder if I should remove the svg image part or put some default, or keep like this. (One problem I see after revert is, that the svg does not load, need to fix that).
![image](https://user-images.githubusercontent.com/11939909/217765965-d6815d78-30b3-49af-a8e0-212719c9e53a.png)

**Comment by tiagobento** [comment]
@jstastny-cz Very nice UI for deleted files, I like it!

Regarding the SVG...... 😅 

So we have something I called "Companion FS", which is basically an FS implementation that will replicate operations on files that are "related" to files on the "main" FS. When you delete a file on the main FS, the companion FS will delete its related files, meaning the SVG is deleted (forever) when you delete a file on the main FS.

Of course, right now with the ability to revert this deletion, we're going to end up with a missing SVG that was potentially perfectly fine before deleting the file. I think this is a minor bug that requires a major solution. I would map this in a "Backlog" issue and leave it there for now. If this gains interest from users, we make a plan to address that, WDYT? If you agree @jstastny-cz please create this issue there for us.

**Comment by jstastny-cz** [comment]
> Regarding the SVG

To prevent misunderstanding - when I delete the file and don't see the SVG I think that's understandable. My concern was, that after I reverted the file (it came back into existence) - the SVG does not reload in the menu until I navigate editor to it (specifically to that exact file, it is not enough to reload the editor or even the page).

So for me the missing part of the picture is how the SVG thumbnail is actually created, from the findings above I assume it is stored when the file itself is loaded into editor, correct? (And thus the "workaround" above resolves...)

**Comment by jstastny-cz** [comment]
@thiagoelg @tiagobento if you have a sec, I would like to get feedback on the "confirm action" part of the requirement.

* alert is "annoying" in terms of changing control elements location significantly
* inline solution using drilldownMenu
  * problem nesting this into FileSwitcher which is drilldownMenu itself, I didn't make it work nicely, would require spreading the git-sync indicator context more broadly into codebase, which I didn't like anyway.
    * not even nesting under a dropdown helped 
  * problem with having this in the workspace toolbar section - it's not possible to tweak overflow x and y so that the drilldown menu renders nicely and at the same time the toolbar does not expand together with it.
* inline solution using dropdown + expandableContent
  * is not so smooth as drilldownMenu, but works nicely in all places.
  * Dropdown direction is varying based the actual placement. In FileSwitcher the dropdown position is set to right, not to overflow the menu itself, while on workspace toolbar more natural is the oposite:
    * ![image](https://user-images.githubusercontent.com/11939909/219000697-14ca8f91-27d6-4c5e-bf73-f0e3c53216cf.png)
  * One concern is the expansion of the dropdown, tried to overcome that by keeping control elements in same location:
    * ![image](https://user-images.githubusercontent.com/11939909/218977717-ae54df1b-1090-41dd-98e8-4087e4d5f75f.png)
    * ![image](https://user-images.githubusercontent.com/11939909/218978051-c50997e7-534b-46d5-91d8-400b56bf81b7.png)

**Comment by tiagobento** [comment]
Regarding the SVG: Yes, the SVG is created when we open the Editor. Right now, the code that knows how to generate an SVG for a diagram is inside Stunner. So we can't get the SVG with the Editor closed.

Regarding the confirmation: I think it's okay with the Dropdown. I just think the circular arrow icon should be part of the "Revert" dropdown toggle. When the content is expanded, you can then change the whole thing to an inline Alert [1] for example, making it clear where the "revert action warning" is contained.

Suggestion for the texts:
- For the warning: "⚠️ This action is permanent. [filename] will be reverted to the last commit."
- For the button: "Revert permanently"

[1] https://www.patternfly.org/v4/components/alert/#inline-alerts-variants
