### ISSUE TITLE
DMN - Option to use alternative image for InputData

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#856]
Currently in DMN, the Input Data is represented visually by an oval. Allow the use of an alternative image, unifying the image with BPMN Data Object image: 
![Image](https://user-images.githubusercontent.com/125682/262669788-82c6198e-7d4e-4565-8641-601e3251b924.gif)

The alternative object should be enabled by the new DMNDiagram attribute `useAlternativeInputDataShape=true`.

FrontEnd related ticket --> https://github.com/apache/incubator-kie-issues/issues/669

Acceptance criteria: 
- DMN engine can parse the new DMNDiagram attribute `useAlternativeInputDataShape`.
- Tests cover parsing of the attribute.

**Comment by yesamer** [comment]
Closing in favor of https://github.com/apache/incubator-kie-issues/issues/856

**Comment by tiagobento** [comment]
Duplicate https://github.com/apache/incubator-kie-issues/issues/669

**Comment by tiagobento** [comment]
@yesamer I see there's mentions to the DMN engine and the DMN Editor here... we already have an issue for this on the DMN Editor side, maybe it's a matter of removing references to the DMN Editor here?

**Comment by yesamer** [comment]
@tiagobento Correct, it's a ticket for the engine side (please notice the label). I would link this to the ticket related to Editor you mentioned, It would be good to test the e2e functionality once both the backend and frontend support it.

**Comment by tiagobento** [comment]
@yesamer Sure, you can reference the DMN Editor ticket here, but I don't think it's accurate to list DMN Editor requirements on the Acceptance criteria of this particular issue, as its scope is the engine.

**Comment by yesamer** [comment]
@tiagobento Reference (in the acceptance criteria) to DMN Editor removed

**Comment by yesamer** [comment]
@baldimir Please help me to better understand, I guess this requirement is already fulfilled in your PR, right?https://github.com/apache/incubator-kie-drools/pull/5669/files#diff-a244db7659004f7f3a77b1b9c61cb172bcd0cc41406a12f741b370afcd4bbec8R34

<img width="1180" alt="Screenshot 2024-01-30 at 16 52 51" src="https://github.com/apache/incubator-kie-issues/assets/16005046/5ad234f2-637b-46ca-be77-c5897d1fb550">

**Comment by yesamer** [comment]
Implemented here https://github.com/apache/incubator-kie-issues/issues/853. Closing as duplicate.
