### ISSUE TITLE
PIM for kogito workflow.

### ISSUE THREAD

**Issue by elguardian** [apache/incubator-kie-issues#861]
[001 - Process Instance Migration Proposal.pdf](https://github.com/apache/incubator-kie-issues/files/14236985/001.-.Process.Instance.Migration.Proposal.pdf)

The idea is to create a system to migrate kogito process from one version to the other. The requirments are:

- Need to support the same persistence pluggable tier from workflow engine
- needs to support batch processing and paralelization (avoid one by one execution)
- need to implement mapping between one version and the other.
- some modifications in the code to support container localization (2 or more versions of the same process and know which one is responsible for executing the workflow)
- Endpoints to implement
- cloud event to indicate the system has beeing migrated (this should go to the data audit as well) 
- revisit the idea of migrated logs (in v7 there were a bit bad)

**Comment by elguardian** [comment]
Problems:
ProtobufObjectMarshallerStrategy and requires both versions loaded.

Logic in here 
https://github.com/kiegroup/jbpm/blob/main/jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/migration/MigrationManager.java


Timers problem (contain information about process etc...)
https://github.com/kiegroup/jbpm/blob/main/jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/migration/MigrationManager.java#L145-L146

https://github.com/apache/incubator-kie-kogito-apps/blob/main/data-index/data-index-storage/data-index-storage-api/src/main/java/org/kie/kogito/index/model/Job.java#L27

**Comment by domhanak** [comment]
Could you please clarify if this is specific to serverless workflows ( sonataflow) or covers business processes too? It is not clear from description.

Is this supposed to bring similar tool as we had in 7.xx kiegroup? [1]
[1] https://github.com/kiegroup/process-migration-service
I understand this issue concerns just the implementation of the logic, please confirm.

**Comment by fjtirado** [comment]
@domhanak I think, by Kogito Workflow, Enrique is referring to this class https://github.com/apache/incubator-kie-kogito-runtimes/blob/main/api/kogito-api/src/main/java/org/kie/kogito/internal/process/runtime/KogitoWorkflowProcess.java

**Comment by elguardian** [comment]
This is related to any workflow regardless the parser. and yes, it is the same concept as you are mentioning in there @domhanak but fixing some of the downsides we had in v7 like the inmemory process migration.

**Comment by domhanak** [comment]
@elguardian Thank you for the details, all clear now.
I ll try to provide feedback ( if any ) by the end of the week.

**Comment by elguardian** [comment]
[TRACK PR] 
https://github.com/apache/incubator-kie-drools/pull/5685
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3403


https://github.com/apache/incubator-kie-kogito-apps/pull/2005
https://github.com/apache/incubator-kie-kogito-examples/pull/1882

**Comment by elguardian** [comment]
@domhanak kind reminder that discussion should occur in ML under the preceptive times involved in this. but I will do an exception in this case in this thread.

**Comment by domhanak** [comment]
@elguardian Yea, I will reply to the ML if anything comes up.

**Comment by elguardian** [comment]
@domhanak plz... do it in here, so I can add your suggestion in PIM.
