### ISSUE TITLE
Adjust pipelines to recent build dependency changes

### ISSUE THREAD

**Issue by jstastny-cz** [apache/incubator-kie-issues#872]
After optaplanner:main and optaplanner-quickstarts:development branches were adjusted to quarkus3 upgrade changes, it's important to adjust pipeline configuration too.

Together with snapshot version unification across KIE projects, optaplanner now depends on snapshot version of drools, which is an important change. Drools project now needs to be part of buildchain configuration for the repository, i.e. drools project should be built as part of both nightly and PR checks pipelines.

Also Drools build chain configuration needs additional entry optaplanner, for drools changes to be validated in optaplanner build. Drools toolchain config also needs removal of the mappings sections, as versions are now identical.

**Comment by baldimir** [comment]
PR is here https://github.com/apache/incubator-kie-kogito-pipelines/pull/1190
