### ISSUE TITLE
Upgrade the `process-usertasks-timer-data-index-persistence-addon-quarkus` to use the proper `kogito-runtime-jvm` image.

### ISSUE THREAD

**Issue by pefernan** [apache/incubator-kie-issues#873]
The `kogito-runtime-jvm:latest` image isn't yet aligned with the quarkus 3 requirements, so the new example `process-usertasks-timer-data-index-persistence-addon-quarkus`(created in https://github.com/apache/incubator-kie-issues/issues/723) is configured to use the `nightly` version.

We should update example config as soon as the image is updated.

**Comment by tiagobento** [comment]
Closing this due to #1285. Please reopen if necessary @pefernan.
