### ISSUE TITLE
Implement DMN 1.5 new FEEL functions support (list replace) in the new DMN Editor

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#904]
DMN 1.5 introduced the following functions:

list replace(list, position, newItem)

 > Examples:
 ```FEEL
 list replace( [2, 4, 7, 8], 3, 6) = [2, 4, 6, 8]
```

 list replace(list, match, newItem)

 > Examples:
 ```FEEL
 list replace ( [2, 4, 7, 8], function(item, newItem) item < newItem, 5) = [5, 5, 7, 8]
 ```

The engine already implemented it in this ticket https://github.com/apache/incubator-kie-issues/issues/507

**Comment by tiagobento** [comment]
Is this the same as https://github.com/apache/incubator-kie-issues/issues/672?

**Comment by yesamer** [comment]
@tiagobento oops... Didn't notice it... Feel free to close this (or the other one)

**Comment by yesamer** [comment]
But wait... I just added `list replace` and nothing related to `range`, please let me check

**Comment by yesamer** [comment]
@tiagobento Let's change the scope of this PR and add list replace only. We will add `range` in the old one. Does make sense? Or propose any other alternative :D

**Comment by tiagobento** [comment]
@yesamer Ok. Will repurpose the other ticket.
