### ISSUE TITLE
Verify backend compliance with Frontend 1.5

### ISSUE THREAD

**Issue by gitgabrio** [apache/incubator-kie-issues#908]
Verify backend DMN is implementing new features 1.5 as defined in frontend ticket
https://github.com/apache/incubator-kie-issues/issues/231

- [x] https://github.com/apache/incubator-kie-drools/pull/5785
- [x] https://github.com/apache/incubator-kie-kogito-apps/pull/2014
- [x] https://github.com/apache/incubator-kie-issues/issues/1014
- [x] Execute DMN editor with current jitexecutor (it can be everything locally built or extended-services locally built link to remote sandbox instance)

@baldimir @yesamer

**Comment by yesamer** [comment]
Range function was introduced in this PR https://github.com/apache/incubator-kie-drools/pull/4279

**Comment by gitgabrio** [comment]
Close this ticket.
Pending frontend issues [here](https://github.com/apache/incubator-kie-issues/issues/403)
