### ISSUE TITLE
Verify Quarkus Extensions metadata in `kogito-runtimes`

### ISSUE THREAD

**Issue by pefernan** [apache/incubator-kie-issues#917]
As explained here: https://github.com/apache/incubator-kie-issues/issues/910

Verify that all the Quarkus Extensions in `kogito-runtimes` have the right metadata in the `pom.xml` & `quarkus-extensions.yaml` 

Quarkus extensions metadata reference: https://quarkus.io/version/main/guides/extension-metadata#quarkus-extension-yaml

**Comment by pefernan** [comment]
Extensions:

| Extension name | Path | Verified |
|-----------------|------|:-------:|
| Kogito Add-On Task Management | ./quarkus/addons/task-management/runtime/ | ✅ |
| Kogito Add-On Process Management | ./quarkus/addons/process-management/runtime/ | ✅ |
| Kogito Add-On Process Definitions | ./quarkus/addons/process-definitions/runtime/ | ✅ |
| Kogito Add-On Mail | ./quarkus/addons/mail/runtime/ | ✅ |
| Kogito Add-On Knative Eventing | ./quarkus/addons/knative/eventing/runtime/ | ✅  |
| Kogito :: Add-Ons :: Quarkus :: Camel :: Runtimes | ./quarkus/addons/camel/runtime/ | ❓  |
| Kogito Add-On Process SVG | ./quarkus/addons/process-svg/runtime/ | ✅  |
| Kogito Add-On MicroProfile Config Service Catalog | ./quarkus/addons/microprofile-config-service-catalog/runtime/ | ✅  |
| Kogito Add-On Explainability | ./quarkus/addons/explainability/runtime/ | ✅  |
| Kogito Add-On Task Notification | ./quarkus/addons/task-notification/runtime/ | ✅ |
| Kogito Add-On Tracing Decision | ./quarkus/addons/tracing-decision/runtime/ | ✅  |
| Kogito Quarkus Add-On Persistence Rocksdb | ./quarkus/addons/persistence/rocksdb/runtime/ | ✅  |
| Kogito Add-On Persistence PostgreSQL | ./quarkus/addons/persistence/postgresql/runtime/ | ✅  |
| Kogito Add-On Persistence FileSystem | ./quarkus/addons/persistence/filesystem/runtime/ | ✅  |
| Kogito Add-On Persistence MongoDB | ./quarkus/addons/persistence/mongodb/runtime/ | ✅  |
| Kogito Add-On Persistence JDBC | ./quarkus/addons/persistence/jdbc/runtime/ | ✅  |
| Kogito Add-On Persistence Kafka Streams | ./quarkus/addons/persistence/kafka/runtime/ | ✅  |
| Kogito Add-On Persistence Infinispan | ./quarkus/addons/persistence/infinispan/runtime/ | ✅  |
| Kogito Add-Ons Quarkus Jobs - Knative Eventing | ./quarkus/addons/jobs/knative-eventing/runtime/ | ✅  |
| Kogito Add-Ons Quarkus Jobs - Management | ./quarkus/addons/jobs/management/runtime/ | ✅  |
| Kogito Add-Ons Quarkus Jobs - Messaging | ./quarkus/addons/jobs/messaging/runtime/ | ✅  |
| Kogito Add-On Monitoring Elastic | ./quarkus/addons/monitoring/elastic/runtime/ | ✅  |
| Kogito Add-On Monitoring Prometheus | ./quarkus/addons/monitoring/prometheus/runtime/ | ✅  |
| Kogito Add-On Events Decisions | ./quarkus/addons/events/decisions/runtime/ | ✅  |
| Kogito Add-On Events MongoDB | ./quarkus/addons/events/mongodb/runtime/ | ✅  |
| Kogito :: Add-Ons :: Events :: Event-Driven Rules :: Quarkus | ./quarkus/addons/events/rules/runtime/ | ✅  |
| Kogito Add-On Events Predictions | ./quarkus/addons/events/predictions/runtime/ | ✅  |
| Kogito Add-On Events Process | ./quarkus/addons/events/process/runtime/ | ✅ |
| Kogito Add-On Kubernetes | ./quarkus/addons/kubernetes/runtime/ | ✅  |
| Kogito Add-On Messaging | ./quarkus/addons/messaging/runtime/ | ✅  |
| Kogito :: Quarkus Rules Extension :: Runtime | ./quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules/ | ✅  |
| Kogito :: Quarkus Processes Extension :: Runtime | ./quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes/ | ✅  |
| Kogito :: Quarkus Decisions Extension :: Runtime | ./quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions/ | ✅  |
| Kogito :: Quarkus Serverless Workflow Extension :: Runtime | ./quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/ | ✅  |
| Kogito :: Quarkus Predictions Extension :: Runtime | ./quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions/ | ✅  |
| Kogito :: Quarkus Extension :: Runtime | ./quarkus/extensions/kogito-quarkus-extension/kogito-quarkus/ | ✅  |

**Comment by ricardozanini** [comment]
@pefernan what does this list means?

**Comment by pefernan** [comment]
@ricardozanini that's the list of `quarkus-extension.yaml` in kogito-runtimes, I'm going through the list to update the metadata.
