### ISSUE TITLE
jBPM

### ISSUE THREAD

**Issue by FireBurn** [apache/incubator-kie-issues#940]
Hi

Are there any plans to add jBPM into the incubator? 

I currently build the whole shebang and wonder if development might restart under the Apache umbrella

**Comment by elguardian** [comment]
Hi @FireBurn incubator has its own jbpm engine embedded in it. so it is already there.

**Comment by FireBurn** [comment]
Are there any details for that and how to build it?

**Comment by FireBurn** [comment]
Is there any information or discussions where this was decided?

**Comment by yesamer** [comment]
Hi @FireBurn you can find the jBPM code here https://github.com/apache/incubator-kie-kogito-runtimes/tree/main/jbpm
This decision was a result of the Kogito initiative started more than 4 years ago in the KIE community.
The goal of the Kogito initiative is to make our Business Automation suite cloud native. 
You can learn more about Kogito here https://kogito.kie.org/
