### ISSUE TITLE
Executable model is not properly generated for rule constraint containing an expression

### ISSUE THREAD

**Issue by baldimir** [apache/incubator-kie-issues#941]
When having a DRL rule with a constraint like 
`$a : Address($booleanVariable: (street != null))`
the build generates wrong type for the $booleanVariable variable. It uses the type of the street field, instead of using the type of the whole expression. This works without using the executable model.

**Comment by ebonnet31** [comment]
Hi @baldimir 

The initial problem we had was on a **compilation issue** later with this $booleanVariable, **_not on the allocation problem._**
Actually, the allocation was fine.

When we wrote the rule , we really intended an ALLOCATION into the $boolean variable with the value (street != null) NOT a constraint on the Adress with (street != null).

So it seems to us the idea of the correction as reported by the support team does not provide what we reported on the issue.

Best
Emmanuel
