### ISSUE TITLE
Action plan - Exploratory phase of the strategy for implementing the E2E test suite for the new SceSim editor

### ISSUE THREAD

**Issue by ljmotta** [apache/incubator-kie-issues#950]
During the exploratory phase we should focus on:
- Bootstrapping Storybook;
- Creating basic tests;

## Storybook
The Storybook should be fully working with the minimal functionality of a Dev Story migrating the Dev Webapp and an Empty editor Story, to be used as the target of the tests.

## Tests
The tests should cover basic functionalities to help us create the first abstractions and fixtures. This part should also help us to check for technology limitations, such as the requirement of adding `data-testid` or other properties to our components.

**Comment by kbowers-ibm** [comment]
List of functionalities currently implemented in the SceSim Editor that are ready for testing:
- **Functionalities**
  - Cheat sheet panel (just shows static content, worth testing with screenshot to make sure it renders properly?)
  - Copy as XML (confirm that changes in e.g. values/resizing are reflected in the copied xml)
  - Download as XML (confirm that changes in e.g. values/resizing are reflected in the downloaded xml)
  - Table operations
    - Resizing
    - Plus sign to add new row/column
    - Auto Resizing
    - Populating (confirm value is persisted)
    - Context Menus
      - **Scenario**
        - Insert Above
        - Insert Below
        - Insert multiple rows (above and below) (_currently not implemented_)
        - Delete
        - Duplicate
      - **Field**
        - Insert left
        - Insert Right
        - Insert multiple (left and right) (_currently not implemented_)
        - Delete
      - **Instance**
        - Insert left
        - Insert Right
        - Insert multiple (left and right) (_currently not implemented_)
        - Delete
      - **Selection**
        - Copy
        - Cut
        - Paste
        - Reset
    - **Restrictions**
      - There must always be at least one given and expect column in the Test Scenario table, and always one Given column in background table
      - Right clicking on Given/Expect/Scenario Description/# Cells should do nothing (_currently not implemented_)
  - Clipboard
  - Settings panel (_still under development_)
    - Rule
      - KIE Session (confirm value is persisted)
      - AgendaGroup/RuleFlowGroup (confirm value is persisted)
      - Stateless Session (confirm value is persisted)
      - Skip this test scenario during the test (confirm value is persisted)
    - Decision
- Keyboard Shortcuts
