### ISSUE TITLE
CI job getting a node it shouldn't get

### ISSUE THREAD

**Issue by baldimir** [apache/incubator-kie-issues#955]
In my kogito-images PR job, the job is failing, because it is getting a wrong node. See log here: 
https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/97/console

**Comment by cimbalek** [comment]
Should be solved by
https://github.com/apache/incubator-kie-kogito-pipelines/pull/1184

**Comment by baldimir** [comment]
I see the PR merged. Can we close this issue then please? Or does it need some more testing?
