### ISSUE TITLE
Quarkus LTS 3.8.x upgrade

### ISSUE THREAD

**Issue by porcelli** [apache/incubator-kie-issues#958]
initial repos involved: drools, runtime and apps

- https://github.com/apache/incubator-kie-issues/issues/1092
- https://github.com/apache/incubator-kie-optaplanner/pull/3070
- https://github.com/apache/incubator-kie-kogito-apps/pull/2018
- https://github.com/apache/incubator-kie-tools/pull/2212
- https://github.com/apache/incubator-kie-tools/pull/2272

**Comment by lucamolteni** [comment]
Optaplanner needs the DevUI to be migrated to the new version see https://issues.redhat.com/projects/PLANNER/issues/PLANNER-2937?filter=allopenissues

Also there are failures on the operator

**Comment by porcelli** [comment]
3.8 is the new Quarkus LTS, thus the reason to evaluate the impact of the upgrade.

There's indeed impact on DevUI, I'm investigating this right now.

In regard Optaplanner operator, it was using a fixed 3.0.0.Final version; and to be honest I'm not sure if this was even working. Anyone tried it @lucamolteni ?

**Comment by lucamolteni** [comment]
> In regard Optaplanner operator, it was using a fixed 3.0.0.Final version; and to be honest I'm not sure if this was even working. Anyone tried it @lucamolteni ?

Tests in the operator are working fine, I've opened a PR

https://github.com/apache/incubator-kie-optaplanner/pull/3063

**Comment by lucamolteni** [comment]
Optaplanner PR is here https://github.com/apache/incubator-kie-optaplanner/pull/3070

**Comment by jstastny-cz** [comment]
Is the evaluation complete and should relevant tickets for upgrades in respective repositories be created?

**Comment by lucamolteni** [comment]
> Is the evaluation complete and should relevant tickets for upgrades in respective repositories be created?

@mariofusco

**Comment by tiagobento** [comment]
Both Quarkus Dev UIs we have are already adapted to Quarkus 3.8. 

See:
- https://github.com/apache/incubator-kie-kogito-apps/pull/2018; and
- https://github.com/apache/incubator-kie-tools/pull/2212

Note that `jbpm-quarkus-devui` is moving to `kie-tools` @ https://github.com/apache/incubator-kie-issues/issues/966
