### ISSUE TITLE
DMN Runner enhancements and bug fixes: `uniforms-patternfly` and table

### ISSUE THREAD

**Issue by ljmotta** [apache/incubator-kie-issues#96]
Spliting the #26 into two. This issue groups DMN Runner enhancements and bug fix.

### Table

- [x] Scroll sync of Inputs and Outputs breaks for Table mode after updating Inputs from another tab

### **uniforms-patternfly**

- [x] Checkboxes values are “undefined” if not clicked. This breaks the evaluation with JIT Executor.
- [ ] KOGITO-5436 Custom components for DMN types on DMN forms
- [x] KOGITO-7516 DMN Runner inputs fail silently for Date Time parsing of input formatted as yyyy-MM-dd'T'HH:mm:ss

### Persistence

- [x] KOGITO-8046 KIE Sandbox with Runner fails to recognize inputs from DMN model, but downloading and uploading the same DMN model no changes allows form to work

## **Enhancements**

- [ ] Share URL for importing the same project at the same place.

**Comment by tiagobento** [comment]
@ljmotta Can you please reassess this issue? Ideally we would close it and create one issue for each of the tasks listed here. Also, I think some of them might be resolved or already covered by an existing issue.

Also, I think we can drop "Share URL for importing the same project at the same place.". I don't see this as a requirement for the time being.

**Comment by ljmotta** [comment]
@tiagobento Sure. I'll check them.

**Comment by ljmotta** [comment]
These issues are not happening anymore:
 - "Scroll sync of Inputs and Outputs breaks for Table mode after updating Inputs from another tab"
 - "Checkboxes values are “undefined” if not clicked. This breaks the evaluation with JIT Executor."
 - "KOGITO-7516 DMN Runner inputs fail silently for Date Time parsing of input formatted as yyyy-MM-dd'T'HH:mm:ss"
 - "KOGITO-8046 KIE Sandbox with Runner fails to recognize inputs from DMN model, but downloading and uploading the same DMN model no changes allows form to work"


The "KOGITO-5436 Custom components for DMN types on DMN forms" is already covered in #19.
As the "Share URL for importing the same project at the same place" is not a requirement anymore I'm going to close this issue.
