### ISSUE TITLE
Upgrade `kie-tools` to Java 17, Maven 3.9.6, and Quarkus 3

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#960]
There's a complication here, since we still have three big packages (Serverless Workflow Diagram Editor, BPMN, DMN, and SceSim Editors, and DashBuilder) on `kie-tools` that need GWT, and as you know, GWT together with Java upgrades usually require some work. We're on GWT 2.10, which should already support Java 17, but we'll know more once we try it.

**Comment by yesamer** [comment]
@tiagobento I already did this analysis some time ago (https://github.com/apache/incubator-kie-issues/issues/40#issuecomment-1424170663), I'm afraid that setting any Java 9+ version to compile our GWT code will result in a failure. Consider that we're currently still compiling it with 1.8 ( [see here](https://github.com/apache/incubator-kie-tools/blob/main/packages/stunner-editors/pom.xml#L235) ). 
I guess the only realistic solution is to keep 1.8 as target as source in maven with JDK 17, but that will require some adjustments (on tests side in particular)
