### ISSUE TITLE
Cleanup `kogito-apps` repo removing everything that has moved to `kie-tools`

### ISSUE THREAD

**Issue by porcelli** [apache/incubator-kie-issues#962]

**Comment by fantonangeli** [comment]
During the migration of the `@kogito-apps/runtime-tools-dev-ui-webapp` I created a list of the UI components, related to the DevUI, which are migrated to `kie-tools` repository. 
It was specific for that task but maybe can be helpful:
https://docs.google.com/spreadsheets/d/1oAd-shEsu6JMxau3znNPWtI1lv0G5fTIAHd7CaGGF7Y

**Comment by tiagobento** [comment]
So far this list includes:
1. SonataFlow Quarkus Dev UI
2. BPMN Quarkus Dev UI
3. Everything on `ui-packages`, including Trusty-related stuff
4. Everything related to Trusty
5. Task and Management consoles

Please feel free to add to it if there's more.
