### ISSUE TITLE
Support ConditionalExpr in Drools executable model

### ISSUE THREAD

**Issue by baldimir** [apache/incubator-kie-issues#968]
When not using executable model, it is possible to write an expression like this in a rule when section: 
`$p : Person($booleanVariable: (name != null ? true : false))`

This doesn't work in executable model as it ends with UnsupportedOperationException. 
Test case for this: https://gist.github.com/baldimir/d3fc199aaecdaec9616b3b6759edf2e2

**Comment by ebonnet31** [comment]
Hi @baldimir 
did you see our previous remark on the previous fix ?

https://github.com/apache/incubator-kie-issues/issues/941#issuecomment-1959745566

Best
Emmanuel
