### ISSUE TITLE
When opening a DMN model of 1.2-1.3 level specification, migration to 1.5 occurs if any change made - have option to open in Legacy Editor first

### ISSUE THREAD

**Issue by timwuthenow** [apache/incubator-kie-issues#975]
When working with projects that have DMN models in them for Kogito (or even KIE Server), if you edit a DMN using the new editor, the project gets migrated to DMN 1.5 specification. When this change is committed the model will forever be 1.5, but not all engines that we run in are compatible with this. Having either A) a confirmation to push the project forward so you're aware of the change or B) Opening by default in legacy editor and then asking to go to 1.5 would be preferred. This would be helpful in the cases when working with a project that might not be ready to go to 1.5 yet (e.g. Java 17 might not be certified yet, I'm still running KIE Server, etc). What makes this harder is that you don't know when you've done this, that that is what occurs until you go to execute your model in your project when you get an error similar to the one below. This would help prevent potentially major rework in projects that aren't ready to move forward right away.

~~~log
[ERROR] Errors: 
[ERROR]   GreetingResourceTest.testHelloEndpoint » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor#generateSources threw an exception: java.lang.RuntimeException: DMN Validation schema and model validation contained errors
You may configure kogito.decisions.validation=IGNORE to ignore validation errors
DMN Validation errors:
: Failed XML validation of DMN file: cvc-elt.1.a: Cannot find the declaration of element 'dmn:definitions'.,
: One of the supplied DMN Models has failed validation; cannot proceed to validation of the remaining DMN Models.
        at org.kie.kogito.codegen.decision.DecisionValidation.processMessagesHandleErrors(DecisionValidation.java:195)
        at org.kie.kogito.codegen.decision.DecisionValidation.dmnValidateResources(DecisionValidation.java:90)
        at org.kie.kogito.codegen.decision.DecisionCodegen.loadModelsAndValidate(DecisionCodegen.java:103)
~~~

**Comment by tiagobento** [comment]
@timwuthenow Yeah, I understand that automatically upgrading to 1.5 might have implications for users that are running their DMNs on older runtimes. However, KIE Sandbox and all the new tooling (i.e., not Business Central) are designed to be compatible with Kogito Runtimes.

The DMN Editor released with Apache KIE 10 will be compatible with DMN 1.5, and Kogito Runtimes will too.

I'm not a big fan of using the legacy DMN Editor by default, to be honest, but a blocking alert popup might be useful when making a change to a DMN < 1.5 file before it gets automatically upgraded to 1.5.

Not sure what people think about carrying older runtimes as supported, or how much of a show-stopper it is for people trying the new tooling to not have the ability to continue with their older runtimes before upgrading.

I'd love to hear @porcelli's and @baldimir's opinion on this.

**Comment by yesamer** [comment]
This is a point we deeply discussed some months ago, and I tend to agree with @tiagobento, for the following reasons:

- DMN 1.5 is retro-compatible with the previous versions. That means no actions are required from the user to update the version.
- As @tiagobento correctly mentioned, DMN Editor must be compatible with the current engine side. The backend code is currently based on JDK 17, and that would be the same if you're using DMN 1.2 or DMN 1.5. In a few words, DMN versions are not bound to a Java version.
- The maintenance of the old editor (together with the new one) is an effort our team can't afford, in my opinion.

**Comment by tiagobento** [comment]
I guess it would be nice for us have at least a message on the old Editor saying "You opened a DMN with a version higher than supported. The latest version supported on the legacy DMN Editor is 1.2" or something like that. Do you think that would be too much effort @yesamer? Might be the last nice thing we do for the legacy Editor, and might help users to understand the error message a little better, saving us time in the future. WDYT?

**Comment by yesamer** [comment]
@tiagobento Yep it makes sense, and the required effort is low. If we agree that is the only implementation required by this ticket, please feel free to assign it to me.
