### ISSUE TITLE
Fix null check during constraint evaluation inside rule engine

### ISSUE THREAD

**Issue by gitgabrio** [apache/incubator-kie-issues#978]
The following constraint

`$p : Person($amount: (money == null ? BigDecimal.valueOf(100.0) : money)) `

seems to raise a `java.lang.AssertionError: A reference was unexpectedly null.` when `Person.money == null`

Scope of the ticket
1. create  tests with `Person.money ` populated and not
2. verify the test without the  `Person.money ` raise the mentioned exception
3. check/fix the code behind it

**Comment by mariofusco** [comment]
Fixed by https://github.com/apache/incubator-kie-drools/commit/ff21d1c09202f5ac7f031e68498601b5ab74d9c4
