### ISSUE TITLE
Management Console failing to display process instance details due to missing milestones property in graphql reply

### ISSUE THREAD

**Issue by treivize** [apache/incubator-kie-issues#989]
**Problem statement:**

Building and running the data-index service and the management console based on master branch, it seems that milestones attribute in graphql reply can be now null instead of being an empty array as before. 

I have the feeling that it is following this big refactor on the serialization of the process instance feed between the kogito runtime and the data-index service: https://github.com/apache/incubator-kie-kogito-apps/commit/ffc8500bbdfb979598392719d3b629a673ee5bdf

```
{
    "data": {
        "ProcessInstances": [
            {
                "id": "ceb70cda-0495-4c61-abba-ebd7e65d8788",
                "processId": "myprocess",
                "processName": "MyProcess",
                "businessKey": null,
                "parentProcessInstanceId": null,
                "parentProcessInstance": null,
                "roles": null,
                "variables": {...},
                "state": "COMPLETED",
                "start": "2024-03-05T09:01:28.173Z",
                "lastUpdate": "2024-03-05T09:02:10.503Z",
                "end": null,
                "addons": [
                    "process-management",
                    "process-svg",
                    "cloudevents",
                    "prometheus-monitoring",
                    "monitoring",
                    "mongodb-persistence",
                    "jobs-management"
                ],
                "endpoint": "http://kogito-runtime.kogito.svc.cluster.local:8080/myprocess",
                "serviceUrl": "http://kogito-runtime.kogito.orms-dev-sandbox.svc.cluster.local:8080",
                "source": null,
                "error": null,
                "childProcessInstances": [],
                "nodes": [...],
                "milestones": null,
                "__typename": "ProcessInstance"
            }
        ]
    }
}
```

**Proposed solution:**
Add a simple optional chaining/null check in UI code here:

https://github.com/apache/incubator-kie-kogito-apps/blob/main/ui-packages/packages/process-details/src/envelope/components/ProcessDetails/ProcessDetails.tsx#L353

**Comment by yesamer** [comment]
@treivize Closing as fixed by https://github.com/apache/incubator-kie-issues/issues/833. Thanks again for your contribution!
