### ISSUE TITLE
`uniforms-patternfly` "AddField" or "DelField" are not supported in the DMN Runner Table view

### ISSUE THREAD

**Issue by ljmotta** [apache/incubator-kie-issues#99]
To render a row of the DMN runner table we use the `uniforms-patternfly` library. This feature isn't fully supported as the `AddField` and `DelField` are not working correctly.

Reference: [heating.dmn](https://github.com/kiegroup/kie-assets-library/blob/5a7a7be798af01e58d27e537ea10637ddac31e4f/kie-assets-library-assets/src/main/resources/smarthouse/decisions/03/heating.dmn)

- The + signal doens't work in the DMN Runner Table;
- Should have a - signal to remove the additional data;
- The Problems tab doens't work correctly, as it's missing all problems related to the "Execution";

![Screenshot 2023-01-31 192527](https://user-images.githubusercontent.com/24302289/215898022-f2b26d66-36d3-4fef-abeb-0aa3753b307c.png)

![Screenshot 2023-01-31 192546](https://user-images.githubusercontent.com/24302289/215898031-958996d0-72d4-4778-8f6f-9f6f44498890.png)

**Comment by tiagobento** [comment]
Isn't this the same as #167 ?

**Comment by ljmotta** [comment]
Yes, it's. I'm going to close this one.
