### ISSUE TITLE
Document DMN 1.5 new features

### ISSUE THREAD

**Issue by gitgabrio** [apache/incubator-kie-issues#996]
Create a Box note with new DMN 1.5 features implemented

**Comment by gitgabrio** [comment]
[Box note](https://ibm.ent.box.com/notes/1464480451005)

**Comment by LightGuard** [comment]
@gitgabrio Is this done, or one of the other statuses (In Review, or In Progress)?

**Comment by gitgabrio** [comment]
@LightGuard Nope. I'll close this when the documentation of new DMN 1.5 features will be definetely done

**Comment by gitgabrio** [comment]
@baldimir I'm working at https://github.com/apache/incubator-kie-issues/issues/822 at the same time.
Some of the new features does not ends up in the FEEL handbook, so we'll investigate where to document them
